#Clone TSLib and setup requirements

In [1]:
!rm -rf /content/Time-Series-Library
!git clone https://github.com/thuml/Time-Series-Library.git /content/Time-Series-Library
!ls -la /content/Time-Series-Library

Cloning into '/content/Time-Series-Library'...
remote: Enumerating objects: 2247, done.
remote: Counting objects: 100% (31/31), done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 2247 (delta 16), reused 6 (delta 6), pack-reused 2216 (from 3)
Receiving objects: 100% (2247/2247), 78.43 MiB | 14.09 MiB/s, done.
Resolving deltas: 100% (1531/1531), done.
total 144
drwxr-xr-x 11 root root  4096 Feb 23 19:40 .
drwxr-xr-x  1 root root  4096 Feb 23 19:40 ..
-rw-r--r--  1 root root  1496 Feb 23 19:40 CONTRIBUTING.md
drwxr-xr-x  2 root root  4096 Feb 23 19:40 data_provider
-rw-r--r--  1 root root   809 Feb 23 19:40 docker-compose.yml
-rw-r--r--  1 root root   822 Feb 23 19:40 Dockerfile
drwxr-xr-x  2 root root  4096 Feb 23 19:40 exp
drwxr-xr-x  8 root root  4096 Feb 23 19:40 .git
-rw-r--r--  1 root root  2576 Feb 23 19:40 .gitignore
drwxr-xr-x  2 root root  4096 Feb 23 19:40 layers
-rw-r--r--  1 root root  1084 Feb 23 19:40 LICENSE
drwxr-xr-x  2 root root  4096 Feb 23 19:40 models
drwxr-xr-x  2 root root  4096 Feb 23 19:40 pic
-rw-r--r--  1 root root 29893 Feb 23 19:40 README.md
-rw-r--r--  1 root root 27806 Feb 23 19:40 README_zh.md
-rw-r--r--  1 root root   517 Feb 23 19:40 requirements.txt
-rw-r--r--  1 root root 14671 Feb 23 19:40 run.py
drwxr-xr-x  8 root root  4096 Feb 23 19:40 scripts
drwxr-xr-x  2 root root  4096 Feb 23 19:40 tutorial
drwxr-xr-x  2 root root  4096 Feb 23 19:40 utils

In [2]:
import re

req = "/content/Time-Series-Library/requirements.txt"
drop = re.compile(r"^\s*(timesfm|paxml|praxis|jaxlib|jax|jaxtyping|datasets==4.4.1)\b", re.IGNORECASE)

with open(req, "r") as f:
    lines = f.readlines()

new_lines = [ln for ln in lines if not drop.match(ln)]

with open(req, "w") as f:
    f.writelines(new_lines)

print("Removed:", ["timesfm","paxml","praxis","jax","jaxlib","jaxtyping", "datasets==4.4.1"])

Removed: ['timesfm', 'paxml', 'praxis', 'jax', 'jaxlib', 'jaxtyping', 'datasets==4.4.1']

In [3]:
%cd /content/Time-Series-Library
!pip install -r requirements.txt

/content/Time-Series-Library
Collecting einops==0.8.1 (from -r requirements.txt (line 1))
  Downloading einops-0.8.1-py3-none-any.whl.metadata (13 kB)
Collecting local-attention==1.11.2 (from -r requirements.txt (line 2))
  Downloading local_attention-1.11.2-py3-none-any.whl.metadata (929 bytes)
Collecting reformer-pytorch==1.4.4 (from -r requirements.txt (line 3))
  Downloading reformer_pytorch-1.4.4-py3-none-any.whl.metadata (764 bytes)
Collecting numpy==2.1.2 (from -r requirements.txt (line 5))
  Downloading numpy-2.1.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.9/60.9 kB 3.6 MB/s eta 0:00:00
Requirement already satisfied: scipy==1.16.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 6)) (1.16.3)
Collecting scikit-learn==1.7.2 (from -r requirements.txt (line 7))
  Downloading scikit_learn-1.7.2-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (11 kB)
Collecting pandas==2.3.3 (from -r requirements.txt (line 8))
  Downloading pandas-2.3.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (91 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.2/91.2 kB 12.1 MB/s eta 0:00:00
Collecting matplotlib==3.10.8 (from -r requirements.txt (line 9))
  Downloading matplotlib-3.10.8-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (52 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.8/52.8 kB 6.4 MB/s eta 0:00:00
Collecting sktime==0.40.1 (from -r requirements.txt (line 10))
  Downloading sktime-0.40.1-py3-none-any.whl.metadata (33 kB)
Collecting sympy==1.13.1 (from -r requirements.txt (line 11))
  Downloading sympy-1.13.1-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: PyWavelets==1.9.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 12)) (1.9.0)
Collecting datasets==4.5.0 (from -r requirements.txt (line 13))
  Downloading datasets-4.5.0-py3-none-any.whl.metadata (19 kB)
Collecting tqdm==4.66.5 (from -r requirements.txt (line 15))
  Downloading tqdm-4.66.5-py3-none-any.whl.metadata (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.6/57.6 kB 7.4 MB/s eta 0:00:00
Collecting patool==4.0.3 (from -r requirements.txt (line 16))
  Downloading patool-4.0.3-py2.py3-none-any.whl.metadata (4.6 kB)
Collecting transformers==4.57.3 (from -r requirements.txt (line 18))
  Downloading transformers-4.57.3-py3-none-any.whl.metadata (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 5.4 MB/s eta 0:00:00
Collecting huggingface_hub==0.36.0 (from -r requirements.txt (line 19))
  Downloading huggingface_hub-0.36.0-py3-none-any.whl.metadata (14 kB)
Collecting chronos-forecasting==2.2.1 (from -r requirements.txt (line 20))
  Downloading chronos_forecasting-2.2.1-py3-none-any.whl.metadata (23 kB)
Collecting tirex-ts==1.3.0 (from -r requirements.txt (line 21))
  Downloading tirex_ts-1.3.0-py3-none-any.whl.metadata (15 kB)
Collecting gluonts==0.16.2 (from -r requirements.txt (line 25))
  Downloading gluonts-0.16.2-py3-none-any.whl.metadata (9.8 kB)
Collecting lightning==2.6.0 (from -r requirements.txt (line 26))
  Downloading lightning-2.6.0-py3-none-any.whl.metadata (44 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.9/44.9 kB 5.6 MB/s eta 0:00:00
Collecting hydra-core==1.3.0 (from -r requirements.txt (line 27))
  Downloading hydra_core-1.3.0-py3-none-any.whl.metadata (4.8 kB)
Collecting orjson==3.11.5 (from -r requirements.txt (line 28))
  Downloading orjson-3.11.5-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (41 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.6/41.6 kB 4.7 MB/s eta 0:00:00
Collecting tensorboard==2.20.0 (from -r requirements.txt (line 29))
  Downloading tensorboard-2.20.0-py3-none-any.whl.metadata (1.8 kB)
Collecting python-dotenv==1.0.0 (from -r requirements.txt (line 30))
  Downloading python_dotenv-1.0.0-py3-none-any.whl.metadata (21 kB)
Collecting hyper-connections>=0.1.8 (from local-attention==1.11.2->-r requirements.txt (line 2))
  Downloading hyper_connections-0.4.9-py3-none-any.whl.metadata (6.7 kB)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (from local-attention==1.11.2->-r requirements.txt (line 2)) (2.10.0+cu128)
Collecting axial-positional-embedding>=0.1.0 (from reformer-pytorch==1.4.4->-r requirements.txt (line 3))
  Downloading axial_positional_embedding-0.3.12-py3-none-any.whl.metadata (4.3 kB)
Collecting product-key-memory (from reformer-pytorch==1.4.4->-r requirements.txt (line 3))
  Downloading product_key_memory-0.3.0-py3-none-any.whl.metadata (4.9 kB)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn==1.7.2->-r requirements.txt (line 7)) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn==1.7.2->-r requirements.txt (line 7)) (3.6.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas==2.3.3->-r requirements.txt (line 8)) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas==2.3.3->-r requirements.txt (line 8)) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas==2.3.3->-r requirements.txt (line 8)) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib==3.10.8->-r requirements.txt (line 9)) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib==3.10.8->-r requirements.txt (line 9)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib==3.10.8->-r requirements.txt (line 9)) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib==3.10.8->-r requirements.txt (line 9)) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib==3.10.8->-r requirements.txt (line 9)) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib==3.10.8->-r requirements.txt (line 9)) (11.3.0)
Requirement already satisfied: pyparsing>=3 in /usr/local/lib/python3.12/dist-packages (from matplotlib==3.10.8->-r requirements.txt (line 9)) (3.3.2)
Collecting scikit-base<0.14.0,>=0.6.1 (from sktime==0.40.1->-r requirements.txt (line 10))
  Downloading scikit_base-0.13.1-py3-none-any.whl.metadata (8.8 kB)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy==1.13.1->-r requirements.txt (line 11)) (1.3.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets==4.5.0->-r requirements.txt (line 13)) (3.24.2)
Collecting pyarrow>=21.0.0 (from datasets==4.5.0->-r requirements.txt (line 13))
  Downloading pyarrow-23.0.1-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.1 kB)
Requirement already satisfied: dill<0.4.1,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets==4.5.0->-r requirements.txt (line 13)) (0.3.8)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets==4.5.0->-r requirements.txt (line 13)) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets==4.5.0->-r requirements.txt (line 13)) (0.28.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets==4.5.0->-r requirements.txt (line 13)) (3.6.0)
Requirement already satisfied: multiprocess<0.70.19 in /usr/local/lib/python3.12/dist-packages (from datasets==4.5.0->-r requirements.txt (line 13)) (0.70.16)
Requirement already satisfied: fsspec<=2025.10.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.10.0,>=2023.1.0->datasets==4.5.0->-r requirements.txt (line 13)) (2025.3.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets==4.5.0->-r requirements.txt (line 13)) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.3->-r requirements.txt (line 18)) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.3->-r requirements.txt (line 18)) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.3->-r requirements.txt (line 18)) (0.7.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub==0.36.0->-r requirements.txt (line 19)) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub==0.36.0->-r requirements.txt (line 19)) (1.2.0)
Requirement already satisfied: accelerate<2,>=0.34 in /usr/local/lib/python3.12/dist-packages (from chronos-forecasting==2.2.1->-r requirements.txt (line 20)) (1.12.0)
Requirement already satisfied: pydantic<3,>=1.7 in /usr/local/lib/python3.12/dist-packages (from gluonts==0.16.2->-r requirements.txt (line 25)) (2.12.3)
Requirement already satisfied: toolz~=0.10 in /usr/local/lib/python3.12/dist-packages (from gluonts==0.16.2->-r requirements.txt (line 25)) (0.12.1)
Collecting lightning-utilities<2.0,>=0.10.0 (from lightning==2.6.0->-r requirements.txt (line 26))
  Downloading lightning_utilities-0.15.3-py3-none-any.whl.metadata (5.5 kB)
Collecting torchmetrics<3.0,>0.7.0 (from lightning==2.6.0->-r requirements.txt (line 26))
  Downloading torchmetrics-1.8.2-py3-none-any.whl.metadata (22 kB)
Collecting pytorch-lightning (from lightning==2.6.0->-r requirements.txt (line 26))
  Downloading pytorch_lightning-2.6.1-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: omegaconf~=2.2 in /usr/local/lib/python3.12/dist-packages (from hydra-core==1.3.0->-r requirements.txt (line 27)) (2.3.0)
Requirement already satisfied: antlr4-python3-runtime==4.9.* in /usr/local/lib/python3.12/dist-packages (from hydra-core==1.3.0->-r requirements.txt (line 27)) (4.9.3)
Requirement already satisfied: absl-py>=0.4 in /usr/local/lib/python3.12/dist-packages (from tensorboard==2.20.0->-r requirements.txt (line 29)) (1.4.0)
Requirement already satisfied: grpcio>=1.48.2 in /usr/local/lib/python3.12/dist-packages (from tensorboard==2.20.0->-r requirements.txt (line 29)) (1.78.0)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.12/dist-packages (from tensorboard==2.20.0->-r requirements.txt (line 29)) (3.10.2)
Requirement already satisfied: protobuf!=4.24.0,>=3.19.6 in /usr/local/lib/python3.12/dist-packages (from tensorboard==2.20.0->-r requirements.txt (line 29)) (5.29.6)
Requirement already satisfied: setuptools>=41.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard==2.20.0->-r requirements.txt (line 29)) (75.2.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard==2.20.0->-r requirements.txt (line 29)) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from tensorboard==2.20.0->-r requirements.txt (line 29)) (3.1.5)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate<2,>=0.34->chronos-forecasting==2.2.1->-r requirements.txt (line 20)) (5.9.5)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.10.0,>=2023.1.0->datasets==4.5.0->-r requirements.txt (line 13)) (3.13.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets==4.5.0->-r requirements.txt (line 13)) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets==4.5.0->-r requirements.txt (line 13)) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets==4.5.0->-r requirements.txt (line 13)) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets==4.5.0->-r requirements.txt (line 13)) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets==4.5.0->-r requirements.txt (line 13)) (0.16.0)
Collecting torch-einops-utils>=0.0.20 (from hyper-connections>=0.1.8->local-attention==1.11.2->-r requirements.txt (line 2))
  Downloading torch_einops_utils-0.0.30-py3-none-any.whl.metadata (2.1 kB)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.7->gluonts==0.16.2->-r requirements.txt (line 25)) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.7->gluonts==0.16.2->-r requirements.txt (line 25)) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.7->gluonts==0.16.2->-r requirements.txt (line 25)) (0.4.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas==2.3.3->-r requirements.txt (line 8)) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets==4.5.0->-r requirements.txt (line 13)) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets==4.5.0->-r requirements.txt (line 13)) (2.5.0)
INFO: pip is looking at multiple versions of torch to determine which version is compatible with other requirements. This could take a while.
Collecting torch (from local-attention==1.11.2->-r requirements.txt (line 2))
  Downloading torch-2.10.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (31 kB)
  Downloading torch-2.9.1-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (30 kB)
  Downloading torch-2.9.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (30 kB)
  Downloading torch-2.8.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (30 kB)
  Downloading torch-2.7.1-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (29 kB)
  Downloading torch-2.7.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (29 kB)
  Downloading torch-2.6.0-cp312-cp312-manylinux1_x86_64.whl.metadata (28 kB)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch->local-attention==1.11.2->-r requirements.txt (line 2)) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch->local-attention==1.11.2->-r requirements.txt (line 2)) (3.1.6)
Collecting nvidia-cuda-nvrtc-cu12==12.4.127 (from torch->local-attention==1.11.2->-r requirements.txt (line 2))
  Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.4.127 (from torch->local-attention==1.11.2->-r requirements.txt (line 2))
  Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.4.127 (from torch->local-attention==1.11.2->-r requirements.txt (line 2))
  Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch->local-attention==1.11.2->-r requirements.txt (line 2))
  Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch->local-attention==1.11.2->-r requirements.txt (line 2))
  Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch->local-attention==1.11.2->-r requirements.txt (line 2))
  Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.5.147 (from torch->local-attention==1.11.2->-r requirements.txt (line 2))
  Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch->local-attention==1.11.2->-r requirements.txt (line 2))
  Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch->local-attention==1.11.2->-r requirements.txt (line 2))
  Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparselt-cu12==0.6.2 (from torch->local-attention==1.11.2->-r requirements.txt (line 2))
  Downloading nvidia_cusparselt_cu12-0.6.2-py3-none-manylinux2014_x86_64.whl.metadata (6.8 kB)
Collecting nvidia-nccl-cu12==2.21.5 (from torch->local-attention==1.11.2->-r requirements.txt (line 2))
  Downloading nvidia_nccl_cu12-2.21.5-py3-none-manylinux2014_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvtx-cu12==12.4.127 (from torch->local-attention==1.11.2->-r requirements.txt (line 2))
  Downloading nvidia_nvtx_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch->local-attention==1.11.2->-r requirements.txt (line 2))
  Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting triton==3.2.0 (from torch->local-attention==1.11.2->-r requirements.txt (line 2))
  Downloading triton-3.2.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.4 kB)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from werkzeug>=1.0.1->tensorboard==2.20.0->-r requirements.txt (line 29)) (3.0.3)
Collecting colt5-attention>=0.10.14 (from product-key-memory->reformer-pytorch==1.4.4->-r requirements.txt (line 3))
  Downloading CoLT5_attention-0.11.1-py3-none-any.whl.metadata (737 bytes)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets==4.5.0->-r requirements.txt (line 13)) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets==4.5.0->-r requirements.txt (line 13)) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets==4.5.0->-r requirements.txt (line 13)) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets==4.5.0->-r requirements.txt (line 13)) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets==4.5.0->-r requirements.txt (line 13)) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets==4.5.0->-r requirements.txt (line 13)) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets==4.5.0->-r requirements.txt (line 13)) (1.22.0)
Downloading einops-0.8.1-py3-none-any.whl (64 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.4/64.4 kB 7.5 MB/s eta 0:00:00
Downloading local_attention-1.11.2-py3-none-any.whl (9.5 kB)
Downloading reformer_pytorch-1.4.4-py3-none-any.whl (16 kB)

In [1]:
import torch, numpy, pandas; print('torch', torch.__version__)

torch 2.6.0+cu124

# Run CNN-GRU-SPN-Gamma

In [3]:
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
CNN1D + skip + GRU encoder + conditional SPN-Gamma decoder for JOINT multi-horizon forecasting.

Goal: model the full predictive distribution p(y_{t+1:t+H} | x_{t-W+1:t}) of monthly temperature anomalies,
with tractable exact log-likelihood, exact posterior responsibilities p(k|x,y), and explicit horizon-wise
factorization constraints.

Model summary:
- Encoder: 1D CNN with skip connection + GRU to obtain a context embedding h(x).
- Decoder (conditional SPN head): root Sum over K components with neural gating pi_k(h).
  Each component is a Product over horizons, yielding a mixture-of-products that induces cross-horizon
  dependence via the shared latent component k.
- Per horizon and component: signed magnitude model with Bernoulli sign gate s_{k,h}(h) and Gamma mixtures
  for |y_h|, with sign-specific parameters (pos/neg) to capture asymmetry and heavy tails.

Protocol and leakage controls:
- Monthly aggregation is performed first; anomalies are computed per city using a fixed climatology estimated
  only from that city's training years (<= train_end).
- Input gaps are imputed causally inside the past window only (window-only PCHIP, max short-gap), while targets
  are never imputed (windows with missing targets are discarded).
- Geographic generalization: train/val/test are disjoint by cities; time splits are enforced using the horizon
  boundaries (train_end/val_end) and the first/last target year in the horizon.

Evaluation and robustness:
- Metrics include point accuracy (RMSE/MAE), probabilistic quality (CRPS, NLL per horizon), and multivariate
  dependence-aware scoring (Energy Score) computed for (i) joint sampling and (ii) an independent-k baseline
  (per-horizon latent k) to isolate the contribution of cross-horizon coupling.
- Results are reported globally on pooled test windows and additionally by decade/regime (grouped by the first
  horizon year) to assess non-stationarity.
- Sensitivity to held-out city choice is addressed via multiple stratified, disjoint 10-city test sets.
"""

import argparse
import math
import random
import re
import unicodedata
import os
import json
import time
import zipfile
import platform
import sys
import gc

from pathlib import Path

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
import matplotlib.pyplot as plt
from scipy.interpolate import PchipInterpolator
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.preprocessing import StandardScaler
from torch.utils.data import DataLoader, TensorDataset
from scipy.stats import t as student_t, chi2

# KaggleHub import
import kagglehub
from kagglehub import KaggleDatasetAdapter

# ---------------- Path + Config ----------------

KAGGLE_DATASET_REF = "sudalairajkumar/daily-temperature-of-major-cities"
KAGGLE_FILE_PATH = "city_temperature.csv"

WINDOW = 12
HORIZON = 6          # JOINT multi-horizon length (set to 6 or 12)

HIDDEN = 64
K_ROOT = 8           # root Sum fan-out
M_MAG = 4            # magnitude mixture leaves per (k, horizon, sign)

DROPOUT = 0.30
BATCH = 256
EPOCHS = 200
LR = 3e-3
WARMUP = 10
PATIENCE = 20

# preprocessing
MAX_PCHIP_GAP = 2
MIN_MONTHS_PER_YEAR = 10
MIN_TOTAL_YEARS_FOR_CITY = 18 # of ~26 years available
MIN_TRAIN_YEARS_FOR_CLIM = 5  # years with >=10 months, up to 2000

# probabilistic / regularization
ALPHA_FLOOR = 1e-4
BETA_FLOOR = 1e-4
L2_LOG_PARAM = 1e-4
ENTROPY_WEIGHT = 1e-3

# geographic split
VAL_FRACTION = 0.10
MIN_VAL_CITIES = 20
MAX_VAL_CITIES = 60

# test/eval cities
EVAL_N = 10
N_EVAL_SETS = 5         # no of different sets of 10 cities
EVAL_SEED_BASE = 123    # base seed for city selection
SPLIT_SEED_BASE = 1000  # base seed for geographic split (train/wave vs test)

EVAL_MODE = "stratified_sets"   # "fixed" / "stratified_sets"
ENFORCE_DISJOINT_EVAL_SETS = True

#EVAL_CITIES_FIXED = ["Lome","Manila","Sydney","Lisbon","Bratislava","Kuwait","Anchorage","Buffalo","Albany","Sao Paulo"]

SEED = 42

# ---------------- Artifacts (figures/tables) ----------------
ART_DIR = Path("artifacts")
FIG_DIR = ART_DIR / "figures"
TAB_DIR = ART_DIR / "tables"
NPZ_DIR = ART_DIR / "npz"

ART_DIR.mkdir(exist_ok=True)
FIG_DIR.mkdir(parents=True, exist_ok=True)
TAB_DIR.mkdir(parents=True, exist_ok=True)
NPZ_DIR.mkdir(parents=True, exist_ok=True)

def save_fig(fig, name: str, dpi: int = 200):
    png = FIG_DIR / f"{name}.png"
    pdf = FIG_DIR / f"{name}.pdf"
    fig.tight_layout()
    fig.savefig(png, dpi=dpi, bbox_inches="tight")
    fig.savefig(pdf, bbox_inches="tight")
    plt.close(fig)
    print(f"[ART] saved figure: {png} and {pdf}")
    return str(png), str(pdf)

def save_table(df: pd.DataFrame, name: str, float_fmt: str = "%.6f"):
    csv_path = TAB_DIR / f"{name}.csv"
    tex_path = TAB_DIR / f"{name}.tex"
    df.to_csv(csv_path, index=False)
    df.to_latex(tex_path, index=False, float_format=lambda x: float_fmt % x)
    print(f"[ART] saved table: {csv_path} and {tex_path}")
    return str(csv_path), str(tex_path)

def zip_artifacts(zip_name: str = "artifacts.zip"):
    zip_path = ART_DIR / zip_name
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as z:
        for p in ART_DIR.rglob("*"):
            if p.is_file() and p.name != zip_name:
                z.write(p, p.relative_to(ART_DIR))
    print(f"[ART] zipped -> {zip_path}")
    return str(zip_path)

# flags (generate once)
_FIG_R24_DONE = False
_FIG_R26_DONE = False


# ---------------- Reproducibility ----------------

def set_seed(seed: int = SEED, deterministic: bool = True) -> None:
    os.environ["PYTHONHASHSEED"] = str(seed)

    random.seed(seed)
    np.random.seed(seed)

    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

    if deterministic:
        torch.backends.cudnn.deterministic = True
        torch.backends.cudnn.benchmark = False

        # hard determinism
        try:
            torch.use_deterministic_algorithms(True)
        except Exception:
            pass

        os.environ.setdefault("CUBLAS_WORKSPACE_CONFIG", ":4096:8")


# ---------------- Data utilities ----------------

REQ_COLS = ["Region", "Country", "State", "City", "Month", "Day", "Year", "AvgTemperature"]

def norm_city_name(s: str) -> str:
    s = str(s).strip()
    s = unicodedata.normalize("NFKD", s).encode("ascii", "ignore").decode("ascii")
    s = s.lower()
    s = re.sub(r"\s+", " ", s)
    s = re.sub(r"[^a-z\s\-]", "", s)
    return s.strip()

def _process_raw_dataframe(df: pd.DataFrame) -> pd.DataFrame:
    for c in ["Region", "Country", "State", "City"]:
        df[c] = df[c].astype(str)

    df["Date"] = pd.to_datetime(df[["Year", "Month", "Day"]], errors="coerce")
    df = df.dropna(subset=["Date"]).copy()

    # sentinel + Fahrenheit -> Celsius
    df.loc[df["AvgTemperature"] <= -90, "AvgTemperature"] = np.nan
    df["AvgTemperature"] = (df["AvgTemperature"] - 32.0) * (5.0 / 9.0)
    return df


def read_csv(csv_path: str) -> pd.DataFrame:
    df = pd.read_csv(csv_path, low_memory=False, usecols=REQ_COLS)
    return _process_raw_dataframe(df)


def load_kaggle_dataset(dataset_ref: str, file_path: str) -> pd.DataFrame:
    df = kagglehub.load_dataset(
        KaggleDatasetAdapter.PANDAS,
        dataset_ref,
        file_path,
        pandas_kwargs={"usecols": REQ_COLS, "low_memory": False}
    )
    return _process_raw_dataframe(df)


def probe_span(df: pd.DataFrame) -> tuple[int, int]:
    years = df["Date"].dt.year.to_numpy()
    return int(np.nanmin(years)), int(np.nanmax(years))


def aggregate_monthly(df: pd.DataFrame, year_min: int, year_max: int) -> pd.DataFrame:
    df = df[(df["Date"].dt.year >= year_min) & (df["Date"].dt.year <= year_max)].copy()
    df["Year"] = df["Date"].dt.year
    df["Month"] = df["Date"].dt.month
    monthly = df.groupby(["City", "Year", "Month"], as_index=False)[["AvgTemperature"]].mean()
    return monthly


def exclude_incomplete_years(monthly: pd.DataFrame, min_months: int) -> pd.DataFrame:
    counts = (
        monthly.dropna(subset=["AvgTemperature"])
        .groupby(["City", "Year"])["Month"].nunique()
        .reset_index(name="n_months")
    )
    keep = counts[counts["n_months"] >= min_months][["City", "Year"]]
    return monthly.merge(keep, on=["City", "Year"], how="inner")


def reindex_month_grid(monthly: pd.DataFrame, y0: int, y1: int) -> pd.DataFrame:
    """
    Much lower-RAM version:
    - City stored as categorical + integer CityCode in the big grid
    - merge happens on CityCode (int), not on City (object strings)
    """
    monthly = monthly.copy()

    # compress City column
    monthly["City"] = monthly["City"].astype("category")
    city_cat = monthly["City"].cat.categories

    monthly["CityCode"] = monthly["City"].cat.codes.astype(np.int32)

    # big full grid uses int codes instead of strings
    city_codes = np.arange(len(city_cat), dtype=np.int32)
    idx = pd.MultiIndex.from_product(
        [city_codes, range(y0, y1 + 1), range(1, 13)],
        names=["CityCode", "Year", "Month"],
    )
    full = pd.DataFrame(index=idx).reset_index()

    # merge on ints
    merged = full.merge(
        monthly.drop(columns=["City"]),
        on=["CityCode", "Year", "Month"],
        how="left",
        copy=False,
    )

    # restore City as categorical
    merged["City"] = pd.Categorical.from_codes(
        merged["CityCode"].astype(np.int32),
        categories=city_cat,
    )
    merged = merged.drop(columns=["CityCode"])

    return merged

def split_years(year_min: int, year_max: int) -> tuple[int, int]:
    if year_max - year_min + 1 < 25:
        years = list(range(year_min, year_max + 1))
        n = len(years)
        i1 = int(0.6 * n)
        i2 = int(0.8 * n)
        return years[i1 - 1], years[i2 - 1]

    # Fixed temporal split to avoid information leakage between training, validation and test periods
    train_end = min(1999, year_max - 21)
    val_end   = min(2000, year_max - 10)
    return train_end, val_end


def build_anomalies_fixed_climatology(monthly: pd.DataFrame, train_end: int) -> pd.DataFrame:
    out_parts = []
    for city, g in monthly.groupby("City", sort=False):
        g = g.sort_values(["Year", "Month"]).reset_index(drop=True).copy()

        mask_tr = g["Year"] <= train_end
        tr = g.loc[mask_tr, ["Month", "AvgTemperature"]].copy()

        clim = tr.groupby("Month")["AvgTemperature"].mean().reindex(range(1, 13))
        clim = clim.ffill().bfill()

        if clim.isna().any():
            gmean = float(tr["AvgTemperature"].mean()) if np.isfinite(tr["AvgTemperature"]).any() else 0.0
            clim = clim.fillna(gmean)

        g["Clim"] = g["Month"].map(clim.to_dict())
        g["Anomaly_raw"] = g["AvgTemperature"] - g["Clim"]
        g["is_observed_target"] = g["AvgTemperature"].notna()
        out_parts.append(g)

    return pd.concat(out_parts, ignore_index=True)


def build_city_region_map(df_raw: pd.DataFrame) -> dict[str, str]:
    # most common Region per City (robust)
    tmp = df_raw[["City", "Region"]].dropna().copy()
    tmp["City"] = tmp["City"].astype(str)
    tmp["Region"] = tmp["Region"].astype(str)

    reg = (
        tmp.groupby(["City", "Region"])
        .size()
        .reset_index(name="n")
        .sort_values(["City", "n"], ascending=[True, False])
    )
    # take first Region (mode) per City
    city_region = reg.drop_duplicates("City")[["City", "Region"]]
    return dict(zip(city_region["City"], city_region["Region"]))


def count_test_windows_for_city(
    g_city: pd.DataFrame,
    window: int,
    horizon: int,
    val_end: int,
    max_pchip_gap: int,
) -> int:
    g = g_city.sort_values(["Year", "Month"]).copy()

    a_raw = g["Anomaly_raw"].to_numpy(dtype=np.float32)
    yy = g["Year"].to_numpy(dtype=np.int32)
    is_obs_tgt = g["is_observed_target"].to_numpy(dtype=bool)

    T = len(a_raw)
    max_start = T - window - horizon
    if max_start <= 0:
        return 0

    cnt = 0
    for i in range(max_start):
        t = i + window
        t_end = t + horizon - 1

        # test condition: first target year > val_end
        if int(yy[t]) <= val_end:
            continue

        # targets must be observed
        yvec = a_raw[t:t + horizon]
        obsvec = is_obs_tgt[t:t + horizon]
        if (not np.all(np.isfinite(yvec))) or (not np.all(obsvec)):
            continue

        # causal window must be imputable with short-gap PCHIP
        w_raw = a_raw[i:i + window].astype(np.float32)
        w = pchip_impute_short_gaps_window(w_raw, max_gap=max_pchip_gap)
        if not np.all(np.isfinite(w)):
            continue

        cnt += 1

    return cnt

def city_year_counts(monthly_city: pd.DataFrame, train_end: int) -> tuple[int, int]:
    obs = monthly_city.dropna(subset=["AvgTemperature"])
    years = obs.groupby("Year")["Month"].nunique()
    total_years = int((years >= MIN_MONTHS_PER_YEAR).sum())
    train_years = int(((years.index <= train_end) & (years >= MIN_MONTHS_PER_YEAR)).sum())
    return total_years, train_years

def build_eval_sets_disjoint(
    df_raw: pd.DataFrame,
    monthly: pd.DataFrame,
    window: int,
    horizon: int,
    train_end: int,
    val_end: int,
    max_pchip_gap: int,
    n_eval_sets: int,
    n_eval: int,
    seed_base: int,
    min_test_windows: int = 60,
    enforce_disjoint: bool = True,
) -> list[list[str]]:
    used_norm: set[str] = set()
    eval_sets: list[list[str]] = []

    for i in range(n_eval_sets):
        eval_seed = seed_base + i
        exclude = used_norm if enforce_disjoint else set()

        cities = select_eval_cities_stratified(
            df_raw=df_raw,
            monthly=monthly,
            window=window,
            horizon=horizon,
            train_end=train_end,
            val_end=val_end,
            max_pchip_gap=max_pchip_gap,
            n_eval=n_eval,
            seed=eval_seed,
            min_test_windows=min_test_windows,
            exclude_cities_norm=exclude,
        )

        eval_sets.append(cities)
        if enforce_disjoint:
            used_norm.update(norm_city_name(c) for c in cities)

    return eval_sets

def select_eval_cities_stratified(
    df_raw: pd.DataFrame,
    monthly: pd.DataFrame,
    window: int,
    horizon: int,
    train_end: int,
    val_end: int,
    max_pchip_gap: int,
    n_eval: int,
    seed: int,
    min_test_windows: int = 60,
    exclude_cities_norm: set[str] | None = None,
) -> list[str]:
    """
    Select n_eval cities stratified by Region -> cities with sufficient TEST windows.
    Deterministic (seed) only for tie-break/top pick.
    """
    if exclude_cities_norm is None:
            exclude_cities_norm = set()

    city_region = build_city_region_map(df_raw)

    # count test windows per city
    counts = {}
    for city, g in monthly.groupby("City", sort=False):
        counts[city] = count_test_windows_for_city(
            g, window=window, horizon=horizon, val_end=val_end, max_pchip_gap=max_pchip_gap
        )

    # candidate pool
    candidates = [c for c, k in counts.items() if (k >= min_test_windows) and (c in city_region) and (norm_city_name(c) not in exclude_cities_norm)]

    if len(candidates) < n_eval:
        # fallback: relax threshold
        candidates = [c for c, k in counts.items() if (k > 0) and (c in city_region) and (norm_city_name(c) not in exclude_cities_norm)]

    filtered = []
    for c in candidates:
        g = monthly[monthly["City"] == c]
        tot_y, tr_y = city_year_counts(g, train_end=train_end)
        if tot_y >= MIN_TOTAL_YEARS_FOR_CITY and tr_y >= MIN_TRAIN_YEARS_FOR_CLIM:
            filtered.append(c)
    candidates = filtered

    # group by region
    region2cities = {}
    for c in candidates:
        r = city_region.get(c, "Unknown")
        region2cities.setdefault(r, []).append(c)

    # sort cities in each region by test window count desc
    for r in region2cities:
        region2cities[r].sort(key=lambda c: counts[c], reverse=True)

    regions = sorted(region2cities.keys())

    # quota: 1 per region, rest proportional (based on candidate counts)
    base = {r: 1 for r in regions}
    remaining = n_eval - len(regions)
    if remaining < 0:
        # too many regions for n_eval: keep top regions by size
        regions = sorted(regions, key=lambda r: len(region2cities[r]), reverse=True)[:n_eval]
        base = {r: 1 for r in regions}
        remaining = 0

    # proportional add
    sizes = np.array([len(region2cities[r]) for r in regions], dtype=np.float64)
    if remaining > 0 and sizes.sum() > 0:
        frac = sizes / sizes.sum()
        extra = np.floor(frac * remaining).astype(int)
        # distribute leftover by largest remainder
        leftover = remaining - int(extra.sum())
        rema = frac * remaining - extra
        order = np.argsort(-rema)
        for j in range(leftover):
            extra[order[j]] += 1
        for r, e in zip(regions, extra):
            base[r] += int(e)

    rng = np.random.default_rng(seed)

    chosen = []
    # pick per region from top list (tie-break with RNG among top chunk)
    for r in regions:
        need = base[r]
        pool = region2cities[r]
        if len(pool) == 0:
            continue
        # take from top 20 for diversity
        top = pool[: min(20, len(pool))]
        # deterministic shuffle in top then take need
        idx = np.arange(len(top))
        rng.shuffle(idx)
        pick = [top[i] for i in idx[: min(need, len(top))]]
        chosen.extend(pick)

    chosen = list(dict.fromkeys(chosen))  # unique preserve order

    # fill remaining globally by highest count
    if len(chosen) < n_eval:
        remaining_pool = [c for c in candidates if c not in chosen]
        remaining_pool.sort(key=lambda c: counts[c], reverse=True)
        chosen.extend(remaining_pool[: (n_eval - len(chosen))])

    return chosen[:n_eval]

def diagnose_eval_city_pool(
    df_raw: pd.DataFrame,
    monthly: pd.DataFrame,
    window: int,
    horizon: int,
    val_end: int,
    max_pchip_gap: int,
    min_test_windows: int = 60,
):
    city_region = build_city_region_map(df_raw)

    counts = {}
    for city, g in monthly.groupby("City", sort=False):
        counts[city] = count_test_windows_for_city(
            g, window=window, horizon=horizon, val_end=val_end, max_pchip_gap=max_pchip_gap
        )

    candidates = [c for c, k in counts.items() if k >= min_test_windows and c in city_region]
    print(f"[DIAG] Candidate cities with >= {min_test_windows} TEST windows: {len(candidates)}")

    # per region
    reg2n = {}
    for c in candidates:
        r = city_region.get(c, "Unknown")
        reg2n[r] = reg2n.get(r, 0) + 1

    for r in sorted(reg2n.keys()):
        print(f"  - {r}: {reg2n[r]}")

def plot_dataset_examples_once(monthly_with_anom: pd.DataFrame, city_list: list[str],
                               train_end: int, val_end: int):
    global _FIG_R26_DONE
    if _FIG_R26_DONE:
        return
    _FIG_R26_DONE = True

    fig, ax = plt.subplots(figsize=(12, 4))

    for city in city_list:
        d = monthly_with_anom[monthly_with_anom["City"] == city].copy()
        if len(d) == 0:
            continue
        d["date"] = pd.to_datetime(dict(year=d["Year"], month=d["Month"], day=1))
        d = d.sort_values("date")
        ax.plot(d["date"], d["Anomaly_raw"], label=city, linewidth=1.0)

    ax.axvline(pd.Timestamp(train_end, 12, 31), linestyle="--", linewidth=1.0)
    ax.axvline(pd.Timestamp(val_end, 12, 31), linestyle="--", linewidth=1.0)
    ax.set_title("Monthly temperature anomalies - dataset examples")
    ax.set_ylabel("Anomaly (C)")
    ax.legend(ncol=2, fontsize=8)

    save_fig(fig, "fig_r26_dataset_examples")


# --------- Causal, window-only PCHIP (no future leakage) ---------

def pchip_impute_short_gaps_window(values: np.ndarray, max_gap: int) -> np.ndarray:
    y = values.astype(np.float64).copy()
    n = len(y)
    isnan = ~np.isfinite(y)
    if not isnan.any():
        return y.astype(np.float32)

    obs = np.isfinite(y)
    if obs.sum() < 2:
        return y.astype(np.float32)

    x = np.arange(n, dtype=np.float64)
    f = PchipInterpolator(x[obs], y[obs], extrapolate=False)

    i = 0
    while i < n:
        if isnan[i]:
            j = i
            while j < n and isnan[j]:
                j += 1
            gap_len = j - i
            internal = (i > 0) and (j < n)
            if internal and gap_len <= max_gap:
                y[i:j] = f(x[i:j])
            i = j
        else:
            i += 1

    return y.astype(np.float32)


# --------- Geographic split (train/val/test cities disjoint) ---------

def split_cities_geographic(all_cities: list[str], eval_set_norm: set[str], seed: int) -> tuple[set[str], set[str], set[str]]:
    all_norm = sorted({norm_city_name(c) for c in all_cities})
    test_norm = set(all_norm) & set(eval_set_norm)
    non_test_norm = [cn for cn in all_norm if cn not in test_norm]

    rng = np.random.default_rng(seed)
    n_val = int(round(len(non_test_norm) * VAL_FRACTION))
    n_val = max(n_val, MIN_VAL_CITIES)
    n_val = min(n_val, MAX_VAL_CITIES, max(1, len(non_test_norm) // 2))
    n_val = min(n_val, len(non_test_norm))  # safety

    val_norm = set(rng.choice(non_test_norm, size=n_val, replace=False).tolist()) if n_val > 0 else set()
    train_norm = set([cn for cn in non_test_norm if cn not in val_norm])

    return train_norm, val_norm, test_norm


def make_windows_global_joint(
    df: pd.DataFrame,
    window: int,
    horizon: int,
    train_end: int,
    val_end: int,
    train_cities_norm: set[str],
    val_cities_norm: set[str],
    test_cities_norm: set[str],
    max_pchip_gap: int,
) -> tuple[
    dict[str, np.ndarray], dict[str, np.ndarray], dict[str, np.ndarray], dict[str, np.ndarray], dict[str, int]
]:
    """
    JOINT horizon windowing: targets are vectors y[t : t+horizon]
    Strict rules:
    - Inputs built from past window only; causal PCHIP inside window only
    - Skip if any target in horizon is missing / not observed
    - Time split uses horizon end:
        TRAIN: last target year <= train_end
        VAL:   first target year > train_end and last target year <= val_end
        TEST:  first target year > val_end (test cities only)
    """
    cities = sorted(df["City"].unique())
    city2id = {c: i for i, c in enumerate(cities)}

    Xs = {"train": [], "val": [], "test": []}
    Ys = {"train": [], "val": [], "test": []}
    Cs = {"train": [], "val": [], "test": []}
    Y1years = {"train": [], "val": [], "test": []}  # year of first horizon target (for decade grouping)

    for city, g in df.groupby("City", sort=False):
        g = g.sort_values(["Year", "Month"]).copy()
        cid = city2id[city]
        city_norm = norm_city_name(city)

        a_raw = g["Anomaly_raw"].to_numpy(dtype=np.float32)
        m = g["Month"].to_numpy(dtype=np.int32)
        yy = g["Year"].to_numpy(dtype=np.int32)
        is_obs_tgt = g["is_observed_target"].to_numpy(dtype=bool)

        if city_norm in test_cities_norm:
            which_city = "test"
        elif city_norm in val_cities_norm:
            which_city = "val"
        elif city_norm in train_cities_norm:
            which_city = "train"
        else:
            continue

        T = len(a_raw)
        max_start = T - window - horizon + 1
        if max_start <= 0:
            continue

        for i in range(max_start):
            t = i + window
            t_end = t + horizon - 1

            # targets must be observed (no imputation for scoring)
            yvec = a_raw[t:t + horizon]
            obsvec = is_obs_tgt[t:t + horizon]
            if (not np.all(np.isfinite(yvec))) or (not np.all(obsvec)):
                continue

            y_year_first = int(yy[t])
            y_year_last = int(yy[t_end])

            # enforce split by city + time (using horizon end)
            if which_city == "train":
                if y_year_last > train_end:
                    continue
                split_key = "train"
            elif which_city == "val":
                if not (y_year_first > train_end and y_year_last <= val_end):
                    continue
                split_key = "val"
            else:  # test
                if y_year_first <= val_end:
                    continue
                split_key = "test"

            # build causal input window
            w_raw = a_raw[i:i + window].astype(np.float32)
            w = pchip_impute_short_gaps_window(w_raw, max_gap=max_pchip_gap)
            if not np.all(np.isfinite(w)):
                continue

            sin_m = np.sin(2 * np.pi * ((m[i:i + window] - 1) / 12.0))
            cos_m = np.cos(2 * np.pi * ((m[i:i + window] - 1) / 12.0))
            delta = np.concatenate([[0.0], np.diff(w)])
            feats = np.stack([w, sin_m, cos_m, delta], axis=1).astype(np.float32)  # [W,4]

            Xs[split_key].append(feats)
            Ys[split_key].append(yvec.astype(np.float32))
            Cs[split_key].append(cid)
            Y1years[split_key].append(y_year_first)

    def stack_X(lst):
        return np.asarray(lst, np.float32) if len(lst) > 0 else np.empty((0, window, 4), np.float32)

    def stack_Y(lst):
        return np.asarray(lst, np.float32) if len(lst) > 0 else np.empty((0, horizon), np.float32)

    def stack_c(lst):
        return np.asarray(lst, np.int64) if len(lst) > 0 else np.empty((0,), np.int64)

    def stack_yr(lst):
        return np.asarray(lst, np.int32) if len(lst) > 0 else np.empty((0,), np.int32)

    return (
        {k: stack_X(v) for k, v in Xs.items()},
        {k: stack_Y(v) for k, v in Ys.items()},
        {k: stack_c(v) for k, v in Cs.items()},
        {k: stack_yr(v) for k, v in Y1years.items()},
        city2id,
    )


# ---------------- Model: Joint multi-horizon conditional SPN ----------------
class JointConditionalSPNHead(nn.Module):
    def __init__(self, in_dim: int, k_root: int, horizon: int, m_mag: int,
                 alpha_floor: float, beta_floor: float,
                 shared_magnitude: bool = False):
        super().__init__()
        self.k_root = k_root
        self.horizon = horizon
        self.m_mag = m_mag
        self.shared_magnitude = shared_magnitude

        self.fc1 = nn.Linear(in_dim, 128)
        self.fc2 = nn.Linear(128, 64)

        self.fc_pi_root = nn.Linear(64, k_root)
        self.fc_s = nn.Linear(64, k_root * horizon)

        size_khm = k_root * horizon * m_mag

        if self.shared_magnitude:
            self.fc_pi_mag = nn.Linear(64, size_khm)
            self.fc_alpha_mag = nn.Linear(64, size_khm)
            self.fc_beta_mag  = nn.Linear(64, size_khm)
        else:
            self.fc_pi_pos = nn.Linear(64, size_khm)
            self.fc_pi_neg = nn.Linear(64, size_khm)
            self.fc_alpha_pos = nn.Linear(64, size_khm)
            self.fc_beta_pos  = nn.Linear(64, size_khm)
            self.fc_alpha_neg = nn.Linear(64, size_khm)
            self.fc_beta_neg  = nn.Linear(64, size_khm)

        self.alpha_floor = alpha_floor
        self.beta_floor = beta_floor

    def forward(self, h: torch.Tensor):
        z = F.relu(self.fc1(h))
        z = F.relu(self.fc2(z))

        pi_root = F.softmax(self.fc_pi_root(z), dim=-1)  # [B,K]
        s = torch.sigmoid(self.fc_s(z)).view(-1, self.k_root, self.horizon)  # [B,K,H]

        def smx(v):
            v = v.view(-1, self.k_root, self.horizon, self.m_mag)
            return F.softmax(v, dim=-1)

        def sp(v):
            v = v.view(-1, self.k_root, self.horizon, self.m_mag)
            return F.softplus(v)

        if self.shared_magnitude:
            pi_mag = smx(self.fc_pi_mag(z))
            a_mag  = sp(self.fc_alpha_mag(z)) + self.alpha_floor
            b_mag  = sp(self.fc_beta_mag(z))  + self.beta_floor

            # tie pos/neg to same magnitude params
            pi_pos, pi_neg = pi_mag, pi_mag
            alpha_pos, alpha_neg = a_mag, a_mag
            beta_pos,  beta_neg  = b_mag, b_mag
        else:
            pi_pos = smx(self.fc_pi_pos(z))
            pi_neg = smx(self.fc_pi_neg(z))

            alpha_pos = sp(self.fc_alpha_pos(z)) + self.alpha_floor
            beta_pos  = sp(self.fc_beta_pos(z))  + self.beta_floor
            alpha_neg = sp(self.fc_alpha_neg(z)) + self.alpha_floor
            beta_neg  = sp(self.fc_beta_neg(z))  + self.beta_floor

        return pi_root, s, pi_pos, alpha_pos, beta_pos, pi_neg, alpha_neg, beta_neg


# Encoder that maps the input window to a compact context embedding used by the SPN gating network
class Encoder(nn.Module):
    def __init__(self, in_ch: int, hidden: int, dropout: float):
        super().__init__()
        self.conv = nn.Conv1d(in_channels=in_ch, out_channels=16, kernel_size=3, padding=1)
        self.skip = nn.Linear(in_ch, 16)
        self.gru = nn.GRU(input_size=16, hidden_size=hidden, num_layers=1,
                          batch_first=True, bidirectional=False)
        self.drop = nn.Dropout(dropout)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        skip_in = self.skip(x)  # [B,W,16]
        z = F.relu(self.conv(x.permute(0, 2, 1))).permute(0, 2, 1)  # [B,W,16]
        z = z + skip_in
        out, _ = self.gru(z)
        return self.drop(out[:, -1, :])  # [B,2H]


# End-to-end model: CNN+BiGRU encoder followed by a joint conditional SPN-Gamma decoder
class GlobalJointConditionalSPN(nn.Module):
    def __init__(self, in_ch: int, hidden: int, k_root: int, horizon: int, m_mag: int,
                 dropout: float, alpha_floor: float, beta_floor: float, shared_magnitude: bool = False):
        super().__init__()
        self.k_root = k_root
        self.horizon = horizon
        self.m_mag = m_mag

        self.enc = Encoder(in_ch=in_ch, hidden=hidden, dropout=dropout)
        self.head = JointConditionalSPNHead(
            in_dim=hidden, k_root=k_root, horizon=horizon, m_mag=m_mag,
            alpha_floor=alpha_floor, beta_floor=beta_floor, shared_magnitude = shared_magnitude
        )

    # Log-density of Gamma(|y|) in (alpha, beta) parameterization, used for magnitude likelihood.
    @staticmethod
    def gamma_logpdf_scale(u: torch.Tensor, alpha: torch.Tensor, beta: torch.Tensor) -> torch.Tensor:
        return -torch.lgamma(alpha) - alpha * torch.log(beta) + (alpha - 1.0) * torch.log(u) - (u / beta)

    def forward_params(self, x: torch.Tensor):
        h = self.enc(x)
        return self.head(h)

    def log_prob(self, x: torch.Tensor, y: torch.Tensor) -> torch.Tensor:
        """
        y: [B,H]
        Exact SPN evaluation:
          log p(y|x) = logsumexp_k [ log pi_k + sum_h log p_h(y_h|k,x) ]
        """
        pi_root, s, pi_pos, a_pos, b_pos, pi_neg, a_neg, b_neg = self.forward_params(x)

        eps = 1e-8
        B, H = y.shape
        K = self.k_root
        M = self.m_mag

        y_b1h1 = y.view(B, 1, H, 1)                      # [B,1,H,1]
        u = torch.abs(y_b1h1) + eps                      # [B,1,H,1]
        sign_pos = (y >= 0).float().view(B, 1, H)        # [B,1,H]

        # broadcast to [B,K,H,M]
        u_bkhm = u.expand(B, K, H, M)

        log_ga_pos = self.gamma_logpdf_scale(u_bkhm, a_pos, b_pos)  # [B,K,H,M]
        log_ga_neg = self.gamma_logpdf_scale(u_bkhm, a_neg, b_neg)  # [B,K,H,M]

        log_pu_pos = torch.logsumexp(torch.log(pi_pos + 1e-12) + log_ga_pos, dim=3)  # [B,K,H]
        log_pu_neg = torch.logsumexp(torch.log(pi_neg + 1e-12) + log_ga_neg, dim=3)  # [B,K,H]

        log_s = torch.log(s + 1e-12)                # [B,K,H]
        log_1s = torch.log(1.0 - s + 1e-12)         # [B,K,H]

        # choose sign branch per y_h using indicator
        sign_pos_bkh = sign_pos.expand(B, K, H)
        log_ph = sign_pos_bkh * (log_s + log_pu_pos) + (1.0 - sign_pos_bkh) * (log_1s + log_pu_neg)  # [B,K,H]

        log_pk = log_ph.sum(dim=2)                  # Product over horizons -> sum logs, [B,K]
        log_mix = torch.log(pi_root + 1e-12) + log_pk
        return torch.logsumexp(log_mix, dim=1)       # [B]

    @torch.no_grad()
    def posterior_k(self, x: torch.Tensor, y: torch.Tensor) -> torch.Tensor:
        """
        Returns responsibilities r_{b,k} = p(k | y, x), shape [B,K].
        This is exact inference in the circuit (upward + normalization).
        """
        pi_root, s, pi_pos, a_pos, b_pos, pi_neg, a_neg, b_neg = self.forward_params(x)

        eps = 1e-8
        B, H = y.shape
        K = self.k_root
        M = self.m_mag

        y_b1h1 = y.view(B, 1, H, 1)
        u = torch.abs(y_b1h1) + eps
        sign_pos = (y >= 0).float().view(B, 1, H)

        u_bkhm = u.expand(B, K, H, M)

        log_ga_pos = self.gamma_logpdf_scale(u_bkhm, a_pos, b_pos)
        log_ga_neg = self.gamma_logpdf_scale(u_bkhm, a_neg, b_neg)

        log_pu_pos = torch.logsumexp(torch.log(pi_pos + 1e-12) + log_ga_pos, dim=3)  # [B,K,H]
        log_pu_neg = torch.logsumexp(torch.log(pi_neg + 1e-12) + log_ga_neg, dim=3)  # [B,K,H]

        log_s = torch.log(s + 1e-12)
        log_1s = torch.log(1.0 - s + 1e-12)

        sign_pos_bkh = sign_pos.expand(B, K, H)
        log_ph = sign_pos_bkh * (log_s + log_pu_pos) + (1.0 - sign_pos_bkh) * (log_1s + log_pu_neg)  # [B,K,H]

        log_pk = log_ph.sum(dim=2)  # [B,K]
        log_joint = torch.log(pi_root + 1e-12) + log_pk  # proportional to p(k,y|x)
        return torch.softmax(log_joint, dim=1)


    def log_prob_masked(self, x: torch.Tensor, y: torch.Tensor, mask: torch.Tensor) -> torch.Tensor:
        """
        Exact marginal log-likelihood with missing horizons marginalized out.
        y:    [B,H]
        mask: [B,H] with 1 for observed horizons, 0 for marginalized horizons

        Because the circuit is decomposable and has a Product over horizons,
        marginalizing a horizon corresponds to removing its factor (multiply by 1),
        i.e., skip its log-term.
        """
        pi_root, s, pi_pos, a_pos, b_pos, pi_neg, a_neg, b_neg = self.forward_params(x)

        eps = 1e-8
        B, H = y.shape
        K = self.k_root
        M = self.m_mag

        y_b1h1 = y.view(B, 1, H, 1)
        u = torch.abs(y_b1h1) + eps
        sign_pos = (y >= 0).float().view(B, 1, H)

        u_bkhm = u.expand(B, K, H, M)

        log_ga_pos = self.gamma_logpdf_scale(u_bkhm, a_pos, b_pos)
        log_ga_neg = self.gamma_logpdf_scale(u_bkhm, a_neg, b_neg)

        log_pu_pos = torch.logsumexp(torch.log(pi_pos + 1e-12) + log_ga_pos, dim=3)  # [B,K,H]
        log_pu_neg = torch.logsumexp(torch.log(pi_neg + 1e-12) + log_ga_neg, dim=3)  # [B,K,H]

        log_s = torch.log(s + 1e-12)
        log_1s = torch.log(1.0 - s + 1e-12)

        sign_pos_bkh = sign_pos.expand(B, K, H)
        log_ph = sign_pos_bkh * (log_s + log_pu_pos) + (1.0 - sign_pos_bkh) * (log_1s + log_pu_neg)  # [B,K,H]

        # apply mask: marginalized horizons contribute 0 to sum of logs
        mask_bkh = mask.view(B, 1, H).expand(B, K, H).float()
        log_pk = (log_ph * mask_bkh).sum(dim=2)  # [B,K]

        log_mix = torch.log(pi_root + 1e-12) + log_pk
        return torch.logsumexp(log_mix, dim=1)  # [B]

    # Training objective: maximize average log-likelihood with mild regularization and optional gating-entropy term
    def train_objective(self, x: torch.Tensor, y: torch.Tensor, l2_log_param: float, entropy_weight: float):
        logp = self.log_prob(x, y).mean()

        pi_root, _, pi_pos, a_pos, b_pos, pi_neg, a_neg, b_neg = self.forward_params(x)

        reg = l2_log_param * (
            torch.log(a_pos).pow(2).mean() + torch.log(b_pos).pow(2).mean() +
            torch.log(a_neg).pow(2).mean() + torch.log(b_neg).pow(2).mean()
        )

        pr = pi_root.clamp_min(1e-12)
        entropy_root = -(pr * torch.log(pr)).sum(dim=1).mean()
        reg -= entropy_weight * entropy_root

        return -(logp) + reg

    # Predictive mean E[y|x] computed in closed form by marginalizing the SPN mixture components
    def predictive_mean(self, x: torch.Tensor) -> torch.Tensor:
        """
        Returns mean per horizon: [B,H]
        """
        pi_root, s, pi_pos, a_pos, b_pos, pi_neg, a_neg, b_neg = self.forward_params(x)

        eu_pos = (pi_pos * (a_pos * b_pos)).sum(dim=3)  # [B,K,H]
        eu_neg = (pi_neg * (a_neg * b_neg)).sum(dim=3)  # [B,K,H]

        mean_kh = s * eu_pos - (1.0 - s) * eu_neg        # [B,K,H]
        return (pi_root.unsqueeze(-1) * mean_kh).sum(dim=1)  # [B,H]

    # Draw joint multi-horizon samples; shared latent component induces cross-horizon dependence
    def sample(self, x: torch.Tensor, n_samples: int, dispersion_scale: float | None = None) -> torch.Tensor:
        """
        Joint sampling: [S,B,H]
        Mixture-of-products induces dependencies across horizons via shared k.
        """
        pi_root, s, pi_pos, a_pos, b_pos, pi_neg, a_neg, b_neg = self.forward_params(x)
        B, K = pi_root.shape
        H = self.horizon
        M = self.m_mag
        S = n_samples

        cat_k = torch.distributions.Categorical(probs=pi_root)
        k_idx = cat_k.sample((S,))  # [S,B]

        # expand tensors for gather
        idx_k = k_idx.unsqueeze(-1).unsqueeze(-1)  # [S,B,1,1]

        def gather_k_3(t_bkh: torch.Tensor) -> torch.Tensor:
            t = t_bkh.unsqueeze(0).expand(S, B, K, H)
            idx = k_idx.unsqueeze(-1).unsqueeze(-1).expand(S, B, 1, H)
            return torch.gather(t, 2, idx).squeeze(2)  # [S,B,H]

        def gather_k_4(t_bkhm: torch.Tensor) -> torch.Tensor:
            t = t_bkhm.unsqueeze(0).expand(S, B, K, H, M)
            idx = k_idx.unsqueeze(-1).unsqueeze(-1).unsqueeze(-1).expand(S, B, 1, H, M)
            return torch.gather(t, 2, idx).squeeze(2)  # [S,B,H,M]

        s_k = gather_k_3(s)             # [S,B,H]

        # sample sign per horizon
        sign_draw = torch.distributions.Bernoulli(probs=s_k).sample()  # [S,B,H] in {0,1}
        sign_factor = 2.0 * sign_draw - 1.0

        pi_pos_k = gather_k_4(pi_pos)
        pi_neg_k = gather_k_4(pi_neg)
        a_pos_k  = gather_k_4(a_pos)
        b_pos_k  = gather_k_4(b_pos)
        a_neg_k  = gather_k_4(a_neg)
        b_neg_k  = gather_k_4(b_neg)

        sign_mask = sign_draw.unsqueeze(-1)  # [S,B,H,1]
        pi_mix = torch.where(sign_mask > 0.5, pi_pos_k, pi_neg_k)  # [S,B,H,M]
        a_mix  = torch.where(sign_mask > 0.5, a_pos_k,  a_neg_k)
        b_mix  = torch.where(sign_mask > 0.5, b_pos_k,  b_neg_k)

        cat_m = torch.distributions.Categorical(probs=pi_mix)
        m_idx = cat_m.sample()  # [S,B,H]

        idx_m = m_idx.unsqueeze(-1)  # [S,B,H,1]
        a_g = torch.gather(a_mix, 3, idx_m).squeeze(-1)  # [S,B,H]
        b_g = torch.gather(b_mix, 3, idx_m).squeeze(-1)  # [S,B,H]

        # --- post-hoc dispersion calibration (VAL-fitted) ---
        # Gamma: mean=alpha*beta, var=alpha*beta^2
        # Keep mean fixed, scale variance by v: alpha' = alpha / v, beta' = beta * v
        if dispersion_scale is not None:
            v = torch.as_tensor(dispersion_scale, device=a_g.device, dtype=a_g.dtype)
            a_g = (a_g / v).clamp_min(self.head.alpha_floor)
            b_g = (b_g * v).clamp_min(self.head.beta_floor)

        gam = torch.distributions.Gamma(concentration=a_g, rate=1.0 / (b_g + 1e-12)).sample()  # [S,B,H]
        return sign_factor * gam

    def sample_independent(self, x: torch.Tensor, n_samples: int, dispersion_scale: float | None = None) -> torch.Tensor:
      """
      Sampling with independent latent k per horizon.
      Keeps per-horizon marginals, removes cross-horizon dependence.
      Returns: [S,B,H]
      """
      pi_root, s, pi_pos, a_pos, b_pos, pi_neg, a_neg, b_neg = self.forward_params(x)

      B, K = pi_root.shape
      H = self.horizon
      M = self.m_mag
      S = n_samples

      cat_k = torch.distributions.Categorical(probs=pi_root)

      out = torch.empty((S, B, H), device=x.device, dtype=torch.float32)

      for h in range(H):
          # sample k independently for this horizon
          k_idx = cat_k.sample((S,))  # [S,B]

          # gather s for (B,K) at horizon h -> [S,B]
          s_bk = s[:, :, h]  # [B,K]
          s_exp = s_bk.unsqueeze(0).expand(S, B, K)
          idx = k_idx.unsqueeze(-1)  # [S,B,1]
          s_k = torch.gather(s_exp, 2, idx).squeeze(-1)  # [S,B]

          # sample sign
          sign_draw = torch.distributions.Bernoulli(probs=s_k).sample()  # [S,B]
          sign_factor = 2.0 * sign_draw - 1.0

          # gather mixture params for this horizon: [B,K,M] -> [S,B,M]
          def gather_bkm(t_bkhm: torch.Tensor) -> torch.Tensor:
              t = t_bkhm[:, :, h, :]  # [B,K,M]
              t = t.unsqueeze(0).expand(S, B, K, M)
              idx4 = k_idx.unsqueeze(-1).unsqueeze(-1).expand(S, B, 1, M)
              return torch.gather(t, 2, idx4).squeeze(2)  # [S,B,M]

          pi_pos_k = gather_bkm(pi_pos)
          pi_neg_k = gather_bkm(pi_neg)
          a_pos_k  = gather_bkm(a_pos)
          b_pos_k  = gather_bkm(b_pos)
          a_neg_k  = gather_bkm(a_neg)
          b_neg_k  = gather_bkm(b_neg)

          sign_mask = sign_draw.unsqueeze(-1)  # [S,B,1]
          pi_mix = torch.where(sign_mask > 0.5, pi_pos_k, pi_neg_k)  # [S,B,M]
          a_mix  = torch.where(sign_mask > 0.5, a_pos_k,  a_neg_k)
          b_mix  = torch.where(sign_mask > 0.5, b_pos_k,  b_neg_k)

          cat_m = torch.distributions.Categorical(probs=pi_mix)
          m_idx = cat_m.sample()  # [S,B]

          idx_m = m_idx.unsqueeze(-1)  # [S,B,1]
          a_g = torch.gather(a_mix, 2, idx_m).squeeze(-1)  # [S,B]
          b_g = torch.gather(b_mix, 2, idx_m).squeeze(-1)  # [S,B]

          if dispersion_scale is not None:
            v = torch.as_tensor(dispersion_scale, device=a_g.device, dtype=a_g.dtype)
            a_g = (a_g / v).clamp_min(self.head.alpha_floor)
            b_g = (b_g * v).clamp_min(self.head.beta_floor)

          gam = torch.distributions.Gamma(concentration=a_g, rate=1.0 / (b_g + 1e-12)).sample()  # [S,B]
          out[:, :, h] = sign_factor * gam

      return out

    def covariance_matrix(self, x: torch.Tensor) -> torch.Tensor:
        """
        Exact Cov[y|x] for mixture-of-products:
          Cov = E[Var(y|k,x)] + Var(E[y|k,x])
        Returns [B,H,H].
        """
        pi_root, s, pi_pos, a_pos, b_pos, pi_neg, a_neg, b_neg = self.forward_params(x)

        # Means per leaf
        m1_pos = a_pos * b_pos
        m1_neg = a_neg * b_neg

        # Second moments per leaf: E[u^2] = Var + mean^2, Var(Gamma)=alpha*beta^2
        m2_pos = a_pos * (b_pos ** 2) + (m1_pos ** 2)
        m2_neg = a_neg * (b_neg ** 2) + (m1_neg ** 2)

        # Mixture moments per (B,K,H)
        eu_pos  = (pi_pos * m1_pos).sum(dim=3)  # E[u]   pos
        eu_neg  = (pi_neg * m1_neg).sum(dim=3)  # E[u]   neg
        eu2_pos = (pi_pos * m2_pos).sum(dim=3)  # E[u^2] pos
        eu2_neg = (pi_neg * m2_neg).sum(dim=3)  # E[u^2] neg

        # E[y|k] and E[y^2|k] (since sign^2=1 => y^2=u^2)
        mu_kh  = s * eu_pos - (1.0 - s) * eu_neg          # [B,K,H]
        ey2_kh = s * eu2_pos + (1.0 - s) * eu2_neg        # [B,K,H]

        # Overall mean
        mu = (pi_root.unsqueeze(-1) * mu_kh).sum(dim=1)   # [B,H]

        # Var(E[y|k]) term via E[yy^T] from means
        Eyy = torch.einsum("bk,bkh,bkj->bhj", pi_root, mu_kh, mu_kh)  # [B,H,H]
        cov = Eyy - torch.einsum("bh,bj->bhj", mu, mu)

        # Add E[Var(y|k)] on diagonal: E[y^2|k] - (E[y|k])^2
        diag_add = (pi_root.unsqueeze(-1) * (ey2_kh - mu_kh.pow(2))).sum(dim=1)  # [B,H]
        idx = torch.arange(self.horizon, device=x.device)
        cov[:, idx, idx] += diag_add

        return cov

# ---------------- Figures ----------------
import matplotlib.patches as patches

def plot_framework_diagram_once():
    global _FIG_R24_DONE
    if _FIG_R24_DONE:
        return
    _FIG_R24_DONE = True

    fig, ax = plt.subplots(figsize=(12, 3))
    ax.axis("off")

    boxes = [
        (0.02, 0.35, 0.18, 0.30, "Input\n(lookback window)"),
        (0.25, 0.35, 0.18, 0.30, "CNN1D + skip\nfeature extractor"),
        (0.48, 0.35, 0.18, 0.30, "GRU\nsequence encoder"),
        (0.71, 0.15, 0.27, 0.70, "JOINT conditional SPN head\npi_k, s_{k,h}\nGamma mixtures per sign\nProduct over horizons"),
    ]

    for x, y, w, h, t in boxes:
        rect = patches.FancyBboxPatch((x, y), w, h, boxstyle="round,pad=0.02")
        ax.add_patch(rect)
        ax.text(x + w / 2, y + h / 2, t, ha="center", va="center", fontsize=9)

    def arrow(x1, y1, x2, y2):
        ax.annotate("", xy=(x2, y2), xytext=(x1, y1),
                    arrowprops=dict(arrowstyle="->", lw=1.5))

    arrow(0.20, 0.50, 0.25, 0.50)
    arrow(0.43, 0.50, 0.48, 0.50)
    arrow(0.66, 0.50, 0.71, 0.50)

    ax.text(0.845, 0.85, "Outputs:\n- predictive samples\n- quantiles/intervals\n- log-likelihood",
            ha="center", va="center", fontsize=9)

    save_fig(fig, "fig_r24_framework")


def plot_mag_gof(y_true: np.ndarray, samples: np.ndarray, fig_name: str = "fig_mag_gof"):
    # y_true: [N,H], samples: [S,N,H]
    mag_emp = np.abs(y_true).reshape(-1)
    mag_smp = np.abs(samples).reshape(-1)

    mag_emp = mag_emp[np.isfinite(mag_emp)]
    mag_smp = mag_smp[np.isfinite(mag_smp)]

    x_emp = np.sort(mag_emp)
    y_emp = np.linspace(0, 1, len(x_emp), endpoint=True)

    x_smp = np.sort(mag_smp)
    y_smp = np.linspace(0, 1, len(x_smp), endpoint=True)

    fig, ax = plt.subplots(figsize=(7, 4))
    ax.plot(x_emp, y_emp, label="Empirical |y|", linewidth=2.0)
    ax.plot(x_smp, y_smp, label="Model samples |y|", linewidth=2.0)
    ax.set_xlabel("|y| (°C)")
    ax.set_ylabel("CDF")
    ax.set_title("Magnitude goodness-of-fit for |y|")
    ax.grid(True, alpha=0.3)
    ax.legend()
    save_fig(fig, fig_name)

    qs = [0.5, 0.75, 0.9, 0.95, 0.99]
    rows = []
    for q in qs:
        qe = float(np.quantile(mag_emp, q))
        qsmp = float(np.quantile(mag_smp, q))
        rows.append({"q": q, "emp": qe, "sample": qsmp, "abs_diff": float(abs(qe - qsmp))})
    save_table(pd.DataFrame(rows), name="mag_gof_quantiles", float_fmt="%.6f")

# ---------------- Training ----------------

class WarmupCosine:
    def __init__(self, warm: int, total: int):
        self.warm = warm
        self.total = total

    def __call__(self, ep: int) -> float:
        if ep < self.warm:
            return float(ep + 1) / float(max(1, self.warm))
        prog = (ep - self.warm) / float(max(1, self.total - self.warm))
        return 0.5 * (1.0 + math.cos(math.pi * prog))


# Training loop with validation monitoring and early stopping for robust model selection
def train_model(
    model: GlobalJointConditionalSPN,
    train_loader: DataLoader,
    val_loader: DataLoader,
    device: str,
    epochs: int,
    lr: float,
    warmup: int,
    patience: int,
    l2_log_param: float,
    entropy_weight: float,
    grad_clip: float | None = 1.0,
) -> GlobalJointConditionalSPN:
    model = model.to(device)
    opt = torch.optim.Adam(model.parameters(), lr=lr)
    sch = torch.optim.lr_scheduler.LambdaLR(opt, lr_lambda=WarmupCosine(warmup, epochs))

    best = float("inf")
    best_state = None
    pat = patience

    for ep in range(epochs):
        model.train()
        train_sum = 0.0

        for xb, yb in train_loader:
            xb = xb.to(device)
            yb = yb.to(device)

            loss = model.train_objective(xb, yb, l2_log_param=l2_log_param, entropy_weight=entropy_weight)
            opt.zero_grad()
            loss.backward()
            if grad_clip is not None:
                torch.nn.utils.clip_grad_norm_(model.parameters(), grad_clip)
            opt.step()

            train_sum += loss.item() * xb.size(0)

        sch.step()

        model.eval()
        val_sum = 0.0
        n_val = 0
        with torch.no_grad():
            for xb, yb in val_loader:
                xb = xb.to(device)
                yb = yb.to(device)
                vloss = model.train_objective(xb, yb, l2_log_param=l2_log_param, entropy_weight=entropy_weight)
                val_sum += vloss.item() * xb.size(0)
                n_val += xb.size(0)

        train_obj = train_sum / max(1, len(train_loader.dataset))
        val_obj = val_sum / max(1, n_val)

        print(
            f"Epoch {ep+1:3d}/{epochs} | Train Obj: {train_obj:.4f} | Val Obj: {val_obj:.4f} | LR: {sch.get_last_lr()[0]:.6f}"
        )

        if val_obj < best - 1e-4:
            best = val_obj
            best_state = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
            pat = patience
        else:
            pat -= 1
            if pat <= 0:
                print("Early stopping.")
                break

    if best_state is not None:
        model.load_state_dict(best_state)

    return model

# ---------------- Transformer baseline ----------------
class TinyTransformerForecaster(nn.Module):
    def __init__(self, in_dim: int, H: int, d_model: int = 64, nhead: int = 4,
                 num_layers: int = 2, dim_ff: int = 128, dropout: float = 0.1):
        super().__init__()
        self.H = H
        self.inp = nn.Linear(in_dim, d_model)
        enc_layer = nn.TransformerEncoderLayer(
            d_model=d_model, nhead=nhead, dim_feedforward=dim_ff,
            dropout=dropout, batch_first=True
        )
        self.enc = nn.TransformerEncoder(enc_layer, num_layers=num_layers)
        self.head = nn.Linear(d_model, H)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        # x: [B,W,4]
        h = self.inp(x)
        h = self.enc(h)
        out = self.head(h[:, -1, :])
        return out  # [B,H]

def train_tiny_transformer(train_loader, val_loader, H: int, device: str,
                           max_epochs: int = 50, lr: float = 1e-3, patience: int = 8, seed: int = 0):
    torch.manual_seed(seed)
    model = TinyTransformerForecaster(in_dim=4, H=H).to(device)
    opt = torch.optim.Adam(model.parameters(), lr=lr)

    best = None
    best_state = None
    bad = 0

    def _rmse(pred, y):
        return float(torch.sqrt(torch.mean((pred - y) ** 2)).detach().cpu())

    for _ep in range(1, max_epochs + 1):
        model.train()
        for xb, yb in train_loader:
            xb = xb.to(device)
            yb = yb.to(device)
            pred = model(xb)
            loss = torch.mean((pred - yb) ** 2)
            opt.zero_grad()
            loss.backward()
            opt.step()

        model.eval()
        vals = []
        with torch.no_grad():
            for xb, yb in val_loader:
                xb = xb.to(device)
                yb = yb.to(device)
                pred = model(xb)
                vals.append(_rmse(pred, yb))
        v = float(np.mean(vals))

        if (best is None) or (v < best):
            best = v
            best_state = {k: vv.cpu().clone() for k, vv in model.state_dict().items()}
            bad = 0
        else:
            bad += 1
            if bad >= patience:
                break

    if best_state is not None:
        model.load_state_dict(best_state)
    return model


# ---------------- Metrics ----------------

def rmse_all(y_true: np.ndarray, y_pred: np.ndarray) -> float:
    return float(math.sqrt(np.mean((y_true - y_pred) ** 2)))

def mae_all(y_true: np.ndarray, y_pred: np.ndarray) -> float:
    return float(np.mean(np.abs(y_true - y_pred)))

def _weighted_corr(x, y, w, eps=1e-12):
    x = np.asarray(x, dtype=np.float64)
    y = np.asarray(y, dtype=np.float64)
    w = np.asarray(w, dtype=np.float64)
    ws = w.sum()
    if ws <= eps:
        return float("nan")
    w = w / (ws + eps)
    mx = (w * x).sum()
    my = (w * y).sum()
    cov = (w * (x - mx) * (y - my)).sum()
    vx = (w * (x - mx) ** 2).sum()
    vy = (w * (y - my) ** 2).sum()
    return float(cov / (np.sqrt(vx * vy) + eps))

def _weighted_mi_sign_mag(sign01, mag, w, n_bins=10, eps=1e-12):
    sign01 = np.asarray(sign01, dtype=np.int64)
    mag = np.asarray(mag, dtype=np.float64)
    w = np.asarray(w, dtype=np.float64)
    ws = w.sum()
    if ws <= eps:
        return float("nan")

    # bin by quantiles (robust)
    qs = np.linspace(0, 1, n_bins + 1)
    edges = np.quantile(mag, qs)
    edges[0] -= 1e-9
    edges[-1] += 1e-9
    b = np.digitize(mag, edges[1:-1], right=True)  # 0..n_bins-1

    joint = np.zeros((2, n_bins), dtype=np.float64)
    for s in (0, 1):
        for j in range(n_bins):
            joint[s, j] = w[(sign01 == s) & (b == j)].sum()

    joint = joint / (joint.sum() + eps)
    ps = joint.sum(axis=1, keepdims=True)
    pb = joint.sum(axis=0, keepdims=True)

    mi_nats = (joint * np.log((joint + eps) / (ps * pb + eps))).sum()
    return float(mi_nats / np.log(2.0))  # bits

# Empirical interval coverage from Monte Carlo samples at the requested quantile levels
def coverage_from_samples_1d(y_true: np.ndarray, samples: np.ndarray, q_low: float, q_high: float) -> float:
    lo = np.quantile(samples, q_low, axis=0)
    hi = np.quantile(samples, q_high, axis=0)
    return float(np.mean((y_true >= lo) & (y_true <= hi)))

def _mean_abs_pairwise_sorted(samples_sorted: np.ndarray) -> np.ndarray:
    S = samples_sorted.shape[0]
    k = np.arange(1, S + 1, dtype=np.float64).reshape(-1, 1)
    w = (2.0 * k - S - 1.0)
    sum_abs = 2.0 * np.sum(w * samples_sorted, axis=0)
    return sum_abs / (S * S)

# CRPS estimate from samples as a proper scoring rule for distributional forecasts
def crps_from_samples_1d(y_true: np.ndarray, samples: np.ndarray) -> float:
    term1 = np.mean(np.abs(samples - y_true.reshape(1, -1)), axis=0)
    s_sorted = np.sort(samples, axis=0)
    e_abs_xx = _mean_abs_pairwise_sorted(s_sorted)
    crps = term1 - 0.5 * e_abs_xx
    return float(np.mean(crps))

def cia95_from_cov95(cov95_percent: float) -> float:
    cov = cov95_percent / 100.0
    return 100.0 * (1.0 - abs(cov - 0.95) / 0.95)

def energy_score(y_true: np.ndarray, samples: np.ndarray, seed: int = 0) -> float:
    """
    Multivariate probabilistic score for JOINT forecasts.
    y_true:  [N,H]
    samples: [S,N,H]
    """
    rng = np.random.default_rng(seed)
    S, N, H = samples.shape

    y = y_true[None, :, :]  # [1,N,H]
    d1 = np.linalg.norm(samples - y, axis=2)  # [S,N]
    term1 = d1.mean()

    # approximate E||X-X'|| with random pairing (O(S))
    idx = rng.integers(0, S, size=S)
    d2 = np.linalg.norm(samples - samples[idx], axis=2)  # [S,N]
    term2 = 0.5 * d2.mean()

    return float(term1 - term2)

def bootstrap_ci(metric_fn, y_true: np.ndarray, y_pred: np.ndarray,
                 B: int = 1000, alpha: float = 0.05, seed: int = 0) -> tuple[float, float]:
    """
    Resamples on window dimension N (rows), keeps horizon dimension.
    metric_fn should accept (y_true, y_pred) arrays with shape [N,H].
    """
    rng = np.random.default_rng(seed)
    N = y_true.shape[0]
    vals = np.empty(B, dtype=np.float64)

    for b in range(B):
        idx = rng.integers(0, N, size=N)
        vals[b] = metric_fn(y_true[idx], y_pred[idx])

    lo = float(np.quantile(vals, alpha / 2))
    hi = float(np.quantile(vals, 1 - alpha / 2))
    return lo, hi

def _mbb_indices(n: int, block_len: int, rng: np.random.Generator) -> np.ndarray:
    if block_len <= 1:
        return rng.integers(0, n, size=n)
    n_blocks = int(np.ceil(n / block_len))
    starts = rng.integers(0, n - block_len + 1, size=n_blocks)
    idx = np.concatenate([np.arange(s, s + block_len) for s in starts])[:n]
    return idx

def bootstrap_ci_mbb(metric_fn, y_true: np.ndarray, y_pred: np.ndarray,
                     block_len: int, B: int = 1000, alpha: float = 0.05, seed: int = 0) -> tuple[float, float]:
    rng = np.random.default_rng(seed)
    N = y_true.shape[0]
    vals = np.empty(B, dtype=np.float64)
    for b in range(B):
        idx = _mbb_indices(N, block_len, rng)
        vals[b] = metric_fn(y_true[idx], y_pred[idx])
    lo = float(np.quantile(vals, alpha / 2))
    hi = float(np.quantile(vals, 1 - alpha / 2))
    return lo, hi

def dm_test_newey_west(d: np.ndarray, lag: int = 5) -> tuple[float, float]:
    """
    d_t = loss_model_t - loss_base_t
    Newey-West HAC variance, t-approx p-value (two-sided).
    """
    d = np.asarray(d, dtype=np.float64)
    d = d[np.isfinite(d)]
    T = d.size
    if T < 20:
        return float("nan"), float("nan")

    mu = d.mean()
    x = d - mu

    gamma0 = np.mean(x * x)
    var = gamma0
    L = min(lag, T - 1)
    for l in range(1, L + 1):
        cov = np.mean(x[l:] * x[:-l])
        w = 1.0 - l / (L + 1.0)
        var += 2.0 * w * cov

    dm = mu / np.sqrt(var / T + 1e-12)
    p = 2.0 * (1.0 - student_t.cdf(abs(dm), df=max(T - 1, 1)))
    return float(dm), float(p)

def nw_lag_rule(T: int, cap: int = 24) -> int:
    # standard rule: ~ 1.5 * T^(1/3)
    if T <= 1:
        return 1
    L = int(round(1.5 * (T ** (1.0 / 3.0))))
    return int(max(1, min(cap, T - 1, L)))

def fisher_pvalue(pvals: list[float]) -> float:
    p = np.asarray([x for x in pvals if np.isfinite(x) and (x > 0.0) and (x <= 1.0)], dtype=np.float64)
    if p.size == 0:
        return float("nan")
    stat = -2.0 * np.sum(np.log(p))
    return float(1.0 - chi2.cdf(stat, df=2 * p.size))


def pit_from_samples(y_true: np.ndarray, samples: np.ndarray) -> np.ndarray:
    """
    PIT values using samples.
    y_true:  [N,H]
    samples: [S,N,H]
    returns: [N,H] values in [0,1]
    """
    return np.mean(samples <= y_true[None, :, :], axis=0)

def pit_ks(pit: np.ndarray) -> float:
    """
    Kolmogorov-Smirnov distance to Uniform(0,1) for PIT values (flattened).
    """
    u = np.sort(pit.reshape(-1))
    n = u.size
    if n == 0:
        return float("nan")
    ecdf = np.arange(1, n + 1) / n
    return float(np.max(np.abs(ecdf - u)))

def interval_width_from_samples(samples: np.ndarray, q_low: float, q_high: float) -> float:
    """
    Mean interval width across all N,H.
    samples: [S,N,H]
    """
    lo = np.quantile(samples, q_low, axis=0)
    hi = np.quantile(samples, q_high, axis=0)
    return float(np.mean(hi - lo))

def calibration_abs_error(y_true: np.ndarray, samples: np.ndarray, levels=(0.5, 0.9, 0.95)) -> float:
    """
    Average absolute calibration error across nominal central interval levels.
    """
    errs = []
    for lvl in levels:
        q = (1 - lvl) / 2
        cov = coverage_from_samples_1d(y_true.reshape(-1), samples.reshape(samples.shape[0], -1), q, 1 - q)
        errs.append(abs(cov - lvl))
    return float(np.mean(errs))

def cov95_joint(y_true: np.ndarray, samples: np.ndarray) -> float:
    """
    y_true:  [N,H]
    samples: [S,N,H]
    """
    lo = np.quantile(samples, 0.025, axis=0)
    hi = np.quantile(samples, 0.975, axis=0)
    return float(np.mean((y_true >= lo) & (y_true <= hi)))

@torch.no_grad()
def fit_dispersion_scale_val(
    model,
    Xva_t: torch.Tensor,
    yva: np.ndarray,
    device: str,
    n_samples: int,
    seed: int,
    max_val_windows: int = 3000,
) -> tuple[float, float]:
    """
    Return: (v_best, cov95_val_best)
    """
    rng = np.random.default_rng(seed)
    N = yva.shape[0]
    if N > max_val_windows:
        idx = rng.choice(N, size=max_val_windows, replace=False)
        Xc = Xva_t[idx]
        yc = yva[idx]
    else:
        Xc = Xva_t
        yc = yva

    grid = [0.8, 0.9, 1.0, 1.1, 1.25, 1.4, 1.6, 1.9, 2.2, 2.6, 3.0]

    best_v = 1.0
    best_err = 1e9
    best_cov = np.nan

    model.eval()
    for v in grid:
        smp = model.sample(Xc.to(device), n_samples=n_samples, dispersion_scale=float(v)).cpu().numpy()
        cov = cov95_joint(yc, smp)
        err = abs(cov - 0.95)
        if err < best_err:
            best_err = err
            best_v = float(v)
            best_cov = float(cov)

    return best_v, best_cov

@torch.no_grad()
def avg_test_nll_per_horizon(model: GlobalJointConditionalSPN, loader: DataLoader, device: str, horizon: int) -> float:
    model.eval()
    total = 0.0
    n = 0
    for xb, yb in loader:
        xb = xb.to(device)
        yb = yb.to(device)
        logp = model.log_prob(xb, yb)   # joint logp
        total += float((-logp).sum().item())
        n += xb.size(0)
    # report per-horizon average NLL
    return (total / max(1, n)) / float(horizon)


@torch.no_grad()
def sign_mag_dependence_table(model, X_np, y_np, device, n_bins=10, max_rows=None):
    """
    Computes dependence between sign(y_h) and |y_h| inside each root component k,
    using posterior responsibilities r_{b,k} = p(k | x_b, y_b) from the SPN.
    Returns df with columns: h, k, N_eff, corr(sign,|y|), MI_bits
    """
    model.eval()
    X = torch.tensor(X_np).to(device)
    y = torch.tensor(y_np).to(device)

    # optional subsample for speed
    if (max_rows is not None) and (X.shape[0] > max_rows):
        idx = torch.randperm(X.shape[0], device=device)[:max_rows]
        X = X[idx]
        y = y[idx]

    r = model.posterior_k(X, y).detach().cpu().numpy()   # [B,K]
    yv = y.detach().cpu().numpy()                        # [B,H]

    B, K = r.shape
    H = yv.shape[1]

    rows = []
    for h in range(H):
        sign01 = (yv[:, h] >= 0).astype(np.int64)
        mag    = np.abs(yv[:, h]).astype(np.float64)

        for k in range(K):
            w = r[:, k].astype(np.float64)

            ws = w.sum()
            w2 = (w * w).sum()
            N_eff = (ws * ws) / (w2 + 1e-12)

            corr = _weighted_corr(sign01, mag, w)
            mi   = _weighted_mi_sign_mag(sign01, mag, w, n_bins=n_bins)

            rows.append({
                "h": h + 1,
                "k": k,
                "N_eff": float(N_eff),
                "corr(sign,|y|)": float(corr),
                "MI_bits": float(mi),
            })

    return pd.DataFrame(rows)

    # ---- call (right after you have model, Xte, yte) ----
    df_dep = sign_mag_dependence_table(model, Xte, yte, device=device, n_bins=10, max_rows=None)
    save_table(df_dep, name=f"sign_mag_dependence_{tag}", float_fmt="%.6f")


# ---------------- CLI ----------------

def parse_args(argv=None) -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Joint multi-horizon conditional SPN (Colab-friendly)")
    p.add_argument("--csv_path", type=str, default="") # Changed default to empty string
    p.add_argument("--n_samples", type=int, default=1000)
    p.add_argument("--seed", type=int, default=SEED)
    p.add_argument("--horizon", type=int, default=HORIZON)
    p.add_argument("--seed_split", type=int, default=SEED)
    p.add_argument("--seed_model", type=int, default=SEED)
    p.add_argument("--k_root", type=int, default=K_ROOT)
    p.add_argument("--m_mag", type=int, default=M_MAG)
    p.add_argument("--hidden", type=int, default=HIDDEN)
    p.add_argument("--dropout", type=float, default=DROPOUT)
    p.add_argument("--window", type=int, default=WINDOW)
    p.add_argument("--seeds", type=str, default="42,43,44")
    p.add_argument("--n_eval_sets", type=int, default=5)
    p.add_argument("--eval_seed_base", type=int, default=123)
    p.add_argument("--split_seed_base", type=int, default=1000)
    return p.parse_args(args=([] if argv is None else argv))


def run_once(
      args: argparse.Namespace,
      seed_split: int,
      seed_model: int,
      device: str,
      eval_set_id: int,
      eval_seed: int,
      eval_cities: list[str],
) -> dict:
    """
    One full experiment run for a given (seed_split, seed_model).
    Returns a dict with scalar metrics so main() can summarize across seeds.
    """

    # ---- seeds & determinism
    set_seed(seed_model, deterministic=True)

    H = int(args.horizon)
    print("\n" + "=" * 70)
    print(f"RUN | seed_split: {seed_split} | seed_model: {seed_model} | device: {device} | H={H}")
    print("=" * 70)
    run_wall_t0 = time.time()
    plot_framework_diagram_once()

    # ---------------- Load + preprocess ----------------
    df = load_kaggle_dataset(KAGGLE_DATASET_REF, KAGGLE_FILE_PATH)
    df = df[df["Year"] >= 1900].copy()
    y0, y1 = probe_span(df)
    print(f"[DIAG] Available years: {y0}..{y1}, cities: {df['City'].nunique()}")

    # build once, then we can drop raw daily df to save RAM
    city_region = build_city_region_map(df)

    monthly = aggregate_monthly(df, y0, y1)
    monthly = exclude_incomplete_years(monthly, min_months=MIN_MONTHS_PER_YEAR)
    monthly = reindex_month_grid(monthly, y0, y1)

    train_end, val_end = split_years(y0, y1)
    print(f"[DIAG] Time splits -> TRAIN<= {train_end}, VAL: {train_end+1}..{val_end}, TEST: {val_end+1}..{y1}")
    print(f"[DIAG] Horizon H={H}")

    # anomalies with train-only climatology
    monthly = build_anomalies_fixed_climatology(monthly, train_end=train_end)

    # raw daily df no longer needed (we already extracted city_region)
    del df
    gc.collect()

    # dataset examples (generate once)
    example_cities = []
    for c in eval_cities[:3]:
        if (monthly["City"] == c).any():
            example_cities.append(c)
    if len(example_cities) < 3:
        # fallback
        example_cities = list(monthly["City"].drop_duplicates().head(3).to_list())

    plot_dataset_examples_once(monthly, example_cities, train_end=train_end, val_end=val_end)


    # ----- Choose eval/test cities (fixed or stratified) -----
    print(f"[DIAG] Eval set id: {eval_set_id} | eval_seed: {eval_seed}")
    print("[DIAG] Eval (TEST) cities:", eval_cities)
    eval_set_norm = {norm_city_name(c) for c in eval_cities}

    # geographic split: train/val/test cities disjoint
    all_cities = sorted(monthly["City"].unique())
    train_cities_norm, val_cities_norm, test_cities_norm = split_cities_geographic(
        all_cities, eval_set_norm, seed=seed_split
    )

    print(f"[DIAG] Geographic split -> TRAIN cities: {len(train_cities_norm)}, VAL cities: {len(val_cities_norm)}, TEST cities: {len(test_cities_norm)}")
    if len(test_cities_norm) == 0:
        raise RuntimeError("No test cities matched EVAL_CITIES in the dataset (check city names).")

    # ---- artifacts filenames (so multiple seeds do not overwrite)
    tag = f"set{eval_set_id}_seedS{seed_split}_seedM{seed_model}_H{H}"
    run_manifest = {
        "timestamp": time.strftime("%Y-%m-%d %H:%M:%S"),
        "csv_path": args.csv_path, # This will now be empty if using KaggleHub
        "kaggle_dataset_ref": KAGGLE_DATASET_REF, # Add new field for Kaggle reference
        "years": {"min": y0, "max": y1, "train_end": train_end, "val_end": val_end},
        "seeds": {"split": seed_split, "model": seed_model},
        "hyperparams": {
            "window": args.window,
            "horizon": H,
            "k_root": args.k_root,
            "m_mag": args.m_mag,
            "hidden": args.hidden,
            "dropout": args.dropout,
            "lr": LR,
            "batch": BATCH,
            "epochs": EPOCHS,
            "warmup": WARMUP,
            "patience": PATIENCE,
            "max_pchip_gap": MAX_PCHIP_GAP,
            "min_months_per_year": MIN_MONTHS_PER_YEAR,
        },
        "eval_cities": eval_cities,
        "splits": {
            "train_cities_norm": sorted(list(train_cities_norm)),
            "val_cities_norm": sorted(list(val_cities_norm)),
            "test_cities_norm": sorted(list(test_cities_norm)),
        },
        "versions": {"torch": torch.__version__, "numpy": np.__version__, "pandas": pd.__version__},
        "eval_set": {"id": eval_set_id, "seed": eval_seed},
        "pipeline": {
            "aggregation": "Daily AvgTemperature -> monthly mean per City-Year-Month.",
            "climatology": f"Per-city month-of-year mean computed using only years <= {train_end}.",
            "anomaly": "Anomaly_raw = AvgTemperature - climatology(month).",
            "targets": "Targets are raw anomalies; any window with missing targets is discarded (no target imputation).",
            "pchip": f"Input-only causal PCHIP inside the past window; only internal gaps <= {MAX_PCHIP_GAP} months are imputed.",
            "scaling": "StandardScaler is fit on TRAIN windows only for features [anomaly, delta] and applied to VAL/TEST."
        }
    }

    with open(f"run_manifest_{tag}.json", "w", encoding="utf-8") as f:
        json.dump(run_manifest, f, indent=2)

    # joint windowing
    X_split, Y_split, c_split, y1year_split, city2id = make_windows_global_joint(
        monthly,
        window=args.window,
        horizon=H,
        train_end=train_end,
        val_end=val_end,
        train_cities_norm=train_cities_norm,
        val_cities_norm=val_cities_norm,
        test_cities_norm=test_cities_norm,
        max_pchip_gap=MAX_PCHIP_GAP,
    )

    for kname in ["train", "val", "test"]:
        print(f"[DIAG] {kname.upper()} samples: {len(X_split[kname])}")

    if len(X_split["train"]) == 0 or len(X_split["val"]) == 0 or len(X_split["test"]) == 0:
        raise RuntimeError("Empty split. Try smaller --horizon (e.g., 3 or 6) or check dataset coverage.")


    # ---------------- Scale inputs (fit on TRAIN only) ----------------
    scaler = StandardScaler()
    flat_tr = X_split["train"][..., [0, 3]].reshape(-1, 2)  # anomaly + delta
    scaler.fit(flat_tr)

    np.savez(f"scaler_anom_delta_{tag}.npz", mean=scaler.mean_, scale=scaler.scale_)

    def apply_scale(X: np.ndarray) -> np.ndarray:
        Xc = X.copy()
        flat = Xc[..., [0, 3]].reshape(-1, 2)
        flat = scaler.transform(flat)
        Xc[..., [0, 3]] = flat.reshape(Xc.shape[0], Xc.shape[1], 2)
        return Xc

    Xtr_raw = X_split["train"]
    Xva_raw = X_split["val"]
    Xte_raw = X_split["test"]

    Xtr = apply_scale(Xtr_raw); ytr = Y_split["train"]
    Xva = apply_scale(Xva_raw); yva = Y_split["val"]
    Xte = apply_scale(Xte_raw); yte = Y_split["test"]



    # ---------------- Export for TSLib (Autoformer/Informer) ----------------
    # We export univariate target: anomaly only (channel 0), in the same units as y (°C anomalies).
    # Also export time marks for monthly freq: MonthOfYear in [-0.5, 0.5] (same as TSLib time_features for freq='m').

    def month_mark_from_sin_cos(sin_m, cos_m):
        # Recover month index 1..12 robustly from sin/cos, then map to [-0.5, 0.5]
        ang = np.arctan2(sin_m, cos_m)  # [-pi, pi]
        ang = (ang + 2*np.pi) % (2*np.pi)
        m_idx0 = np.round(ang * 12.0 / (2*np.pi)).astype(int) % 12  # 0..11
        # map 0..11 -> [-0.5, 0.5]
        return (m_idx0 / 11.0) - 0.5

    def build_marks_from_X(X, label_len, pred_len):
        # X: [N, W, 4] where channels 1,2 are sin/cos(month)
        sin_enc = X[:, :, 1]
        cos_enc = X[:, :, 2]
        enc_mark = month_mark_from_sin_cos(sin_enc, cos_enc)[:, :, None].astype(np.float32)  # [N,W,1]

        # decoder mark length = label_len + pred_len
        # we take last label_len marks from enc, and for future pred_len we just roll months forward
        last_ang = np.arctan2(sin_enc[:, -1], cos_enc[:, -1])
        last_ang = (last_ang + 2*np.pi) % (2*np.pi)
        last_m0 = (np.round(last_ang * 12.0 / (2*np.pi)).astype(int) % 12)  # 0..11

        # build future months 1..pred_len ahead (0..11)
        fut = []
        for j in range(1, pred_len + 1):
            fut.append(((last_m0 + j) % 12)[:, None])
        fut_m0 = np.concatenate(fut, axis=1)  # [N,pred_len]
        fut_mark = (fut_m0 / 11.0 - 0.5)[:, :, None].astype(np.float32)  # [N,pred_len,1]

        dec_mark = np.concatenate([enc_mark[:, -label_len:, :], fut_mark], axis=1)  # [N,label_len+pred_len,1]
        return enc_mark, dec_mark

    label_len = min(6, args.window)  # recomandat 6 cand H=6
    pred_len  = H

    Xtr_y = Xtr[:, :, 0:1].astype(np.float32)
    Xva_y = Xva[:, :, 0:1].astype(np.float32)
    Xte_y = Xte[:, :, 0:1].astype(np.float32)

    ytr_y = ytr[:, :, None].astype(np.float32)  # [N,H,1]
    yva_y = yva[:, :, None].astype(np.float32)
    yte_y = yte[:, :, None].astype(np.float32)

    xtr_mark, ytr_mark = build_marks_from_X(Xtr, label_len=label_len, pred_len=pred_len)
    xva_mark, yva_mark = build_marks_from_X(Xva, label_len=label_len, pred_len=pred_len)
    xte_mark, yte_mark = build_marks_from_X(Xte, label_len=label_len, pred_len=pred_len)

    # Save to NPZ inside artifacts/npz to keep it tidy
    npz_out = NPZ_DIR / f"tslib_cityanom_{tag}_W{args.window}_H{H}.npz"
    np.savez_compressed(
        npz_out,
        X_train=Xtr_y, y_train=ytr_y, X_train_mark=xtr_mark, y_train_mark=ytr_mark,
        X_val=Xva_y,   y_val=yva_y,   X_val_mark=xva_mark, y_val_mark=yva_mark,
        X_test=Xte_y,  y_test=yte_y,  X_test_mark=xte_mark, y_test_mark=yte_mark,
        label_len=np.array([label_len], dtype=np.int32),
        pred_len=np.array([pred_len], dtype=np.int32),
    )
    print(f"[ART] saved TSLib NPZ: {npz_out}")
    # ----------------------------------------------------------------------



    cte = c_split["test"]
    yte_year1 = y1year_split["test"]

    # keep only what we need from raw (for persistence baseline)
    xte_last_anom = Xte_raw[:, -1, 0:1].copy()
    del Xtr_raw, Xva_raw, Xte_raw
    del X_split, Y_split, c_split, y1year_split
    gc.collect()

    Xtr_t = torch.from_numpy(Xtr)
    ytr_t = torch.from_numpy(ytr)
    Xva_t = torch.from_numpy(Xva)
    yva_t = torch.from_numpy(yva)
    Xte_t_cpu = torch.from_numpy(Xte)
    yte_t_cpu = torch.from_numpy(yte)

    train_loader = DataLoader(TensorDataset(Xtr_t, ytr_t), batch_size=BATCH, shuffle=True, num_workers=0)
    val_loader   = DataLoader(TensorDataset(Xva_t, yva_t), batch_size=BATCH, shuffle=False, num_workers=0)
    test_loader  = DataLoader(TensorDataset(Xte_t_cpu, yte_t_cpu), batch_size=BATCH, shuffle=False, num_workers=0)

    ###
    def train_eval_variant(variant_name: str, shared_mag: bool):
      set_seed(seed_model, deterministic=True)

      model_v = GlobalJointConditionalSPN(
          in_ch=4,
          hidden=args.hidden,
          k_root=args.k_root,
          horizon=H,
          m_mag=args.m_mag,
          dropout=args.dropout,
          alpha_floor=ALPHA_FLOOR,
          beta_floor=BETA_FLOOR,
          shared_magnitude=shared_mag,
      )

      t0 = time.time()
      model_v = train_model(
          model=model_v,
          train_loader=train_loader,
          val_loader=val_loader,
          device=device,
          epochs=EPOCHS,
          lr=LR,
          warmup=WARMUP,
          patience=PATIENCE,
          l2_log_param=L2_LOG_PARAM,
          entropy_weight=ENTROPY_WEIGHT,
          grad_clip=1.0,
      )
      t1 = time.time()

      train_seconds = float(t1 - t0)
      n_params = int(sum(p.numel() for p in model_v.parameters()))

      model_v.eval()
      with torch.no_grad():
          Xte_t = torch.tensor(Xte).to(device)
          Xva_t = torch.tensor(Xva).to(device)

          v_disp, _ = fit_dispersion_scale_val(
              model_v, Xva_t, yva, device=device,
              n_samples=min(400, args.n_samples),
              seed=seed_model,
          )

          y_pred_v = model_v.predictive_mean(Xte_t).cpu().numpy()
          samples_v = model_v.sample(Xte_t, n_samples=args.n_samples, dispersion_scale=v_disp).cpu().numpy()

      rmse_v = rmse_all(yte, y_pred_v)
      mae_v  = mae_all(yte, y_pred_v)
      nll_ph_v = float(avg_test_nll_per_horizon(model_v, test_loader, device=device, horizon=H))
      crps_h_v = [crps_from_samples_1d(yte[:, h], samples_v[:, :, h]) for h in range(H)]
      crps_avg_v = float(np.mean(crps_h_v))

      return {
          "Variant": variant_name,
          "RMSE": float(rmse_v),
          "MAE": float(mae_v),
          "CRPS": float(crps_avg_v),
          "NLL_per_h": float(nll_ph_v),
          "samples": samples_v,
          "y_pred": y_pred_v,
          "model": model_v,
          "v_disp": float(v_disp),
          "train_seconds": train_seconds,
          "n_params": n_params,
      }


    # ---------------- Train + Predict ----------------
    res_ours = train_eval_variant("Sign-specific magnitude (ours)", shared_mag=False)
    model   = res_ours["model"]
    y_pred  = res_ours["y_pred"]
    samples = res_ours["samples"]
    v_disp  = res_ours["v_disp"]


    # ---------------- SPN diagnostics ----------------
    # 1) GOF magnitude |y|
    # uncomment next line for mag gof plot
    # plot_mag_gof(yte, samples, fig_name=f"fig_mag_gof_{tag}")

    # 2) Dependence sign - |y| on (h,k) using responsibilities p(k|x,y)
    df_dep = sign_mag_dependence_table(
        model=model,
        X_np=Xte,
        y_np=yte,
        device=device,
        n_bins=10,
        max_rows=None,
    )
    save_table(df_dep, name=f"sign_mag_dependence_{tag}", float_fmt="%.6f")


    run_manifest["compute"] = {
        "train_seconds": float(res_ours["train_seconds"]),
        "n_params": int(res_ours["n_params"]),
        "device": device,
        "cuda_name": (torch.cuda.get_device_name(0) if torch.cuda.is_available() else "cpu"),
    }

    # ===== Extra metrics that were previously undefined in return() =====
    with torch.no_grad():
        Xte_t = torch.tensor(Xte).to(device)

        # independent-latent samples (same marginals, no cross-horizon dependence)
        samples_ind = model.sample_independent(Xte_t, n_samples=args.n_samples, dispersion_scale=v_disp).cpu().numpy()

    # Energy score (joint vs independent)
    es_joint = energy_score(yte, samples, seed=seed_model)
    es_ind   = energy_score(yte, samples_ind, seed=seed_model)

    # PIT + KS distance to Uniform(0,1)
    pit_vals   = pit_from_samples(yte, samples)   # [N,H]
    pit_ks_val = pit_ks(pit_vals)

    # Mean 95% interval width
    iw95 = interval_width_from_samples(samples, 0.025, 0.975)

    # Average absolute calibration error over levels
    cal_ae = calibration_abs_error(yte, samples, levels=(0.5, 0.9, 0.95))

    # Off-diagonal correlation magnitude (batched, safe)
    def corr_offdiag_batched(model, X_np, device, batch_size=2048):
        model.eval()
        H = model.horizon
        mask = ~np.eye(H, dtype=bool)
        vals = []

        with torch.no_grad():
            for i in range(0, X_np.shape[0], batch_size):
                xb = torch.tensor(X_np[i:i+batch_size]).to(device)
                cov = model.covariance_matrix(xb).detach().cpu().numpy()  # [B,H,H]

                # corr = cov / sqrt(var_i var_j)
                var = np.diagonal(cov, axis1=1, axis2=2)                  # [B,H]
                denom = np.sqrt(np.clip(var, 1e-12, None))
                corr = cov / (denom[:, :, None] * denom[:, None, :] + 1e-12)

                vals.append(np.mean(np.abs(corr[:, mask])))

        return float(np.mean(vals)) if len(vals) else float("nan")

    corr_off = corr_offdiag_batched(model, Xte, device=device, batch_size=2048)


    # ---------------- Ablation ----------------
    if (eval_set_id == 0) and (seed_model == 42):
        res_shared = train_eval_variant("Shared magnitude", shared_mag=True)

        df_ab = pd.DataFrame([
            {k: res_shared[k] for k in ["Variant","RMSE","MAE","CRPS","NLL_per_h"]},
            {k: res_ours[k]   for k in ["Variant","RMSE","MAE","CRPS","NLL_per_h"]},
        ])
        save_table(df_ab, name="signed_gamma_ablation", float_fmt="%.4f")


    # ---------------- Metrics ----------------
    rmse_g = rmse_all(yte, y_pred)
    mae_g  = mae_all(yte, y_pred)
    nll_ph = float(avg_test_nll_per_horizon(model, test_loader, device=device, horizon=H))

    # JOINT score
    es = energy_score(yte, samples, seed=seed_model)

    # confidence intervals (bootstrap over windows)
    rmse_ci = bootstrap_ci(rmse_all, yte, y_pred, B=1000, seed=seed_model)
    mae_ci  = bootstrap_ci(mae_all,  yte, y_pred, B=1000, seed=seed_model)

    # per-horizon metrics
    rmse_h, mae_h, crps_h, cov95_h = [], [], [], []
    for h in range(H):
        rmse_h.append(rmse_all(yte[:, h], y_pred[:, h]))
        mae_h.append(mae_all(yte[:, h], y_pred[:, h]))
        crps_h.append(crps_from_samples_1d(yte[:, h], samples[:, :, h]))
        cov95_h.append(100.0 * coverage_from_samples_1d(yte[:, h], samples[:, :, h], 0.025, 0.975))

    rmse_avg  = float(np.mean(rmse_h))
    mae_avg   = float(np.mean(mae_h))
    crps_avg  = float(np.mean(crps_h))
    cov95_avg = float(np.mean(cov95_h))

    # baselines
    y_pred_clim0 = np.zeros_like(yte, dtype=np.float32)
    y_pred_persist = np.repeat(xte_last_anom, repeats=H, axis=1).astype(np.float32)


    # ----- Statistical tests: DM + Moving-Block Bootstrap (seasonal blocks) -----
    loss_model = np.mean((y_pred - yte) ** 2, axis=1)          # [N]
    loss_pers  = np.mean((y_pred_persist - yte) ** 2, axis=1)  # [N]
    d_mp = loss_model - loss_pers                              # DM diff

    dm_stat, dm_p = dm_test_newey_west(d_mp, lag=5)
    print(f"[DM] Model vs Persist | DM={dm_stat:.3f} | p={dm_p:.4g} | mean(d)={d_mp.mean():.6f} (negative=better)")

    for L in [6, 12, 24]:
        lo, hi = bootstrap_ci_mbb(lambda yt, yp: np.mean((yp - yt) ** 2), yte, y_pred_persist, block_len=L, B=1000, seed=seed_model + 10*L)
        # CI for MSE(persist)
        dlo, dhi = bootstrap_ci_mbb(lambda yt, yp: np.mean(np.mean((y_pred - yt) ** 2, axis=1) - np.mean((yp - yt) ** 2, axis=1)),
                                    yte, y_pred_persist, block_len=L, B=1000, seed=seed_model + 100*L)
        print(f"[MBB] block={L} | CI95(mean d_model-pers)=[{dlo:.6f},{dhi:.6f}]")

    # MBB CI for RMSE(flat) (requested block-length robustness)
    for L in [6, 12, 24]:
        rm_lo, rm_hi = bootstrap_ci_mbb(rmse_all, yte, y_pred, block_len=L, B=1000, seed=seed_model + 1000*L)
        print(f"[MBB] block={L} | RMSE(flat) CI95=[{rm_lo:.3f},{rm_hi:.3f}]")


    rmse_clim0 = rmse_all(yte, y_pred_clim0)
    mae_clim0  = mae_all(yte, y_pred_clim0)
    rmse_pers  = rmse_all(yte, y_pred_persist)
    mae_pers   = mae_all(yte, y_pred_persist)

    print("\n===== GLOBAL TEST (JOINT; TEST cities; years > VAL) =====")
    print(
        f"H={H} | RMSE(flat): {rmse_g:.2f} °C [{rmse_ci[0]:.2f}, {rmse_ci[1]:.2f}] | "
        f"MAE(flat): {mae_g:.2f} °C [{mae_ci[0]:.2f}, {mae_ci[1]:.2f}] | "
        f"NLL(per-h): {nll_ph:.4f} nats | EnergyScore(joint): {es:.4f}"
    )
    print(f"AVG over horizons | RMSE: {rmse_avg:.2f} | MAE: {mae_avg:.2f} | CRPS: {crps_avg:.4f} | Cov@95(avg): {cov95_avg:.1f}%")
    print(f"Clim-0(flat)  | RMSE: {rmse_clim0:.2f} | MAE: {mae_clim0:.2f}")
    print(f"Persist(flat) | RMSE: {rmse_pers:.2f} | MAE: {mae_pers:.2f}")

    del xte_last_anom
    gc.collect()

    # ---------------- TinyTransformer baseline ----------------
    RUN_TINY_TRANSFORMER = True
    if RUN_TINY_TRANSFORMER:
        tt0 = time.time()
        tinyT = train_tiny_transformer(train_loader, val_loader, H=H, device=device,
                                      max_epochs=50, lr=1e-3, patience=8, seed=seed_split)
        tt1 = time.time()

        tinyT.eval()
        preds_t = []
        ys_t = []
        with torch.no_grad():
            for xb, yb in test_loader:
                xb = xb.to(device)
                pred = tinyT(xb).detach().cpu().numpy()
                preds_t.append(pred)
                ys_t.append(yb.detach().cpu().numpy())
        preds_t = np.concatenate(preds_t, axis=0)
        ys_t = np.concatenate(ys_t, axis=0)

        rmse_tt = float(np.sqrt(np.mean((preds_t - ys_t) ** 2)))
        mae_tt = float(np.mean(np.abs(preds_t - ys_t)))
        print(f"TinyTransformer(flat) | RMSE: {rmse_tt:.2f} | MAE: {mae_tt:.2f} | train_sec: {tt1-tt0:.1f}")


    print("\n----- Per-horizon summary (h=1..H) -----")
    for h in range(H):
        print(f"h={h+1:2d} | RMSE={rmse_h[h]:.2f} | MAE={mae_h[h]:.2f} | CRPS={crps_h[h]:.4f} | Cov@95={cov95_h[h]:.1f}%")

    # Decade-wise aggregation using the first horizon year to study temporal stability of performance
    decades = np.unique((yte_year1 // 10) * 10)
    print("\n----- Decade-wise (TEST; grouped by first horizon year) -----")
    for d0 in decades:
        m = ((yte_year1 // 10) * 10) == d0
        if m.sum() < 10:
            continue
        yt = yte[m]           # [N_d, H]
        yp = y_pred[m]        # [N_d, H]
        sm = samples[:, m, :] # [S, N_d, H]

        crps_list = []
        cov95_list = []
        for h in range(H):
            crps_list.append(crps_from_samples_1d(yt[:, h], sm[:, :, h]))
            cov95_list.append(100.0 * coverage_from_samples_1d(yt[:, h], sm[:, :, h], 0.025, 0.975))

        print(
            f"{d0}s | N={m.sum():4d} | RMSE(flat)={rmse_all(yt, yp):.2f} | "
            f"MAE(flat)={mae_all(yt, yp):.2f} | CRPS(avg)={float(np.mean(crps_list)):.4f} | "
            f"Cov@95(avg)={float(np.mean(cov95_list)):.1f}%"
        )


    # regime-wise
    print("\n----- Regime-wise (TEST; grouped by first horizon year ranges) -----")
    regimes = [
      ("2001-2004", 2001, 2004),
      ("2005-2007", 2005, 2007),
      ("2008-2010", 2008, 2010),
      ("2011-2014", 2011, 2014),
      ("2015-2017", 2015, 2017),
      ("2018-2020", 2018, 2020),
    ]
    for name, a, b in regimes:
        m_reg = (yte_year1 >= a) & (yte_year1 <= b)
        if m_reg.sum() < 20:
            continue

        yt = yte[m_reg]
        yp = y_pred[m_reg]
        sm = samples[:, m_reg, :]

        crps_list = []
        cov95_list = []
        for h in range(H):
            crps_list.append(crps_from_samples_1d(yt[:, h], sm[:, :, h]))
            cov95_list.append(100.0 * coverage_from_samples_1d(yt[:, h], sm[:, :, h], 0.025, 0.975))

        print(
            f"{name} | N={m_reg.sum():4d} | RMSE(flat)={rmse_all(yt, yp):.2f} | "
            f"MAE(flat)={mae_all(yt, yp):.2f} | CRPS(avg)={float(np.mean(crps_list)):.4f} | "
            f"Cov@95(avg)={float(np.mean(cov95_list)):.1f}%"
        )

    # per-city table (same as your code)
    dataset_city_by_norm = {norm_city_name(city): city for city in city2id.keys()}

    rows = []
    for canon in eval_cities:
        cn = norm_city_name(canon)
        ds_city = dataset_city_by_norm.get(cn)

        if ds_city is None:
            rows.append([canon, "n/a", "n/a", "n/a", "n/a", "n/a", "n/a", "n/a", "n/a", "n/a", "n/a", "n/a", "n/a", "n/a"])
            continue

        cid = city2id[ds_city]
        m_city = (cte == cid)
        if m_city.sum() == 0:
            rows.append([canon, "n/a", "n/a", "n/a", "n/a", "n/a", "n/a", "n/a", "n/a", "n/a", "n/a", "n/a", "n/a", "n/a"])
            continue

        # --- DM per-city (model vs persist) ---
        d_city = d_mp[m_city]  # d_mp already exists (model - persist), shape [N_test]
        lag_city = nw_lag_rule(int(d_city.size))
        dm_city, p_city = dm_test_newey_west(d_city, lag=lag_city)

        region = city_region.get(ds_city, "n/a")
        n_test_windows = count_test_windows_for_city(
            monthly[monthly["City"] == ds_city],
            window=args.window,
            horizon=H,
            val_end=val_end,
            max_pchip_gap=MAX_PCHIP_GAP,
        )

        yt = yte[m_city]
        yp = y_pred[m_city]
        sm = samples[:, m_city, :]

        rm = rmse_all(yt, yp)
        ma = mae_all(yt, yp)

        with torch.no_grad():
            Xc = torch.tensor(Xte[m_city]).to(device)
            yc = torch.tensor(yt).to(device)
            logp = model.log_prob(Xc, yc)
            nll_city_ph = float((-logp).mean().item()) / float(H)

        crps_list, cov50_list, cov90_list, cov95_list, cia95_list = [], [], [], [], []
        for h in range(H):
            crps_hh = crps_from_samples_1d(yt[:, h], sm[:, :, h])
            cov50_hh = 100.0 * coverage_from_samples_1d(yt[:, h], sm[:, :, h], 0.25, 0.75)
            cov90_hh = 100.0 * coverage_from_samples_1d(yt[:, h], sm[:, :, h], 0.05, 0.95)
            cov95_hh = 100.0 * coverage_from_samples_1d(yt[:, h], sm[:, :, h], 0.025, 0.975)
            cia_hh = cia95_from_cov95(cov95_hh)

            crps_list.append(crps_hh)
            cov50_list.append(cov50_hh)
            cov90_list.append(cov90_hh)
            cov95_list.append(cov95_hh)
            cia95_list.append(cia_hh)

        rows.append([
            canon,
            region,
            int(n_test_windows),
            f"{rm:.2f}",
            f"{ma:.2f}",
            f"{nll_city_ph:.4f}",
            f"{float(np.mean(crps_list)):.4f}",
            f"{float(np.mean(cia95_list)):.2f}%",
            f"{float(np.mean(cov50_list)):.1f}%",
            f"{float(np.mean(cov90_list)):.1f}%",
            f"{float(np.mean(cov95_list)):.1f}%",
            int(m_city.sum()),
            f"{dm_city:.3f}",
            f"{p_city:.4g}",
        ])

    table = pd.DataFrame(
        rows,
        columns=[
            "City",
            "Region",
            "N_test_windows",
            "RMSE (°C)",
            "MAE (°C)",
            "NLL (per-h)",
            "CRPS (°C)",
            "CIA95",
            "Cov@50",
            "Cov@90",
            "Cov@95",
            "N_windows_in_test",
            "DM_vs_Persist",
            "DM_p",
        ],
    )

    print("\n----- Per-city (eval cities; years > VAL) -----")
    print(table.to_string(index=False))
    # --- rewrite manifest at the end so it includes any late-added fields ---
    with open(f"run_manifest_{tag}.json", "w", encoding="utf-8") as f:
        json.dump(run_manifest, f, indent=2)


    pvals = []
    for _, r in table.iterrows():
        try:
            p = float(r["DM_p"])
        except Exception:
            p = np.nan
        if np.isfinite(p):
            pvals.append(p)

    p_fisher = fisher_pvalue(pvals)
    sig_count = int(np.sum(np.asarray(pvals) < 0.05)) if len(pvals) else 0
    print(f"\n[DM] Per-city summary | significant(p<0.05): {sig_count}/{len(pvals)} | Fisher combined p={p_fisher:.4g}")

    run_wall_t1 = time.time()
    run_total_sec = float(run_wall_t1 - run_wall_t0)
    run_manifest["compute"]["run_total_seconds"] = run_total_sec

    # ---- return scalars for seed summary
    return {
        "seed_split": seed_split,
        "seed_model": seed_model,
        "H": H,
        "rmse_flat": float(rmse_g),
        "mae_flat": float(mae_g),
        "nll_per_h": float(nll_ph),
        "energy_joint": float(es_joint),
        "energy_ind": float(es_ind),
        "pit_ks": float(pit_ks_val),
        "iw95": float(iw95),
        "cal_ae": float(cal_ae),
        "corr_offdiag": float(corr_off),
        "n_test": int(Xte.shape[0]),
        "eval_set_id": int(eval_set_id),
        "eval_seed": int(eval_seed),
        "eval_cities": "|".join(eval_cities),
        "crps_avg": float(crps_avg),
        "cov95_avg": float(cov95_avg),
        "dispersion_v_val": float(v_disp),
        "dm_vs_persist": float(dm_stat),
        "dm_p_vs_persist": float(dm_p),
        "mean_d_mse_vs_persist": float(d_mp.mean()),
        "run_total_seconds": float(run_total_sec),
    }

def compute_epistemic_for_evalset(eval_set_id: int, seed_split: int, seed_models: list[int], H: int):
    files = []
    for sm in seed_models:
        tag_prefix = f"set{eval_set_id}_seedS{seed_split}_seedM{sm}_H{H}"
        p = NPZ_DIR / f"epi_moments_{tag_prefix}.npz"
        if p.exists():
            files.append(str(p))

    if len(files) < 2:
        print(f"Not enough models for epistemic on eval_set={eval_set_id} (found {len(files)}).")
        return

    mus = []
    vars_ = []
    for fp in files:
        d = np.load(fp)
        mus.append(d["mu"])
        vars_.append(d["var"])

    mus = np.stack(mus, axis=0)     # [M,N,H]
    vars_ = np.stack(vars_, axis=0) # [M,N,H]

    aleatoric = vars_.mean(axis=0)         # [N,H]
    epistemic = mus.var(axis=0, ddof=0)    # [N,H]
    total = aleatoric + epistemic
    frac = epistemic / (total + 1e-12)

    rows = []
    for h in range(H):
        rows.append({
            "eval_set_id": eval_set_id,
            "seed_split": seed_split,
            "h": h + 1,
            "aleatoric_mean": float(aleatoric[:, h].mean()),
            "epistemic_mean": float(epistemic[:, h].mean()),
            "epistemic_frac": float(frac[:, h].mean()),
        })

    df_epi = pd.DataFrame(rows)
    print("\nEpistemic decomposition (ensemble across seed_model):\n" + df_epi.to_string(index=False))

    save_table(df_epi, name=f"epistemic_evalset{eval_set_id}_seedS{seed_split}_H{H}")

    fig, ax = plt.subplots(figsize=(7, 3))
    ax.plot(df_epi["h"], df_epi["epistemic_frac"], marker="o")
    ax.set_title("Epistemic uncertainty fraction vs horizon")
    ax.set_xlabel("Horizon (months)")
    ax.set_ylabel("Epistemic / (total)")
    save_fig(fig, f"fig_r33_epistemic_frac_evalset{eval_set_id}_seedS{seed_split}_H{H}")


# ---------------- MAIN ----------------
def main(argv=None) -> None:
    args = parse_args(argv)

    seed_list = [int(s.strip()) for s in args.seeds.split(",") if s.strip() != ""]
    device = "cuda" if torch.cuda.is_available() else "cpu"

    print("=== Reproducibility (ENV) ==")
    print(f"Device: {device}")
    print(f"Torch: {torch.__version__} | NumPy: {np.__version__} | Pandas: {pd.__version__}")
    print(f"KAGGLE_DATASET_REF: {KAGGLE_DATASET_REF}")
    print(f"Seeds to run: {seed_list}")
    print("=============================")

    all_runs = []

    # Pre-pass: read the dataset once, build monthly + anomalies, to generate the disjoint sets
    df_raw_all = load_kaggle_dataset(KAGGLE_DATASET_REF, KAGGLE_FILE_PATH)
    df_raw_all = df_raw_all[df_raw_all["Year"] >= 1900].copy()
    y0_all, y1_all = probe_span(df_raw_all)

    monthly_all = aggregate_monthly(df_raw_all, y0_all, y1_all)
    monthly_all = exclude_incomplete_years(monthly_all, min_months=MIN_MONTHS_PER_YEAR)
    monthly_all = reindex_month_grid(monthly_all, y0_all, y1_all)

    train_end_all, val_end_all = split_years(y0_all, y1_all)
    monthly_all = build_anomalies_fixed_climatology(monthly_all, train_end=train_end_all)

    diagnose_eval_city_pool(
        df_raw_all,
        monthly_all,
        window=args.window,
        horizon=int(args.horizon),
        val_end=val_end_all,
        max_pchip_gap=MAX_PCHIP_GAP,
        min_test_windows=60,
    )

    # build eval_sets only once (here is the key for disjoint)
    if (EVAL_MODE == "fixed"):
        eval_sets = [list(EVAL_CITIES_FIXED)]
    else:
        eval_sets = build_eval_sets_disjoint(
            df_raw=df_raw_all,
            monthly=monthly_all,
            window=args.window,
            horizon=int(args.horizon),
            train_end=train_end_all,
            val_end=val_end_all,
            max_pchip_gap=MAX_PCHIP_GAP,
            n_eval_sets=int(args.n_eval_sets),
            n_eval=EVAL_N,
            seed_base=int(args.eval_seed_base),
            min_test_windows=60,
            enforce_disjoint=ENFORCE_DISJOINT_EVAL_SETS,
        )

    print("\n[DIAG] Eval sets (disjoint):")
    for i, s in enumerate(eval_sets):
        print(i, s)
    print("[DIAG] Unique eval cities total:",
          len({norm_city_name(c) for ss in eval_sets for c in ss}))

    del df_raw_all
    del monthly_all
    gc.collect()

    # Run: each eval set has its own seed_split, and inside you run 3 model seeds
    for set_id, eval_cities in enumerate(eval_sets):
        eval_seed = int(args.eval_seed_base + set_id)
        seed_split = int(args.split_seed_base + set_id)

        for seed_model in seed_list:
            metrics = run_once(
                args,
                seed_split=seed_split,
                seed_model=seed_model,
                device=device,
                eval_set_id=set_id,
                eval_seed=eval_seed,
                eval_cities=eval_cities,
            )
            all_runs.append(metrics)

        compute_epistemic_for_evalset(set_id, seed_split, seed_list, int(args.horizon))

    # Save raw runs
    df_runs = pd.DataFrame(all_runs)
    df_runs.to_csv("runs_all.csv", index=False)

    metric_keys = [
        "rmse_flat", "mae_flat", "nll_per_h", "energy_joint", "energy_ind",
        "pit_ks", "iw95", "cal_ae", "corr_offdiag", "crps_avg", "cov95_avg"
    ]

    # Aggregate per eval set (mean over model seeds)
    df_set = (
        df_runs.groupby("eval_set_id", as_index=False)[metric_keys]
        .mean()
        .sort_values("eval_set_id")
        .reset_index(drop=True)
    )
    df_set.to_csv("runs_by_evalset.csv", index=False)

    # Print distributions across eval sets
    if len(eval_sets) > 1:
        print("\n" + "#" * 70)
        print(f"EVAL-SET DISTRIBUTION (over {len(eval_sets)} different 10-city TEST sets)")
        print("#" * 70)

        for k in metric_keys:
            vals = df_set[k].to_numpy(dtype=np.float64)
            mu = float(vals.mean())
            sd = float(vals.std(ddof=1)) if len(vals) > 1 else 0.0
            print(f"{k}: {mu:.4f} \u00B1 {sd:.4f}")

        plt.figure()
        plt.boxplot(df_set["rmse_flat"].to_numpy(dtype=np.float64))
        plt.ylabel("RMSE (°C)")
        plt.title(f"RMSE across {len(eval_sets)} eval city sets (mean over model seeds)")
        plt.savefig("boxplot_rmse_evalsets.png", dpi=200, bbox_inches="tight")
        plt.close()

        plt.figure()
        plt.boxplot(df_set["energy_joint"].to_numpy(dtype=np.float64))
        plt.ylabel("EnergyScore (joint)")
        plt.title(f"EnergyScore across {len(eval_sets)} eval city sets (mean over model seeds)")
        plt.savefig("boxplot_energy_evalsets.png", dpi=200, bbox_inches="tight")
        plt.close()

    # Single-run final line
    if len(all_runs) == 1:
        r = all_runs[0]
        print("\nFINAL:")
        print(
            f"seed={r['seed_model']} | RMSE={r['rmse_flat']:.3f} | MAE={r['mae_flat']:.3f} | "
            f"NLL={r['nll_per_h']:.3f} | ES(joint)={r['energy_joint']:.3f} | PIT-KS={r['pit_ks']:.3f}"
        )

    # Zip everything in artifacts/ for easy download
    zip_path = zip_artifacts("artifacts.zip")

    # optional Colab download
    try:
        from google.colab import files
        files.download(zip_path)
    except Exception:
        print("[ART] Zip ready at:", zip_path)


if __name__ == "__main__":
    main()

=== Reproducibility (ENV) ==
Device: cuda
Torch: 2.6.0+cu124 | NumPy: 2.1.2 | Pandas: 2.3.3
KAGGLE_DATASET_REF: sudalairajkumar/daily-temperature-of-major-cities
Seeds to run: [42, 43, 44]
=============================

/tmp/ipython-input-199474976.py:214: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (1.0.0).
Downloading from https://www.kaggle.com/api/v1/datasets/download/sudalairajkumar/daily-temperature-of-major-cities?dataset_version_number=1&file_name=city_temperature.csv...

100%|██████████| 12.9M/12.9M [00:00<00:00, 50.6MB/s]

Extracting zip of city_temperature.csv...

/tmp/ipython-input-199474976.py:301: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  for city, g in monthly.groupby("City", sort=False):
/tmp/ipython-input-199474976.py:548: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  for city, g in monthly.groupby("City", sort=False):

[DIAG] Candidate cities with >= 60 TEST windows: 311
  - Africa: 27
  - Asia: 35
  - Australia/South Pacific: 6
  - Europe: 39
  - Middle East: 14
  - North America: 166
  - South/Central America & Carribean: 24

/tmp/ipython-input-199474976.py:454: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  for city, g in monthly.groupby("City", sort=False):
/tmp/ipython-input-199474976.py:454: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  for city, g in monthly.groupby("City", sort=False):
/tmp/ipython-input-199474976.py:454: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  for city, g in monthly.groupby("City", sort=False):
/tmp/ipython-input-199474976.py:454: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  for city, g in monthly.groupby("City", sort=False):
/tmp/ipython-input-199474976.py:454: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  for city, g in monthly.groupby("City", sort=False):

[DIAG] Eval sets (disjoint):
0 ['Addis Ababa', 'Hanoi', 'Sydney', 'Copenhagen', 'London', 'Beirut', 'Boston', 'Allentown', 'Brownsville', 'La Paz']
1 ['Bangui', 'Osaka', 'Canberra', 'Lisbon', 'Madrid', 'Amman', 'Albany', 'Buffalo', 'Billings', 'Tegucigalpa']
2 ['Banjul', 'Kuala Lumpur', 'Melbourne', 'Moscow', 'Oslo', 'Damascus', 'Akron Canton', 'Birmingham', 'Asheville', 'Paramaribo']
3 ['Dakar', 'Singapore', 'Brisbane', 'Budapest', 'Minsk', 'Abu Dhabi', 'Boise', 'Albuquerque', 'Cheyenne', 'Sao Paulo']
4 ['Lome', 'Tashkent', 'Ulan-bator', 'Auckland', 'Kiev', 'Kuwait', 'Cleveland', 'Cincinnati', 'Caribou', 'Panama City']
[DIAG] Unique eval cities total: 50

======================================================================
RUN | seed_split: 1000 | seed_model: 42 | device: cuda | H=6
======================================================================
[ART] saved figure: artifacts/figures/fig_r24_framework.png and artifacts/figures/fig_r24_framework.pdf

/tmp/ipython-input-199474976.py:214: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

Using Colab cache for faster access to the 'daily-temperature-of-major-cities' dataset.
[DIAG] Available years: 1995..2020, cities: 321
[DIAG] Time splits -> TRAIN<= 1999, VAL: 2000..2000, TEST: 2001..2020
[DIAG] Horizon H=6

/tmp/ipython-input-199474976.py:301: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  for city, g in monthly.groupby("City", sort=False):

[ART] saved figure: artifacts/figures/fig_r26_dataset_examples.png and artifacts/figures/fig_r26_dataset_examples.pdf
[DIAG] Eval set id: 0 | eval_seed: 123
[DIAG] Eval (TEST) cities: ['Addis Ababa', 'Hanoi', 'Sydney', 'Copenhagen', 'London', 'Beirut', 'Boston', 'Allentown', 'Brownsville', 'La Paz']
[DIAG] Geographic split -> TRAIN cities: 280, VAL cities: 31, TEST cities: 10

/tmp/ipython-input-199474976.py:674: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  for city, g in df.groupby("City", sort=False):

[DIAG] TRAIN samples: 11193
[DIAG] VAL samples: 207
[DIAG] TEST samples: 2177
[ART] saved TSLib NPZ: artifacts/npz/tslib_cityanom_set0_seedS1000_seedM42_H6_W12_H6.npz
Epoch   1/200 | Train Obj: 12.0036 | Val Obj: 10.4519 | LR: 0.000600
Epoch   2/200 | Train Obj: 10.2707 | Val Obj: 10.0316 | LR: 0.000900
Epoch   3/200 | Train Obj: 9.8056 | Val Obj: 9.9540 | LR: 0.001200
Epoch   4/200 | Train Obj: 9.6086 | Val Obj: 9.9160 | LR: 0.001500
Epoch   5/200 | Train Obj: 9.4536 | Val Obj: 9.8473 | LR: 0.001800
Epoch   6/200 | Train Obj: 9.2887 | Val Obj: 9.7019 | LR: 0.002100
Epoch   7/200 | Train Obj: 9.1780 | Val Obj: 9.7112 | LR: 0.002400
Epoch   8/200 | Train Obj: 9.0710 | Val Obj: 9.8510 | LR: 0.002700
Epoch   9/200 | Train Obj: 8.9781 | Val Obj: 9.8184 | LR: 0.003000
Epoch  10/200 | Train Obj: 8.8578 | Val Obj: 9.7861 | LR: 0.003000
Epoch  11/200 | Train Obj: 8.7255 | Val Obj: 9.8400 | LR: 0.003000
Epoch  12/200 | Train Obj: 8.5868 | Val Obj: 9.9967 | LR: 0.002999
Epoch  13/200 | Train Obj: 8.4566 | Val Obj: 10.0068 | LR: 0.002998
Epoch  14/200 | Train Obj: 8.3236 | Val Obj: 10.1922 | LR: 0.002997
Epoch  15/200 | Train Obj: 8.1962 | Val Obj: 10.1984 | LR: 0.002995
Epoch  16/200 | Train Obj: 8.0856 | Val Obj: 10.3036 | LR: 0.002993
Epoch  17/200 | Train Obj: 7.9722 | Val Obj: 10.3787 | LR: 0.002990
Epoch  18/200 | Train Obj: 7.8624 | Val Obj: 10.5723 | LR: 0.002987
Epoch  19/200 | Train Obj: 7.7614 | Val Obj: 10.4358 | LR: 0.002983
Epoch  20/200 | Train Obj: 7.6810 | Val Obj: 10.5167 | LR: 0.002980
Epoch  21/200 | Train Obj: 7.5735 | Val Obj: 10.6329 | LR: 0.002975
Epoch  22/200 | Train Obj: 7.5087 | Val Obj: 10.6437 | LR: 0.002971
Epoch  23/200 | Train Obj: 7.4246 | Val Obj: 10.6126 | LR: 0.002965
Epoch  24/200 | Train Obj: 7.3506 | Val Obj: 10.7395 | LR: 0.002960
Epoch  25/200 | Train Obj: 7.2784 | Val Obj: 10.7564 | LR: 0.002954
Epoch  26/200 | Train Obj: 7.1914 | Val Obj: 10.8022 | LR: 0.002948
Early stopping.
[ART] saved table: artifacts/tables/sign_mag_dependence_set0_seedS1000_seedM42_H6.csv and artifacts/tables/sign_mag_dependence_set0_seedS1000_seedM42_H6.tex
Epoch   1/200 | Train Obj: 11.9078 | Val Obj: 10.3570 | LR: 0.000600
Epoch   2/200 | Train Obj: 10.3119 | Val Obj: 10.0187 | LR: 0.000900
Epoch   3/200 | Train Obj: 9.9135 | Val Obj: 9.8881 | LR: 0.001200
Epoch   4/200 | Train Obj: 9.6900 | Val Obj: 9.8071 | LR: 0.001500
Epoch   5/200 | Train Obj: 9.5464 | Val Obj: 9.7352 | LR: 0.001800
Epoch   6/200 | Train Obj: 9.3926 | Val Obj: 9.6046 | LR: 0.002100
Epoch   7/200 | Train Obj: 9.3065 | Val Obj: 9.6615 | LR: 0.002400
Epoch   8/200 | Train Obj: 9.2229 | Val Obj: 9.7049 | LR: 0.002700
Epoch   9/200 | Train Obj: 9.1338 | Val Obj: 9.6707 | LR: 0.003000
Epoch  10/200 | Train Obj: 9.0323 | Val Obj: 9.7320 | LR: 0.003000
Epoch  11/200 | Train Obj: 8.9197 | Val Obj: 9.7897 | LR: 0.003000
Epoch  12/200 | Train Obj: 8.7768 | Val Obj: 9.8585 | LR: 0.002999
Epoch  13/200 | Train Obj: 8.6609 | Val Obj: 9.8813 | LR: 0.002998
Epoch  14/200 | Train Obj: 8.5289 | Val Obj: 9.8741 | LR: 0.002997
Epoch  15/200 | Train Obj: 8.4238 | Val Obj: 9.9216 | LR: 0.002995
Epoch  16/200 | Train Obj: 8.3051 | Val Obj: 9.9366 | LR: 0.002993
Epoch  17/200 | Train Obj: 8.1957 | Val Obj: 10.0428 | LR: 0.002990
Epoch  18/200 | Train Obj: 8.0978 | Val Obj: 10.0955 | LR: 0.002987
Epoch  19/200 | Train Obj: 7.9975 | Val Obj: 10.0643 | LR: 0.002983
Epoch  20/200 | Train Obj: 7.9029 | Val Obj: 10.2000 | LR: 0.002980
Epoch  21/200 | Train Obj: 7.8258 | Val Obj: 10.1537 | LR: 0.002975
Epoch  22/200 | Train Obj: 7.7543 | Val Obj: 10.1794 | LR: 0.002971
Epoch  23/200 | Train Obj: 7.6806 | Val Obj: 10.3542 | LR: 0.002965
Epoch  24/200 | Train Obj: 7.6195 | Val Obj: 10.2202 | LR: 0.002960
Epoch  25/200 | Train Obj: 7.5328 | Val Obj: 10.3876 | LR: 0.002954
Epoch  26/200 | Train Obj: 7.4832 | Val Obj: 10.4075 | LR: 0.002948
Early stopping.
[ART] saved table: artifacts/tables/signed_gamma_ablation.csv and artifacts/tables/signed_gamma_ablation.tex
[DM] Model vs Persist | DM=-15.117 | p=0 | mean(d)=-1.352989 (negative=better)
[MBB] block=6 | CI95(mean d_model-pers)=[-1.396979,-1.016198]
[MBB] block=12 | CI95(mean d_model-pers)=[-1.422153,-0.993314]
[MBB] block=24 | CI95(mean d_model-pers)=[-1.452373,-0.978863]
[MBB] block=6 | RMSE(flat) CI95=[1.355,1.486]
[MBB] block=12 | RMSE(flat) CI95=[1.342,1.501]
[MBB] block=24 | RMSE(flat) CI95=[1.327,1.514]

===== GLOBAL TEST (JOINT; TEST cities; years > VAL) =====
H=6 | RMSE(flat): 1.42 °C [1.39, 1.45] | MAE(flat): 1.04 °C [1.02, 1.07] | NLL(per-h): 1.6430 nats | EnergyScore(joint): 2.2365
AVG over horizons | RMSE: 1.42 | MAE: 1.04 | CRPS: 0.7549 | Cov@95(avg): 95.3%
Clim-0(flat)  | RMSE: 1.46 | MAE: 1.09
Persist(flat) | RMSE: 1.83 | MAE: 1.36
TinyTransformer(flat) | RMSE: 1.50 | MAE: 1.11 | train_sec: 6.3

----- Per-horizon summary (h=1..H) -----
h= 1 | RMSE=1.36 | MAE=1.00 | CRPS=0.7203 | Cov@95=95.6%
h= 2 | RMSE=1.42 | MAE=1.04 | CRPS=0.7535 | Cov@95=95.5%
h= 3 | RMSE=1.43 | MAE=1.05 | CRPS=0.7625 | Cov@95=96.4%
h= 4 | RMSE=1.43 | MAE=1.06 | CRPS=0.7624 | Cov@95=95.2%
h= 5 | RMSE=1.42 | MAE=1.05 | CRPS=0.7577 | Cov@95=95.1%
h= 6 | RMSE=1.44 | MAE=1.07 | CRPS=0.7730 | Cov@95=94.3%

----- Decade-wise (TEST; grouped by first horizon year) -----
2000s | N=1027 | RMSE(flat)=1.37 | MAE(flat)=1.01 | CRPS(avg)=0.7329 | Cov@95(avg)=95.3%
2010s | N=1150 | RMSE(flat)=1.46 | MAE(flat)=1.07 | CRPS(avg)=0.7746 | Cov@95(avg)=95.4%

----- Regime-wise (TEST; grouped by first horizon year ranges) -----
2001-2004 | N= 439 | RMSE(flat)=1.32 | MAE(flat)=0.99 | CRPS(avg)=0.7116 | Cov@95(avg)=95.8%
2005-2007 | N= 348 | RMSE(flat)=1.44 | MAE(flat)=1.06 | CRPS(avg)=0.7637 | Cov@95(avg)=95.3%
2008-2010 | N= 360 | RMSE(flat)=1.41 | MAE(flat)=1.03 | CRPS(avg)=0.7565 | Cov@95(avg)=94.4%
2011-2014 | N= 480 | RMSE(flat)=1.42 | MAE(flat)=1.03 | CRPS(avg)=0.7426 | Cov@95(avg)=95.9%
2015-2017 | N= 360 | RMSE(flat)=1.55 | MAE(flat)=1.14 | CRPS(avg)=0.8258 | Cov@95(avg)=94.8%
2018-2020 | N= 190 | RMSE(flat)=1.33 | MAE(flat)=1.00 | CRPS(avg)=0.7328 | Cov@95(avg)=95.9%

----- Per-city (eval cities; years > VAL) -----
       City                            Region  N_test_windows RMSE (°C) MAE (°C) NLL (per-h) CRPS (°C)  CIA95 Cov@50 Cov@90 Cov@95  N_windows_in_test DM_vs_Persist      DM_p
Addis Ababa                            Africa             170      0.80     0.61      1.1554    0.4500 98.35%  48.9%  92.5%  96.6%                170        -3.039  0.002747
      Hanoi                              Asia             223      1.23     0.90      1.5008    0.6500 98.51%  47.8%  93.7%  96.4%                223        -6.323 1.395e-09
     Sydney           Australia/South Pacific             223      1.32     1.01      1.6901    0.7393 98.90%  43.7%  90.9%  95.1%                223        -6.452 6.825e-10
 Copenhagen                            Europe             223      1.88     1.47      2.0708    1.0551 97.37%  40.1%  85.4%  92.8%                223        -9.983         0
     London                            Europe             223      1.46     1.14      1.8058    0.8185 99.24%  43.6%  89.2%  95.4%                223        -7.173  1.08e-11
     Beirut                       Middle East             223      1.07     0.83      1.4652    0.6103 99.55%  44.2%  88.5%  94.9%                223        -4.377 1.851e-05
     Boston                     North America             223      1.74     1.33      1.9608    0.9595 98.47%  41.9%  86.7%  93.9%                223        -6.346 1.228e-09
  Allentown                     North America             223      1.94     1.50      2.0766    1.0787 97.45%  37.1%  85.6%  92.6%                223        -7.068 2.007e-11
Brownsville                     North America             223      1.36     1.03      1.6576    0.7430 98.04%  46.6%  90.5%  96.9%                223        -7.338 4.032e-12
     La Paz South/Central America & Carribean             223      0.64     0.51      0.9309    0.3722 95.68%  49.0%  95.3%  99.1%                223        -4.124 5.269e-05

[DM] Per-city summary | significant(p<0.05): 10/10 | Fisher combined p=0

======================================================================
RUN | seed_split: 1000 | seed_model: 43 | device: cuda | H=6
======================================================================

/tmp/ipython-input-199474976.py:214: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

Using Colab cache for faster access to the 'daily-temperature-of-major-cities' dataset.
[DIAG] Available years: 1995..2020, cities: 321
[DIAG] Time splits -> TRAIN<= 1999, VAL: 2000..2000, TEST: 2001..2020
[DIAG] Horizon H=6

/tmp/ipython-input-199474976.py:301: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  for city, g in monthly.groupby("City", sort=False):

[DIAG] Eval set id: 0 | eval_seed: 123
[DIAG] Eval (TEST) cities: ['Addis Ababa', 'Hanoi', 'Sydney', 'Copenhagen', 'London', 'Beirut', 'Boston', 'Allentown', 'Brownsville', 'La Paz']
[DIAG] Geographic split -> TRAIN cities: 280, VAL cities: 31, TEST cities: 10

/tmp/ipython-input-199474976.py:674: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  for city, g in df.groupby("City", sort=False):

[DIAG] TRAIN samples: 11193
[DIAG] VAL samples: 207
[DIAG] TEST samples: 2177
[ART] saved TSLib NPZ: artifacts/npz/tslib_cityanom_set0_seedS1000_seedM43_H6_W12_H6.npz
Epoch   1/200 | Train Obj: 11.9447 | Val Obj: 10.3391 | LR: 0.000600
Epoch   2/200 | Train Obj: 10.2777 | Val Obj: 10.0825 | LR: 0.000900
Epoch   3/200 | Train Obj: 9.7846 | Val Obj: 10.0100 | LR: 0.001200
Epoch   4/200 | Train Obj: 9.6158 | Val Obj: 9.9245 | LR: 0.001500
Epoch   5/200 | Train Obj: 9.4575 | Val Obj: 9.9390 | LR: 0.001800
Epoch   6/200 | Train Obj: 9.3302 | Val Obj: 9.6918 | LR: 0.002100
Epoch   7/200 | Train Obj: 9.2135 | Val Obj: 9.6493 | LR: 0.002400
Epoch   8/200 | Train Obj: 9.1014 | Val Obj: 9.6496 | LR: 0.002700
Epoch   9/200 | Train Obj: 8.9860 | Val Obj: 9.7783 | LR: 0.003000
Epoch  10/200 | Train Obj: 8.8596 | Val Obj: 9.9360 | LR: 0.003000
Epoch  11/200 | Train Obj: 8.7075 | Val Obj: 9.8103 | LR: 0.003000
Epoch  12/200 | Train Obj: 8.5835 | Val Obj: 10.0021 | LR: 0.002999
Epoch  13/200 | Train Obj: 8.4353 | Val Obj: 10.0030 | LR: 0.002998
Epoch  14/200 | Train Obj: 8.2945 | Val Obj: 10.0994 | LR: 0.002997
Epoch  15/200 | Train Obj: 8.1656 | Val Obj: 10.1378 | LR: 0.002995
Epoch  16/200 | Train Obj: 8.0190 | Val Obj: 10.2435 | LR: 0.002993
Epoch  17/200 | Train Obj: 7.9187 | Val Obj: 10.2908 | LR: 0.002990
Epoch  18/200 | Train Obj: 7.8108 | Val Obj: 10.3813 | LR: 0.002987
Epoch  19/200 | Train Obj: 7.7077 | Val Obj: 10.4856 | LR: 0.002983
Epoch  20/200 | Train Obj: 7.6041 | Val Obj: 10.5830 | LR: 0.002980
Epoch  21/200 | Train Obj: 7.5243 | Val Obj: 10.5191 | LR: 0.002975
Epoch  22/200 | Train Obj: 7.4425 | Val Obj: 10.4981 | LR: 0.002971
Epoch  23/200 | Train Obj: 7.3603 | Val Obj: 10.6425 | LR: 0.002965
Epoch  24/200 | Train Obj: 7.2763 | Val Obj: 10.7226 | LR: 0.002960
Epoch  25/200 | Train Obj: 7.2012 | Val Obj: 10.6463 | LR: 0.002954
Epoch  26/200 | Train Obj: 7.1161 | Val Obj: 10.8201 | LR: 0.002948
Epoch  27/200 | Train Obj: 7.0585 | Val Obj: 10.8337 | LR: 0.002941
Early stopping.
[ART] saved table: artifacts/tables/sign_mag_dependence_set0_seedS1000_seedM43_H6.csv and artifacts/tables/sign_mag_dependence_set0_seedS1000_seedM43_H6.tex
[DM] Model vs Persist | DM=-15.297 | p=0 | mean(d)=-1.353938 (negative=better)
[MBB] block=6 | CI95(mean d_model-pers)=[-1.411535,-0.997826]
[MBB] block=12 | CI95(mean d_model-pers)=[-1.411113,-0.990668]
[MBB] block=24 | CI95(mean d_model-pers)=[-1.427993,-0.972212]
[MBB] block=6 | RMSE(flat) CI95=[1.351,1.484]
[MBB] block=12 | RMSE(flat) CI95=[1.341,1.493]
[MBB] block=24 | RMSE(flat) CI95=[1.332,1.508]

===== GLOBAL TEST (JOINT; TEST cities; years > VAL) =====
H=6 | RMSE(flat): 1.42 °C [1.38, 1.45] | MAE(flat): 1.04 °C [1.02, 1.06] | NLL(per-h): 1.6400 nats | EnergyScore(joint): 2.2300
AVG over horizons | RMSE: 1.42 | MAE: 1.04 | CRPS: 0.7542 | Cov@95(avg): 95.1%
Clim-0(flat)  | RMSE: 1.46 | MAE: 1.09
Persist(flat) | RMSE: 1.83 | MAE: 1.36
TinyTransformer(flat) | RMSE: 1.50 | MAE: 1.11 | train_sec: 7.1

----- Per-horizon summary (h=1..H) -----
h= 1 | RMSE=1.36 | MAE=1.00 | CRPS=0.7235 | Cov@95=95.4%
h= 2 | RMSE=1.42 | MAE=1.03 | CRPS=0.7498 | Cov@95=96.1%
h= 3 | RMSE=1.44 | MAE=1.05 | CRPS=0.7630 | Cov@95=94.3%
h= 4 | RMSE=1.44 | MAE=1.06 | CRPS=0.7642 | Cov@95=94.6%
h= 5 | RMSE=1.41 | MAE=1.04 | CRPS=0.7549 | Cov@95=95.6%
h= 6 | RMSE=1.43 | MAE=1.06 | CRPS=0.7697 | Cov@95=94.4%

----- Decade-wise (TEST; grouped by first horizon year) -----
2000s | N=1027 | RMSE(flat)=1.37 | MAE(flat)=1.01 | CRPS(avg)=0.7341 | Cov@95(avg)=95.1%
2010s | N=1150 | RMSE(flat)=1.46 | MAE(flat)=1.06 | CRPS(avg)=0.7721 | Cov@95(avg)=95.1%

----- Regime-wise (TEST; grouped by first horizon year ranges) -----
2001-2004 | N= 439 | RMSE(flat)=1.32 | MAE(flat)=0.98 | CRPS(avg)=0.7094 | Cov@95(avg)=95.4%
2005-2007 | N= 348 | RMSE(flat)=1.46 | MAE(flat)=1.07 | CRPS(avg)=0.7717 | Cov@95(avg)=95.0%
2008-2010 | N= 360 | RMSE(flat)=1.42 | MAE(flat)=1.03 | CRPS(avg)=0.7569 | Cov@95(avg)=94.1%
2011-2014 | N= 480 | RMSE(flat)=1.41 | MAE(flat)=1.03 | CRPS(avg)=0.7421 | Cov@95(avg)=95.5%
2015-2017 | N= 360 | RMSE(flat)=1.54 | MAE(flat)=1.13 | CRPS(avg)=0.8217 | Cov@95(avg)=95.0%
2018-2020 | N= 190 | RMSE(flat)=1.32 | MAE(flat)=0.99 | CRPS(avg)=0.7230 | Cov@95(avg)=95.6%

----- Per-city (eval cities; years > VAL) -----
       City                            Region  N_test_windows RMSE (°C) MAE (°C) NLL (per-h) CRPS (°C)  CIA95 Cov@50 Cov@90 Cov@95  N_windows_in_test DM_vs_Persist      DM_p
Addis Ababa                            Africa             170      0.77     0.59      1.1278    0.4334 97.01%  48.4%  93.1%  97.8%                170        -3.548 0.0005025
      Hanoi                              Asia             223      1.23     0.90      1.4976    0.6498 98.12%  45.3%  93.6%  96.8%                223        -6.443 7.187e-10
     Sydney           Australia/South Pacific             223      1.30     1.00      1.6757    0.7299 99.24%  40.8%  91.0%  95.6%                223        -6.829 8.069e-11
 Copenhagen                            Europe             223      1.88     1.47      2.0859    1.0607 95.90%  37.3%  84.7%  91.1%                223        -9.568         0
     London                            Europe             223      1.47     1.15      1.8191    0.8247 99.64%  40.3%  89.2%  95.2%                223        -7.012 2.792e-11
     Beirut                       Middle East             223      1.07     0.83      1.4434    0.6050 98.69%  42.8%  89.3%  95.5%                223        -4.992 1.206e-06
     Boston                     North America             223      1.75     1.33      1.9772    0.9664 97.47%  37.7%  84.3%  92.6%                223        -6.302 1.565e-09
  Allentown                     North America             223      1.96     1.52      2.1122    1.0980 95.67%  33.9%  83.6%  90.9%                223        -6.932 4.459e-11
Brownsville                     North America             223      1.35     1.03      1.6443    0.7432 98.12%  44.8%  90.2%  96.8%                223        -7.484 1.669e-12
     La Paz South/Central America & Carribean             223      0.61     0.48      0.8947    0.3546 95.68%  51.6%  96.1%  99.1%                223        -6.176 3.106e-09

[DM] Per-city summary | significant(p<0.05): 10/10 | Fisher combined p=0

======================================================================
RUN | seed_split: 1000 | seed_model: 44 | device: cuda | H=6
======================================================================

/tmp/ipython-input-199474976.py:214: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

Using Colab cache for faster access to the 'daily-temperature-of-major-cities' dataset.
[DIAG] Available years: 1995..2020, cities: 321
[DIAG] Time splits -> TRAIN<= 1999, VAL: 2000..2000, TEST: 2001..2020
[DIAG] Horizon H=6

/tmp/ipython-input-199474976.py:301: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  for city, g in monthly.groupby("City", sort=False):

[DIAG] Eval set id: 0 | eval_seed: 123
[DIAG] Eval (TEST) cities: ['Addis Ababa', 'Hanoi', 'Sydney', 'Copenhagen', 'London', 'Beirut', 'Boston', 'Allentown', 'Brownsville', 'La Paz']
[DIAG] Geographic split -> TRAIN cities: 280, VAL cities: 31, TEST cities: 10

/tmp/ipython-input-199474976.py:674: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  for city, g in df.groupby("City", sort=False):

[DIAG] TRAIN samples: 11193
[DIAG] VAL samples: 207
[DIAG] TEST samples: 2177
[ART] saved TSLib NPZ: artifacts/npz/tslib_cityanom_set0_seedS1000_seedM44_H6_W12_H6.npz
Epoch   1/200 | Train Obj: 12.1440 | Val Obj: 10.7735 | LR: 0.000600
Epoch   2/200 | Train Obj: 10.3162 | Val Obj: 10.0639 | LR: 0.000900
Epoch   3/200 | Train Obj: 9.7861 | Val Obj: 10.0838 | LR: 0.001200
Epoch   4/200 | Train Obj: 9.6239 | Val Obj: 9.9798 | LR: 0.001500
Epoch   5/200 | Train Obj: 9.4552 | Val Obj: 9.8796 | LR: 0.001800
Epoch   6/200 | Train Obj: 9.3090 | Val Obj: 9.7763 | LR: 0.002100
Epoch   7/200 | Train Obj: 9.1965 | Val Obj: 9.8373 | LR: 0.002400
Epoch   8/200 | Train Obj: 9.0926 | Val Obj: 9.8949 | LR: 0.002700
Epoch   9/200 | Train Obj: 8.9985 | Val Obj: 9.9458 | LR: 0.003000
Epoch  10/200 | Train Obj: 8.8880 | Val Obj: 9.9912 | LR: 0.003000
Epoch  11/200 | Train Obj: 8.7666 | Val Obj: 10.0432 | LR: 0.003000
Epoch  12/200 | Train Obj: 8.6312 | Val Obj: 10.1198 | LR: 0.002999
Epoch  13/200 | Train Obj: 8.4927 | Val Obj: 10.2186 | LR: 0.002998
Epoch  14/200 | Train Obj: 8.3382 | Val Obj: 10.4025 | LR: 0.002997
Epoch  15/200 | Train Obj: 8.2414 | Val Obj: 10.3605 | LR: 0.002995
Epoch  16/200 | Train Obj: 8.1022 | Val Obj: 10.3230 | LR: 0.002993
Epoch  17/200 | Train Obj: 7.9943 | Val Obj: 10.4139 | LR: 0.002990
Epoch  18/200 | Train Obj: 7.8900 | Val Obj: 10.3884 | LR: 0.002987
Epoch  19/200 | Train Obj: 7.7861 | Val Obj: 10.3925 | LR: 0.002983
Epoch  20/200 | Train Obj: 7.7091 | Val Obj: 10.4770 | LR: 0.002980
Epoch  21/200 | Train Obj: 7.6135 | Val Obj: 10.5651 | LR: 0.002975
Epoch  22/200 | Train Obj: 7.5247 | Val Obj: 10.7414 | LR: 0.002971
Epoch  23/200 | Train Obj: 7.4327 | Val Obj: 10.6899 | LR: 0.002965
Epoch  24/200 | Train Obj: 7.3823 | Val Obj: 10.7368 | LR: 0.002960
Epoch  25/200 | Train Obj: 7.2957 | Val Obj: 10.7526 | LR: 0.002954
Epoch  26/200 | Train Obj: 7.2226 | Val Obj: 10.8522 | LR: 0.002948
Early stopping.
[ART] saved table: artifacts/tables/sign_mag_dependence_set0_seedS1000_seedM44_H6.csv and artifacts/tables/sign_mag_dependence_set0_seedS1000_seedM44_H6.tex
[DM] Model vs Persist | DM=-14.721 | p=0 | mean(d)=-1.311379 (negative=better)
[MBB] block=6 | CI95(mean d_model-pers)=[-1.389724,-0.995355]
[MBB] block=12 | CI95(mean d_model-pers)=[-1.403525,-0.984872]
[MBB] block=24 | CI95(mean d_model-pers)=[-1.426697,-0.978062]
[MBB] block=6 | RMSE(flat) CI95=[1.370,1.496]
[MBB] block=12 | RMSE(flat) CI95=[1.355,1.517]
[MBB] block=24 | RMSE(flat) CI95=[1.336,1.524]

===== GLOBAL TEST (JOINT; TEST cities; years > VAL) =====
H=6 | RMSE(flat): 1.43 °C [1.40, 1.46] | MAE(flat): 1.05 °C [1.03, 1.08] | NLL(per-h): 1.6488 nats | EnergyScore(joint): 2.2548
AVG over horizons | RMSE: 1.43 | MAE: 1.05 | CRPS: 0.7709 | Cov@95(avg): 95.4%
Clim-0(flat)  | RMSE: 1.46 | MAE: 1.09
Persist(flat) | RMSE: 1.83 | MAE: 1.36
TinyTransformer(flat) | RMSE: 1.50 | MAE: 1.11 | train_sec: 6.7

----- Per-horizon summary (h=1..H) -----
h= 1 | RMSE=1.39 | MAE=1.02 | CRPS=0.7498 | Cov@95=95.5%
h= 2 | RMSE=1.44 | MAE=1.05 | CRPS=0.7688 | Cov@95=95.5%
h= 3 | RMSE=1.46 | MAE=1.07 | CRPS=0.7828 | Cov@95=94.7%
h= 4 | RMSE=1.44 | MAE=1.06 | CRPS=0.7752 | Cov@95=95.4%
h= 5 | RMSE=1.43 | MAE=1.06 | CRPS=0.7703 | Cov@95=96.0%
h= 6 | RMSE=1.44 | MAE=1.07 | CRPS=0.7784 | Cov@95=95.5%

----- Decade-wise (TEST; grouped by first horizon year) -----
2000s | N=1027 | RMSE(flat)=1.37 | MAE(flat)=1.02 | CRPS(avg)=0.7421 | Cov@95(avg)=95.5%
2010s | N=1150 | RMSE(flat)=1.48 | MAE(flat)=1.09 | CRPS(avg)=0.7966 | Cov@95(avg)=95.4%

----- Regime-wise (TEST; grouped by first horizon year ranges) -----
2001-2004 | N= 439 | RMSE(flat)=1.32 | MAE(flat)=0.99 | CRPS(avg)=0.7146 | Cov@95(avg)=95.7%
2005-2007 | N= 348 | RMSE(flat)=1.46 | MAE(flat)=1.07 | CRPS(avg)=0.7818 | Cov@95(avg)=95.1%
2008-2010 | N= 360 | RMSE(flat)=1.42 | MAE(flat)=1.04 | CRPS(avg)=0.7657 | Cov@95(avg)=95.0%
2011-2014 | N= 480 | RMSE(flat)=1.42 | MAE(flat)=1.04 | CRPS(avg)=0.7560 | Cov@95(avg)=95.9%
2015-2017 | N= 360 | RMSE(flat)=1.58 | MAE(flat)=1.16 | CRPS(avg)=0.8503 | Cov@95(avg)=95.2%
2018-2020 | N= 190 | RMSE(flat)=1.40 | MAE(flat)=1.04 | CRPS(avg)=0.7781 | Cov@95(avg)=95.4%

----- Per-city (eval cities; years > VAL) -----
       City                            Region  N_test_windows RMSE (°C) MAE (°C) NLL (per-h) CRPS (°C)  CIA95 Cov@50 Cov@90 Cov@95  N_windows_in_test DM_vs_Persist      DM_p
Addis Ababa                            Africa             170      0.79     0.60      1.1293    0.4472 97.11%  40.8%  93.9%  97.7%                170        -3.271  0.001299
      Hanoi                              Asia             223      1.22     0.89      1.4858    0.6479 97.81%  40.7%  93.8%  97.1%                223        -6.376  1.04e-09
     Sydney           Australia/South Pacific             223      1.36     1.04      1.7013    0.7751 99.37%  34.6%  89.2%  94.8%                223        -5.747 2.979e-08
 Copenhagen                            Europe             223      1.93     1.51      2.1099    1.1029 97.00%  34.0%  83.6%  92.2%                223        -8.192 2.021e-14
     London                            Europe             223      1.46     1.13      1.8163    0.8235 99.32%  37.0%  88.4%  95.4%                223        -7.192 9.665e-12
     Beirut                       Middle East             223      1.09     0.85      1.4661    0.6285 98.85%  36.8%  87.7%  96.0%                223        -4.115  5.46e-05
     Boston                     North America             223      1.74     1.32      1.9851    0.9705 98.42%  37.1%  84.2%  93.5%                223        -6.429 7.745e-10
  Allentown                     North America             223      1.97     1.53      2.0999    1.1065 96.53%  30.6%  82.2%  91.7%                223        -7.031 2.495e-11
Brownsville                     North America             223      1.37     1.05      1.6636    0.7622 98.43%  37.2%  89.5%  96.5%                223        -6.757 1.219e-10
     La Paz South/Central America & Carribean             223      0.63     0.50      0.9071    0.3678 94.74%  41.6%  96.9% 100.0%                223        -4.831 2.529e-06

[DM] Per-city summary | significant(p<0.05): 10/10 | Fisher combined p=0
Not enough models for epistemic on eval_set=0 (found 0).

======================================================================
RUN | seed_split: 1001 | seed_model: 42 | device: cuda | H=6
======================================================================

/tmp/ipython-input-199474976.py:214: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

Using Colab cache for faster access to the 'daily-temperature-of-major-cities' dataset.
[DIAG] Available years: 1995..2020, cities: 321
[DIAG] Time splits -> TRAIN<= 1999, VAL: 2000..2000, TEST: 2001..2020
[DIAG] Horizon H=6

/tmp/ipython-input-199474976.py:301: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  for city, g in monthly.groupby("City", sort=False):

[DIAG] Eval set id: 1 | eval_seed: 124
[DIAG] Eval (TEST) cities: ['Bangui', 'Osaka', 'Canberra', 'Lisbon', 'Madrid', 'Amman', 'Albany', 'Buffalo', 'Billings', 'Tegucigalpa']
[DIAG] Geographic split -> TRAIN cities: 280, VAL cities: 31, TEST cities: 10

/tmp/ipython-input-199474976.py:674: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  for city, g in df.groupby("City", sort=False):

[DIAG] TRAIN samples: 11347
[DIAG] VAL samples: 189
[DIAG] TEST samples: 2230
[ART] saved TSLib NPZ: artifacts/npz/tslib_cityanom_set1_seedS1001_seedM42_H6_W12_H6.npz
Epoch   1/200 | Train Obj: 11.8287 | Val Obj: 11.4405 | LR: 0.000600
Epoch   2/200 | Train Obj: 10.1251 | Val Obj: 10.8608 | LR: 0.000900
Epoch   3/200 | Train Obj: 9.6864 | Val Obj: 10.7775 | LR: 0.001200
Epoch   4/200 | Train Obj: 9.4847 | Val Obj: 10.8132 | LR: 0.001500
Epoch   5/200 | Train Obj: 9.3171 | Val Obj: 10.6768 | LR: 0.001800
Epoch   6/200 | Train Obj: 9.1724 | Val Obj: 10.6052 | LR: 0.002100
Epoch   7/200 | Train Obj: 9.0541 | Val Obj: 10.4309 | LR: 0.002400
Epoch   8/200 | Train Obj: 8.9560 | Val Obj: 10.6615 | LR: 0.002700
Epoch   9/200 | Train Obj: 8.8621 | Val Obj: 10.5538 | LR: 0.003000
Epoch  10/200 | Train Obj: 8.7324 | Val Obj: 10.5982 | LR: 0.003000
Epoch  11/200 | Train Obj: 8.6153 | Val Obj: 10.8036 | LR: 0.003000
Epoch  12/200 | Train Obj: 8.4668 | Val Obj: 10.7739 | LR: 0.002999
Epoch  13/200 | Train Obj: 8.3480 | Val Obj: 10.8665 | LR: 0.002998
Epoch  14/200 | Train Obj: 8.2200 | Val Obj: 11.0873 | LR: 0.002997
Epoch  15/200 | Train Obj: 8.0976 | Val Obj: 11.0464 | LR: 0.002995
Epoch  16/200 | Train Obj: 7.9670 | Val Obj: 11.1871 | LR: 0.002993
Epoch  17/200 | Train Obj: 7.8727 | Val Obj: 11.1879 | LR: 0.002990
Epoch  18/200 | Train Obj: 7.7621 | Val Obj: 11.4820 | LR: 0.002987
Epoch  19/200 | Train Obj: 7.6402 | Val Obj: 11.4509 | LR: 0.002983
Epoch  20/200 | Train Obj: 7.5609 | Val Obj: 11.4354 | LR: 0.002980
Epoch  21/200 | Train Obj: 7.4480 | Val Obj: 11.5039 | LR: 0.002975
Epoch  22/200 | Train Obj: 7.3711 | Val Obj: 11.4873 | LR: 0.002971
Epoch  23/200 | Train Obj: 7.2942 | Val Obj: 11.6440 | LR: 0.002965
Epoch  24/200 | Train Obj: 7.2096 | Val Obj: 11.5335 | LR: 0.002960
Epoch  25/200 | Train Obj: 7.1504 | Val Obj: 11.6945 | LR: 0.002954
Epoch  26/200 | Train Obj: 7.0780 | Val Obj: 11.5117 | LR: 0.002948
Epoch  27/200 | Train Obj: 7.0054 | Val Obj: 11.7389 | LR: 0.002941
Early stopping.
[ART] saved table: artifacts/tables/sign_mag_dependence_set1_seedS1001_seedM42_H6.csv and artifacts/tables/sign_mag_dependence_set1_seedS1001_seedM42_H6.tex
[DM] Model vs Persist | DM=-10.996 | p=0 | mean(d)=-1.940483 (negative=better)
[MBB] block=6 | CI95(mean d_model-pers)=[-2.124097,-1.396266]
[MBB] block=12 | CI95(mean d_model-pers)=[-2.174230,-1.353215]
[MBB] block=24 | CI95(mean d_model-pers)=[-2.311744,-1.300148]
[MBB] block=6 | RMSE(flat) CI95=[1.596,1.773]
[MBB] block=12 | RMSE(flat) CI95=[1.585,1.789]
[MBB] block=24 | RMSE(flat) CI95=[1.553,1.823]

===== GLOBAL TEST (JOINT; TEST cities; years > VAL) =====
H=6 | RMSE(flat): 1.68 °C [1.64, 1.73] | MAE(flat): 1.22 °C [1.20, 1.25] | NLL(per-h): 1.7893 nats | EnergyScore(joint): 2.5996
AVG over horizons | RMSE: 1.68 | MAE: 1.22 | CRPS: 0.8924 | Cov@95(avg): 96.3%
Clim-0(flat)  | RMSE: 1.70 | MAE: 1.24
Persist(flat) | RMSE: 2.19 | MAE: 1.57
TinyTransformer(flat) | RMSE: 1.70 | MAE: 1.24 | train_sec: 5.4

----- Per-horizon summary (h=1..H) -----
h= 1 | RMSE=1.63 | MAE=1.17 | CRPS=0.8639 | Cov@95=95.4%
h= 2 | RMSE=1.67 | MAE=1.21 | CRPS=0.8822 | Cov@95=96.3%
h= 3 | RMSE=1.71 | MAE=1.24 | CRPS=0.9050 | Cov@95=96.6%
h= 4 | RMSE=1.71 | MAE=1.24 | CRPS=0.8991 | Cov@95=96.9%
h= 5 | RMSE=1.69 | MAE=1.23 | CRPS=0.8999 | Cov@95=96.6%
h= 6 | RMSE=1.69 | MAE=1.24 | CRPS=0.9046 | Cov@95=95.8%

----- Decade-wise (TEST; grouped by first horizon year) -----
2000s | N=1080 | RMSE(flat)=1.59 | MAE(flat)=1.17 | CRPS(avg)=0.8502 | Cov@95(avg)=96.9%
2010s | N=1150 | RMSE(flat)=1.77 | MAE(flat)=1.27 | CRPS(avg)=0.9321 | Cov@95(avg)=95.7%

----- Regime-wise (TEST; grouped by first horizon year ranges) -----
2001-2004 | N= 480 | RMSE(flat)=1.57 | MAE(flat)=1.15 | CRPS(avg)=0.8269 | Cov@95(avg)=97.2%
2005-2007 | N= 360 | RMSE(flat)=1.61 | MAE(flat)=1.20 | CRPS(avg)=0.8691 | Cov@95(avg)=97.0%
2008-2010 | N= 360 | RMSE(flat)=1.62 | MAE(flat)=1.19 | CRPS(avg)=0.8783 | Cov@95(avg)=96.1%
2011-2014 | N= 480 | RMSE(flat)=1.67 | MAE(flat)=1.20 | CRPS(avg)=0.8765 | Cov@95(avg)=96.0%
2015-2017 | N= 360 | RMSE(flat)=1.85 | MAE(flat)=1.36 | CRPS(avg)=1.0009 | Cov@95(avg)=95.0%
2018-2020 | N= 190 | RMSE(flat)=1.92 | MAE(flat)=1.31 | CRPS(avg)=0.9636 | Cov@95(avg)=96.2%

----- Per-city (eval cities; years > VAL) -----
       City                            Region  N_test_windows RMSE (°C) MAE (°C) NLL (per-h) CRPS (°C)  CIA95 Cov@50 Cov@90 Cov@95  N_windows_in_test DM_vs_Persist      DM_p
     Bangui                            Africa             223      0.59     0.45      0.8400    0.3337 95.13%  42.8%  96.3%  99.6%                223        -5.056 8.936e-07
      Osaka                              Asia             223      1.33     1.09      1.7716    0.8220 98.04%  29.4%  89.9%  96.9%                223        -2.181   0.03026
   Canberra           Australia/South Pacific             223      1.40     1.08      1.7465    0.7972 97.88%  36.5%  91.6%  97.0%                223        -9.345         0
     Lisbon                            Europe             223      1.47     1.22      1.7538    0.8579 95.52%  26.6%  92.8%  99.3%                223        -5.737  3.14e-08
     Madrid                            Europe             223      1.75     1.44      1.9894    1.0297 98.90%  26.6%  84.4%  95.1%                223        -7.619 7.312e-13
      Amman                       Middle East             223      1.57     1.23      1.9189    0.8890 98.36%  36.3%  89.7%  96.6%                223        -8.084 4.019e-14
     Albany                     North America             223      2.02     1.56      2.1226    1.1329 98.74%  30.1%  86.2%  95.1%                223        -6.973 3.511e-11
    Buffalo                     North America             223      2.11     1.62      2.1855    1.1750 99.06%  30.7%  85.9%  95.1%                223        -7.661 5.653e-13
   Billings                     North America             223      2.76     2.01      2.6072    1.5001 94.25%  29.7%  80.8%  89.5%                223        -6.189 2.894e-09
Tegucigalpa South/Central America & Carribean             223      0.67     0.52      0.9574    0.3868 96.00%  36.5%  96.7%  98.8%                223        -3.669 0.0003051

[DM] Per-city summary | significant(p<0.05): 10/10 | Fisher combined p=0

======================================================================
RUN | seed_split: 1001 | seed_model: 43 | device: cuda | H=6
======================================================================

/tmp/ipython-input-199474976.py:214: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

Using Colab cache for faster access to the 'daily-temperature-of-major-cities' dataset.
[DIAG] Available years: 1995..2020, cities: 321
[DIAG] Time splits -> TRAIN<= 1999, VAL: 2000..2000, TEST: 2001..2020
[DIAG] Horizon H=6

/tmp/ipython-input-199474976.py:301: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  for city, g in monthly.groupby("City", sort=False):

[DIAG] Eval set id: 1 | eval_seed: 124
[DIAG] Eval (TEST) cities: ['Bangui', 'Osaka', 'Canberra', 'Lisbon', 'Madrid', 'Amman', 'Albany', 'Buffalo', 'Billings', 'Tegucigalpa']
[DIAG] Geographic split -> TRAIN cities: 280, VAL cities: 31, TEST cities: 10

/tmp/ipython-input-199474976.py:674: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  for city, g in df.groupby("City", sort=False):

[DIAG] TRAIN samples: 11347
[DIAG] VAL samples: 189
[DIAG] TEST samples: 2230
[ART] saved TSLib NPZ: artifacts/npz/tslib_cityanom_set1_seedS1001_seedM43_H6_W12_H6.npz
Epoch   1/200 | Train Obj: 11.7868 | Val Obj: 11.3362 | LR: 0.000600
Epoch   2/200 | Train Obj: 10.1013 | Val Obj: 10.9376 | LR: 0.000900
Epoch   3/200 | Train Obj: 9.6596 | Val Obj: 10.8984 | LR: 0.001200
Epoch   4/200 | Train Obj: 9.4991 | Val Obj: 10.7653 | LR: 0.001500
Epoch   5/200 | Train Obj: 9.3595 | Val Obj: 10.5425 | LR: 0.001800
Epoch   6/200 | Train Obj: 9.2310 | Val Obj: 10.5746 | LR: 0.002100
Epoch   7/200 | Train Obj: 9.0923 | Val Obj: 10.6090 | LR: 0.002400
Epoch   8/200 | Train Obj: 8.9922 | Val Obj: 10.3532 | LR: 0.002700
Epoch   9/200 | Train Obj: 8.8948 | Val Obj: 10.6328 | LR: 0.003000
Epoch  10/200 | Train Obj: 8.7504 | Val Obj: 10.8354 | LR: 0.003000
Epoch  11/200 | Train Obj: 8.6169 | Val Obj: 10.7315 | LR: 0.003000
Epoch  12/200 | Train Obj: 8.4625 | Val Obj: 10.7584 | LR: 0.002999
Epoch  13/200 | Train Obj: 8.3136 | Val Obj: 10.9811 | LR: 0.002998
Epoch  14/200 | Train Obj: 8.1560 | Val Obj: 11.1120 | LR: 0.002997
Epoch  15/200 | Train Obj: 8.0435 | Val Obj: 11.2293 | LR: 0.002995
Epoch  16/200 | Train Obj: 7.9061 | Val Obj: 11.2238 | LR: 0.002993
Epoch  17/200 | Train Obj: 7.7957 | Val Obj: 11.4268 | LR: 0.002990
Epoch  18/200 | Train Obj: 7.6998 | Val Obj: 11.3610 | LR: 0.002987
Epoch  19/200 | Train Obj: 7.6000 | Val Obj: 11.4343 | LR: 0.002983
Epoch  20/200 | Train Obj: 7.4976 | Val Obj: 11.4867 | LR: 0.002980
Epoch  21/200 | Train Obj: 7.4114 | Val Obj: 11.4249 | LR: 0.002975
Epoch  22/200 | Train Obj: 7.3449 | Val Obj: 11.6468 | LR: 0.002971
Epoch  23/200 | Train Obj: 7.2478 | Val Obj: 11.5843 | LR: 0.002965
Epoch  24/200 | Train Obj: 7.1828 | Val Obj: 11.5303 | LR: 0.002960
Epoch  25/200 | Train Obj: 7.1100 | Val Obj: 11.6398 | LR: 0.002954
Epoch  26/200 | Train Obj: 7.0360 | Val Obj: 11.5501 | LR: 0.002948
Epoch  27/200 | Train Obj: 6.9849 | Val Obj: 11.8243 | LR: 0.002941
Epoch  28/200 | Train Obj: 6.9170 | Val Obj: 11.8717 | LR: 0.002934
Early stopping.
[ART] saved table: artifacts/tables/sign_mag_dependence_set1_seedS1001_seedM43_H6.csv and artifacts/tables/sign_mag_dependence_set1_seedS1001_seedM43_H6.tex
[DM] Model vs Persist | DM=-11.022 | p=0 | mean(d)=-1.913918 (negative=better)
[MBB] block=6 | CI95(mean d_model-pers)=[-2.115775,-1.325963]
[MBB] block=12 | CI95(mean d_model-pers)=[-2.104803,-1.333245]
[MBB] block=24 | CI95(mean d_model-pers)=[-2.198813,-1.233419]
[MBB] block=6 | RMSE(flat) CI95=[1.610,1.783]
[MBB] block=12 | RMSE(flat) CI95=[1.582,1.796]
[MBB] block=24 | RMSE(flat) CI95=[1.556,1.839]

===== GLOBAL TEST (JOINT; TEST cities; years > VAL) =====
H=6 | RMSE(flat): 1.69 °C [1.65, 1.73] | MAE(flat): 1.22 °C [1.20, 1.25] | NLL(per-h): 1.8052 nats | EnergyScore(joint): 2.6096
AVG over horizons | RMSE: 1.69 | MAE: 1.22 | CRPS: 0.8867 | Cov@95(avg): 94.8%
Clim-0(flat)  | RMSE: 1.70 | MAE: 1.24
Persist(flat) | RMSE: 2.19 | MAE: 1.57
TinyTransformer(flat) | RMSE: 1.70 | MAE: 1.24 | train_sec: 6.0

----- Per-horizon summary (h=1..H) -----
h= 1 | RMSE=1.64 | MAE=1.17 | CRPS=0.8503 | Cov@95=94.3%
h= 2 | RMSE=1.69 | MAE=1.22 | CRPS=0.8828 | Cov@95=95.3%
h= 3 | RMSE=1.72 | MAE=1.24 | CRPS=0.9012 | Cov@95=93.9%
h= 4 | RMSE=1.71 | MAE=1.24 | CRPS=0.9047 | Cov@95=93.5%
h= 5 | RMSE=1.70 | MAE=1.24 | CRPS=0.8929 | Cov@95=96.1%
h= 6 | RMSE=1.69 | MAE=1.23 | CRPS=0.8886 | Cov@95=95.7%

----- Decade-wise (TEST; grouped by first horizon year) -----
2000s | N=1080 | RMSE(flat)=1.59 | MAE(flat)=1.18 | CRPS(avg)=0.8451 | Cov@95(avg)=95.6%
2010s | N=1150 | RMSE(flat)=1.78 | MAE(flat)=1.27 | CRPS(avg)=0.9259 | Cov@95(avg)=94.2%

----- Regime-wise (TEST; grouped by first horizon year ranges) -----
2001-2004 | N= 480 | RMSE(flat)=1.57 | MAE(flat)=1.15 | CRPS(avg)=0.8231 | Cov@95(avg)=95.8%
2005-2007 | N= 360 | RMSE(flat)=1.62 | MAE(flat)=1.22 | CRPS(avg)=0.8714 | Cov@95(avg)=95.2%
2008-2010 | N= 360 | RMSE(flat)=1.62 | MAE(flat)=1.18 | CRPS(avg)=0.8614 | Cov@95(avg)=94.7%
2011-2014 | N= 480 | RMSE(flat)=1.68 | MAE(flat)=1.20 | CRPS(avg)=0.8729 | Cov@95(avg)=94.6%
2015-2017 | N= 360 | RMSE(flat)=1.87 | MAE(flat)=1.36 | CRPS(avg)=0.9969 | Cov@95(avg)=93.6%
2018-2020 | N= 190 | RMSE(flat)=1.92 | MAE(flat)=1.30 | CRPS(avg)=0.9509 | Cov@95(avg)=94.9%

----- Per-city (eval cities; years > VAL) -----
       City                            Region  N_test_windows RMSE (°C) MAE (°C) NLL (per-h) CRPS (°C)  CIA95 Cov@50 Cov@90 Cov@95  N_windows_in_test DM_vs_Persist      DM_p
     Bangui                            Africa             223      0.57     0.43      0.8586    0.3207 94.89%  56.1%  99.2%  99.9%                223        -7.806 2.309e-13
      Osaka                              Asia             223      1.32     1.08      1.7060    0.7894 98.59%  35.8%  90.2%  96.3%                223        -2.529   0.01213
   Canberra           Australia/South Pacific             223      1.40     1.09      1.7416    0.7902 98.48%  42.9%  90.9%  96.0%                223        -8.867  2.22e-16
     Lisbon                            Europe             223      1.41     1.17      1.7402    0.8148 96.86%  32.8%  91.6%  98.0%                223        -6.800 9.582e-11
     Madrid                            Europe             223      1.75     1.44      2.0298    1.0289 96.11%  32.2%  82.2%  91.8%                223        -7.886 1.406e-13
      Amman                       Middle East             223      1.61     1.25      1.9291    0.8990 99.01%  41.4%  88.6%  95.8%                223        -7.619 7.312e-13
     Albany                     North America             223      2.06     1.59      2.1561    1.1464 97.69%  34.4%  83.3%  93.0%                223        -6.731 1.418e-10
    Buffalo                     North America             223      2.13     1.65      2.2230    1.1848 96.37%  34.9%  84.6%  91.6%                223        -7.328 4.284e-12
   Billings                     North America             223      2.78     2.03      2.6952    1.5169 90.87%  33.3%  78.1%  86.3%                223        -6.136 3.842e-09
Tegucigalpa South/Central America & Carribean             223      0.66     0.51      0.9721    0.3764 95.05%  48.7%  97.8%  99.7%                223        -4.462 1.291e-05

[DM] Per-city summary | significant(p<0.05): 10/10 | Fisher combined p=0

======================================================================
RUN | seed_split: 1001 | seed_model: 44 | device: cuda | H=6
======================================================================

/tmp/ipython-input-199474976.py:214: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

Using Colab cache for faster access to the 'daily-temperature-of-major-cities' dataset.
[DIAG] Available years: 1995..2020, cities: 321
[DIAG] Time splits -> TRAIN<= 1999, VAL: 2000..2000, TEST: 2001..2020
[DIAG] Horizon H=6

/tmp/ipython-input-199474976.py:301: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  for city, g in monthly.groupby("City", sort=False):

[DIAG] Eval set id: 1 | eval_seed: 124
[DIAG] Eval (TEST) cities: ['Bangui', 'Osaka', 'Canberra', 'Lisbon', 'Madrid', 'Amman', 'Albany', 'Buffalo', 'Billings', 'Tegucigalpa']
[DIAG] Geographic split -> TRAIN cities: 280, VAL cities: 31, TEST cities: 10

/tmp/ipython-input-199474976.py:674: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  for city, g in df.groupby("City", sort=False):

[DIAG] TRAIN samples: 11347
[DIAG] VAL samples: 189
[DIAG] TEST samples: 2230
[ART] saved TSLib NPZ: artifacts/npz/tslib_cityanom_set1_seedS1001_seedM44_H6_W12_H6.npz
Epoch   1/200 | Train Obj: 11.9744 | Val Obj: 12.0658 | LR: 0.000600
Epoch   2/200 | Train Obj: 10.1428 | Val Obj: 10.8522 | LR: 0.000900
Epoch   3/200 | Train Obj: 9.6509 | Val Obj: 10.8440 | LR: 0.001200
Epoch   4/200 | Train Obj: 9.4889 | Val Obj: 10.6955 | LR: 0.001500
Epoch   5/200 | Train Obj: 9.3374 | Val Obj: 10.7979 | LR: 0.001800
Epoch   6/200 | Train Obj: 9.1916 | Val Obj: 10.3568 | LR: 0.002100
Epoch   7/200 | Train Obj: 9.0824 | Val Obj: 10.3517 | LR: 0.002400
Epoch   8/200 | Train Obj: 8.9775 | Val Obj: 10.5783 | LR: 0.002700
Epoch   9/200 | Train Obj: 8.8762 | Val Obj: 10.5354 | LR: 0.003000
Epoch  10/200 | Train Obj: 8.7451 | Val Obj: 10.8695 | LR: 0.003000
Epoch  11/200 | Train Obj: 8.6268 | Val Obj: 10.9386 | LR: 0.003000
Epoch  12/200 | Train Obj: 8.4901 | Val Obj: 11.0030 | LR: 0.002999
Epoch  13/200 | Train Obj: 8.3552 | Val Obj: 11.2166 | LR: 0.002998
Epoch  14/200 | Train Obj: 8.2319 | Val Obj: 11.3606 | LR: 0.002997
Epoch  15/200 | Train Obj: 8.0934 | Val Obj: 11.3017 | LR: 0.002995
Epoch  16/200 | Train Obj: 7.9990 | Val Obj: 11.3179 | LR: 0.002993
Epoch  17/200 | Train Obj: 7.8682 | Val Obj: 11.6146 | LR: 0.002990
Epoch  18/200 | Train Obj: 7.7613 | Val Obj: 11.4766 | LR: 0.002987
Epoch  19/200 | Train Obj: 7.6650 | Val Obj: 11.6040 | LR: 0.002983
Epoch  20/200 | Train Obj: 7.5670 | Val Obj: 11.6962 | LR: 0.002980
Epoch  21/200 | Train Obj: 7.4647 | Val Obj: 11.6737 | LR: 0.002975
Epoch  22/200 | Train Obj: 7.3782 | Val Obj: 11.8100 | LR: 0.002971
Epoch  23/200 | Train Obj: 7.2998 | Val Obj: 11.8711 | LR: 0.002965
Epoch  24/200 | Train Obj: 7.2395 | Val Obj: 11.7084 | LR: 0.002960
Epoch  25/200 | Train Obj: 7.1550 | Val Obj: 11.9828 | LR: 0.002954
Epoch  26/200 | Train Obj: 7.0826 | Val Obj: 12.0304 | LR: 0.002948
Epoch  27/200 | Train Obj: 6.9974 | Val Obj: 12.1309 | LR: 0.002941
Early stopping.
[ART] saved table: artifacts/tables/sign_mag_dependence_set1_seedS1001_seedM44_H6.csv and artifacts/tables/sign_mag_dependence_set1_seedS1001_seedM44_H6.tex
[DM] Model vs Persist | DM=-11.144 | p=0 | mean(d)=-1.912002 (negative=better)
[MBB] block=6 | CI95(mean d_model-pers)=[-2.093965,-1.306706]
[MBB] block=12 | CI95(mean d_model-pers)=[-2.131445,-1.242251]
[MBB] block=24 | CI95(mean d_model-pers)=[-2.224345,-1.177504]
[MBB] block=6 | RMSE(flat) CI95=[1.603,1.789]
[MBB] block=12 | RMSE(flat) CI95=[1.588,1.805]
[MBB] block=24 | RMSE(flat) CI95=[1.553,1.845]

===== GLOBAL TEST (JOINT; TEST cities; years > VAL) =====
H=6 | RMSE(flat): 1.69 °C [1.65, 1.74] | MAE(flat): 1.22 °C [1.20, 1.25] | NLL(per-h): 1.7759 nats | EnergyScore(joint): 2.5948
AVG over horizons | RMSE: 1.69 | MAE: 1.22 | CRPS: 0.8865 | Cov@95(avg): 95.9%
Clim-0(flat)  | RMSE: 1.70 | MAE: 1.24
Persist(flat) | RMSE: 2.19 | MAE: 1.57
TinyTransformer(flat) | RMSE: 1.70 | MAE: 1.24 | train_sec: 6.2

----- Per-horizon summary (h=1..H) -----
h= 1 | RMSE=1.65 | MAE=1.18 | CRPS=0.8540 | Cov@95=95.9%
h= 2 | RMSE=1.71 | MAE=1.23 | CRPS=0.8873 | Cov@95=96.1%
h= 3 | RMSE=1.72 | MAE=1.24 | CRPS=0.8990 | Cov@95=95.7%
h= 4 | RMSE=1.71 | MAE=1.24 | CRPS=0.8954 | Cov@95=95.7%
h= 5 | RMSE=1.70 | MAE=1.24 | CRPS=0.8951 | Cov@95=95.7%
h= 6 | RMSE=1.67 | MAE=1.22 | CRPS=0.8880 | Cov@95=96.1%

----- Decade-wise (TEST; grouped by first horizon year) -----
2000s | N=1080 | RMSE(flat)=1.60 | MAE(flat)=1.18 | CRPS(avg)=0.8465 | Cov@95(avg)=96.4%
2010s | N=1150 | RMSE(flat)=1.78 | MAE(flat)=1.27 | CRPS(avg)=0.9240 | Cov@95(avg)=95.4%

----- Regime-wise (TEST; grouped by first horizon year ranges) -----
2001-2004 | N= 480 | RMSE(flat)=1.57 | MAE(flat)=1.15 | CRPS(avg)=0.8240 | Cov@95(avg)=96.3%
2005-2007 | N= 360 | RMSE(flat)=1.63 | MAE(flat)=1.22 | CRPS(avg)=0.8701 | Cov@95(avg)=96.4%
2008-2010 | N= 360 | RMSE(flat)=1.63 | MAE(flat)=1.19 | CRPS(avg)=0.8684 | Cov@95(avg)=96.0%
2011-2014 | N= 480 | RMSE(flat)=1.67 | MAE(flat)=1.19 | CRPS(avg)=0.8663 | Cov@95(avg)=95.9%
2015-2017 | N= 360 | RMSE(flat)=1.87 | MAE(flat)=1.37 | CRPS(avg)=0.9948 | Cov@95(avg)=94.9%
2018-2020 | N= 190 | RMSE(flat)=1.93 | MAE(flat)=1.31 | CRPS(avg)=0.9551 | Cov@95(avg)=95.5%

----- Per-city (eval cities; years > VAL) -----
       City                            Region  N_test_windows RMSE (°C) MAE (°C) NLL (per-h) CRPS (°C)  CIA95 Cov@50 Cov@90 Cov@95  N_windows_in_test DM_vs_Persist      DM_p
     Bangui                            Africa             223      0.58     0.44      0.8504    0.3302 94.82%  51.3%  99.0%  99.9%                223        -5.951  1.03e-08
      Osaka                              Asia             223      1.28     1.04      1.6600    0.7679 96.78%  38.9%  92.9%  98.1%                223        -3.550 0.0004699
   Canberra           Australia/South Pacific             223      1.43     1.10      1.7397    0.8025 97.49%  42.8%  91.5%  97.4%                223        -8.801 4.441e-16
     Lisbon                            Europe             223      1.43     1.19      1.7389    0.8325 96.62%  28.6%  92.1%  98.2%                223        -6.592  3.12e-10
     Madrid                            Europe             223      1.79     1.46      1.9995    1.0446 96.74%  30.4%  83.0%  92.1%                223        -7.251 6.788e-12
      Amman                       Middle East             223      1.59     1.25      1.9009    0.8911 97.73%  40.4%  90.8%  97.2%                223        -7.933 1.041e-13
     Albany                     North America             223      2.05     1.58      2.1122    1.1367 98.58%  34.4%  84.2%  93.6%                223        -7.171 1.097e-11
    Buffalo                     North America             223      2.12     1.64      2.1720    1.1737 98.00%  34.4%  86.4%  93.4%                223        -7.762 3.024e-13
   Billings                     North America             223      2.78     2.04      2.6297    1.5082 94.01%  32.3%  80.6%  89.3%                223        -6.213 2.537e-09
Tegucigalpa South/Central America & Carribean             223      0.65     0.51      0.9558    0.3772 95.21%  44.0%  96.8%  99.6%                223        -4.722 4.129e-06

[DM] Per-city summary | significant(p<0.05): 10/10 | Fisher combined p=0
Not enough models for epistemic on eval_set=1 (found 0).

======================================================================
RUN | seed_split: 1002 | seed_model: 42 | device: cuda | H=6
======================================================================

/tmp/ipython-input-199474976.py:214: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

Using Colab cache for faster access to the 'daily-temperature-of-major-cities' dataset.
[DIAG] Available years: 1995..2020, cities: 321
[DIAG] Time splits -> TRAIN<= 1999, VAL: 2000..2000, TEST: 2001..2020
[DIAG] Horizon H=6

/tmp/ipython-input-199474976.py:301: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  for city, g in monthly.groupby("City", sort=False):

[DIAG] Eval set id: 2 | eval_seed: 125
[DIAG] Eval (TEST) cities: ['Banjul', 'Kuala Lumpur', 'Melbourne', 'Moscow', 'Oslo', 'Damascus', 'Akron Canton', 'Birmingham', 'Asheville', 'Paramaribo']
[DIAG] Geographic split -> TRAIN cities: 280, VAL cities: 31, TEST cities: 10

/tmp/ipython-input-199474976.py:674: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  for city, g in df.groupby("City", sort=False):

[DIAG] TRAIN samples: 11316
[DIAG] VAL samples: 196
[DIAG] TEST samples: 2131
[ART] saved TSLib NPZ: artifacts/npz/tslib_cityanom_set2_seedS1002_seedM42_H6_W12_H6.npz
Epoch   1/200 | Train Obj: 11.7981 | Val Obj: 12.0195 | LR: 0.000600
Epoch   2/200 | Train Obj: 10.0975 | Val Obj: 11.7505 | LR: 0.000900
Epoch   3/200 | Train Obj: 9.6702 | Val Obj: 11.7383 | LR: 0.001200
Epoch   4/200 | Train Obj: 9.4952 | Val Obj: 11.5418 | LR: 0.001500
Epoch   5/200 | Train Obj: 9.3296 | Val Obj: 11.7330 | LR: 0.001800
Epoch   6/200 | Train Obj: 9.1943 | Val Obj: 11.4235 | LR: 0.002100
Epoch   7/200 | Train Obj: 9.0742 | Val Obj: 11.4731 | LR: 0.002400
Epoch   8/200 | Train Obj: 8.9756 | Val Obj: 11.3871 | LR: 0.002700
Epoch   9/200 | Train Obj: 8.8628 | Val Obj: 11.5772 | LR: 0.003000
Epoch  10/200 | Train Obj: 8.7273 | Val Obj: 11.8418 | LR: 0.003000
Epoch  11/200 | Train Obj: 8.5924 | Val Obj: 11.8289 | LR: 0.003000
Epoch  12/200 | Train Obj: 8.4473 | Val Obj: 12.0542 | LR: 0.002999
Epoch  13/200 | Train Obj: 8.3023 | Val Obj: 11.9804 | LR: 0.002998
Epoch  14/200 | Train Obj: 8.1822 | Val Obj: 12.1824 | LR: 0.002997
Epoch  15/200 | Train Obj: 8.0555 | Val Obj: 12.3271 | LR: 0.002995
Epoch  16/200 | Train Obj: 7.9315 | Val Obj: 12.3870 | LR: 0.002993
Epoch  17/200 | Train Obj: 7.8286 | Val Obj: 12.3912 | LR: 0.002990
Epoch  18/200 | Train Obj: 7.7139 | Val Obj: 12.5822 | LR: 0.002987
Epoch  19/200 | Train Obj: 7.6137 | Val Obj: 12.5500 | LR: 0.002983
Epoch  20/200 | Train Obj: 7.5378 | Val Obj: 12.5875 | LR: 0.002980
Epoch  21/200 | Train Obj: 7.4263 | Val Obj: 12.7183 | LR: 0.002975
Epoch  22/200 | Train Obj: 7.3614 | Val Obj: 12.4399 | LR: 0.002971
Epoch  23/200 | Train Obj: 7.2620 | Val Obj: 12.7943 | LR: 0.002965
Epoch  24/200 | Train Obj: 7.2018 | Val Obj: 12.6819 | LR: 0.002960
Epoch  25/200 | Train Obj: 7.1322 | Val Obj: 12.7491 | LR: 0.002954
Epoch  26/200 | Train Obj: 7.0495 | Val Obj: 12.9385 | LR: 0.002948
Epoch  27/200 | Train Obj: 6.9982 | Val Obj: 13.0258 | LR: 0.002941
Epoch  28/200 | Train Obj: 6.9304 | Val Obj: 13.1229 | LR: 0.002934
Early stopping.
[ART] saved table: artifacts/tables/sign_mag_dependence_set2_seedS1002_seedM42_H6.csv and artifacts/tables/sign_mag_dependence_set2_seedS1002_seedM42_H6.tex
[DM] Model vs Persist | DM=-13.661 | p=0 | mean(d)=-2.404197 (negative=better)
[MBB] block=6 | CI95(mean d_model-pers)=[-2.649924,-1.854493]
[MBB] block=12 | CI95(mean d_model-pers)=[-2.666536,-1.843255]
[MBB] block=24 | CI95(mean d_model-pers)=[-2.772577,-1.750915]
[MBB] block=6 | RMSE(flat) CI95=[1.658,1.851]
[MBB] block=12 | RMSE(flat) CI95=[1.642,1.882]
[MBB] block=24 | RMSE(flat) CI95=[1.597,1.928]

===== GLOBAL TEST (JOINT; TEST cities; years > VAL) =====
H=6 | RMSE(flat): 1.76 °C [1.72, 1.80] | MAE(flat): 1.23 °C [1.20, 1.26] | NLL(per-h): 1.7670 nats | EnergyScore(joint): 2.6404
AVG over horizons | RMSE: 1.76 | MAE: 1.23 | CRPS: 0.9035 | Cov@95(avg): 95.9%
Clim-0(flat)  | RMSE: 1.80 | MAE: 1.28
Persist(flat) | RMSE: 2.34 | MAE: 1.64
TinyTransformer(flat) | RMSE: 1.76 | MAE: 1.23 | train_sec: 4.8

----- Per-horizon summary (h=1..H) -----
h= 1 | RMSE=1.73 | MAE=1.20 | CRPS=0.8924 | Cov@95=95.6%
h= 2 | RMSE=1.77 | MAE=1.23 | CRPS=0.8982 | Cov@95=96.2%
h= 3 | RMSE=1.78 | MAE=1.25 | CRPS=0.9131 | Cov@95=95.4%
h= 4 | RMSE=1.77 | MAE=1.24 | CRPS=0.9120 | Cov@95=95.0%
h= 5 | RMSE=1.75 | MAE=1.22 | CRPS=0.8967 | Cov@95=96.8%
h= 6 | RMSE=1.75 | MAE=1.22 | CRPS=0.9084 | Cov@95=96.5%

----- Decade-wise (TEST; grouped by first horizon year) -----
2000s | N= 993 | RMSE(flat)=1.71 | MAE(flat)=1.19 | CRPS(avg)=0.8743 | Cov@95(avg)=96.4%
2010s | N=1138 | RMSE(flat)=1.80 | MAE(flat)=1.25 | CRPS(avg)=0.9289 | Cov@95(avg)=95.5%

----- Regime-wise (TEST; grouped by first horizon year ranges) -----
2001-2004 | N= 422 | RMSE(flat)=1.65 | MAE(flat)=1.18 | CRPS(avg)=0.8579 | Cov@95(avg)=97.0%
2005-2007 | N= 355 | RMSE(flat)=1.76 | MAE(flat)=1.21 | CRPS(avg)=0.8863 | Cov@95(avg)=96.3%
2008-2010 | N= 324 | RMSE(flat)=1.95 | MAE(flat)=1.33 | CRPS(avg)=0.9942 | Cov@95(avg)=93.5%
2011-2014 | N= 480 | RMSE(flat)=1.72 | MAE(flat)=1.19 | CRPS(avg)=0.8720 | Cov@95(avg)=96.4%
2015-2017 | N= 360 | RMSE(flat)=1.79 | MAE(flat)=1.28 | CRPS(avg)=0.9481 | Cov@95(avg)=95.7%
2018-2020 | N= 190 | RMSE(flat)=1.66 | MAE(flat)=1.17 | CRPS(avg)=0.8771 | Cov@95(avg)=96.1%

----- Per-city (eval cities; years > VAL) -----
        City                            Region  N_test_windows RMSE (°C) MAE (°C) NLL (per-h) CRPS (°C)  CIA95 Cov@50 Cov@90 Cov@95  N_windows_in_test DM_vs_Persist      DM_p
      Banjul                            Africa             149      0.82     0.60      1.1356    0.4334 95.80%  40.4%  94.9%  99.0%                149        -6.330 2.762e-09
Kuala Lumpur                              Asia             223      0.58     0.46      0.7992    0.3439 94.89%  41.1%  97.5%  99.9%                223        -1.794   0.07422
   Melbourne           Australia/South Pacific             223      0.98     0.77      1.4256    0.5947 96.31%  38.4%  94.9%  98.5%                223        -5.044 9.456e-07
      Moscow                            Europe             223      2.89     2.31      2.8182    1.7124 91.50%  23.5%  75.3%  86.9%                223       -10.776         0
        Oslo                            Europe             223      2.24     1.73      2.2695    1.2608 97.71%  31.1%  86.2%  92.8%                223       -10.240         0
    Damascus                       Middle East             223      1.55     1.16      1.8296    0.8604 98.51%  38.3%  90.3%  96.4%                223        -6.265 1.915e-09
Akron Canton                     North America             223      2.25     1.72      2.3173    1.2624 98.90%  31.6%  86.1%  94.0%                223        -8.447 3.997e-15
  Birmingham                     North America             223      1.87     1.45      2.0511    1.0469 98.06%  32.3%  89.7%  96.7%                223        -8.702 6.661e-16
   Asheville                     North America             223      1.80     1.39      2.0153    1.0101 98.51%  32.9%  90.1%  96.4%                223        -7.702 4.403e-13
  Paramaribo South/Central America & Carribean             198      0.48     0.37      0.6764    0.2842 94.74%  45.7%  99.2% 100.0%                198        -2.898   0.00418

[DM] Per-city summary | significant(p<0.05): 9/10 | Fisher combined p=0

======================================================================
RUN | seed_split: 1002 | seed_model: 43 | device: cuda | H=6
======================================================================

/tmp/ipython-input-199474976.py:214: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

Using Colab cache for faster access to the 'daily-temperature-of-major-cities' dataset.
[DIAG] Available years: 1995..2020, cities: 321
[DIAG] Time splits -> TRAIN<= 1999, VAL: 2000..2000, TEST: 2001..2020
[DIAG] Horizon H=6

/tmp/ipython-input-199474976.py:301: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  for city, g in monthly.groupby("City", sort=False):

[DIAG] Eval set id: 2 | eval_seed: 125
[DIAG] Eval (TEST) cities: ['Banjul', 'Kuala Lumpur', 'Melbourne', 'Moscow', 'Oslo', 'Damascus', 'Akron Canton', 'Birmingham', 'Asheville', 'Paramaribo']
[DIAG] Geographic split -> TRAIN cities: 280, VAL cities: 31, TEST cities: 10

/tmp/ipython-input-199474976.py:674: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  for city, g in df.groupby("City", sort=False):

[DIAG] TRAIN samples: 11316
[DIAG] VAL samples: 196
[DIAG] TEST samples: 2131
[ART] saved TSLib NPZ: artifacts/npz/tslib_cityanom_set2_seedS1002_seedM43_H6_W12_H6.npz
Epoch   1/200 | Train Obj: 11.7343 | Val Obj: 11.7885 | LR: 0.000600
Epoch   2/200 | Train Obj: 10.0992 | Val Obj: 11.7303 | LR: 0.000900
Epoch   3/200 | Train Obj: 9.6394 | Val Obj: 11.7150 | LR: 0.001200
Epoch   4/200 | Train Obj: 9.4757 | Val Obj: 11.5571 | LR: 0.001500
Epoch   5/200 | Train Obj: 9.3401 | Val Obj: 11.5739 | LR: 0.001800
Epoch   6/200 | Train Obj: 9.1984 | Val Obj: 11.3494 | LR: 0.002100
Epoch   7/200 | Train Obj: 9.0917 | Val Obj: 11.5164 | LR: 0.002400
Epoch   8/200 | Train Obj: 8.9974 | Val Obj: 11.5656 | LR: 0.002700
Epoch   9/200 | Train Obj: 8.9113 | Val Obj: 11.5746 | LR: 0.003000
Epoch  10/200 | Train Obj: 8.7826 | Val Obj: 11.7734 | LR: 0.003000
Epoch  11/200 | Train Obj: 8.6288 | Val Obj: 11.7148 | LR: 0.003000
Epoch  12/200 | Train Obj: 8.5039 | Val Obj: 11.7643 | LR: 0.002999
Epoch  13/200 | Train Obj: 8.3665 | Val Obj: 12.0377 | LR: 0.002998
Epoch  14/200 | Train Obj: 8.2289 | Val Obj: 11.9717 | LR: 0.002997
Epoch  15/200 | Train Obj: 8.1099 | Val Obj: 12.0883 | LR: 0.002995
Epoch  16/200 | Train Obj: 8.0095 | Val Obj: 12.1558 | LR: 0.002993
Epoch  17/200 | Train Obj: 7.8897 | Val Obj: 12.2042 | LR: 0.002990
Epoch  18/200 | Train Obj: 7.7568 | Val Obj: 12.3597 | LR: 0.002987
Epoch  19/200 | Train Obj: 7.6608 | Val Obj: 12.3124 | LR: 0.002983
Epoch  20/200 | Train Obj: 7.5815 | Val Obj: 12.4239 | LR: 0.002980
Epoch  21/200 | Train Obj: 7.5029 | Val Obj: 12.4762 | LR: 0.002975
Epoch  22/200 | Train Obj: 7.4321 | Val Obj: 12.5349 | LR: 0.002971
Epoch  23/200 | Train Obj: 7.3351 | Val Obj: 12.7426 | LR: 0.002965
Epoch  24/200 | Train Obj: 7.2688 | Val Obj: 12.8254 | LR: 0.002960
Epoch  25/200 | Train Obj: 7.1834 | Val Obj: 12.5524 | LR: 0.002954
Epoch  26/200 | Train Obj: 7.1039 | Val Obj: 12.7609 | LR: 0.002948
Early stopping.
[ART] saved table: artifacts/tables/sign_mag_dependence_set2_seedS1002_seedM43_H6.csv and artifacts/tables/sign_mag_dependence_set2_seedS1002_seedM43_H6.tex
[DM] Model vs Persist | DM=-13.690 | p=0 | mean(d)=-2.342394 (negative=better)
[MBB] block=6 | CI95(mean d_model-pers)=[-2.572694,-1.823962]
[MBB] block=12 | CI95(mean d_model-pers)=[-2.618160,-1.801202]
[MBB] block=24 | CI95(mean d_model-pers)=[-2.741282,-1.682292]
[MBB] block=6 | RMSE(flat) CI95=[1.683,1.875]
[MBB] block=12 | RMSE(flat) CI95=[1.646,1.899]
[MBB] block=24 | RMSE(flat) CI95=[1.617,1.937]

===== GLOBAL TEST (JOINT; TEST cities; years > VAL) =====
H=6 | RMSE(flat): 1.77 °C [1.73, 1.82] | MAE(flat): 1.25 °C [1.21, 1.28] | NLL(per-h): 1.7626 nats | EnergyScore(joint): 2.6726
AVG over horizons | RMSE: 1.77 | MAE: 1.25 | CRPS: 0.9177 | Cov@95(avg): 95.4%
Clim-0(flat)  | RMSE: 1.80 | MAE: 1.28
Persist(flat) | RMSE: 2.34 | MAE: 1.64
TinyTransformer(flat) | RMSE: 1.76 | MAE: 1.23 | train_sec: 5.6

----- Per-horizon summary (h=1..H) -----
h= 1 | RMSE=1.75 | MAE=1.23 | CRPS=0.9030 | Cov@95=95.6%
h= 2 | RMSE=1.79 | MAE=1.25 | CRPS=0.9209 | Cov@95=95.7%
h= 3 | RMSE=1.79 | MAE=1.26 | CRPS=0.9266 | Cov@95=94.9%
h= 4 | RMSE=1.77 | MAE=1.24 | CRPS=0.9118 | Cov@95=95.1%
h= 5 | RMSE=1.76 | MAE=1.24 | CRPS=0.9059 | Cov@95=96.4%
h= 6 | RMSE=1.78 | MAE=1.26 | CRPS=0.9378 | Cov@95=94.8%

----- Decade-wise (TEST; grouped by first horizon year) -----
2000s | N= 993 | RMSE(flat)=1.73 | MAE(flat)=1.21 | CRPS(avg)=0.8864 | Cov@95(avg)=95.9%
2010s | N=1138 | RMSE(flat)=1.82 | MAE(flat)=1.27 | CRPS(avg)=0.9449 | Cov@95(avg)=95.0%

----- Regime-wise (TEST; grouped by first horizon year ranges) -----
2001-2004 | N= 422 | RMSE(flat)=1.66 | MAE(flat)=1.19 | CRPS(avg)=0.8682 | Cov@95(avg)=96.2%
2005-2007 | N= 355 | RMSE(flat)=1.79 | MAE(flat)=1.23 | CRPS(avg)=0.9050 | Cov@95(avg)=95.6%
2008-2010 | N= 324 | RMSE(flat)=1.96 | MAE(flat)=1.35 | CRPS(avg)=1.0012 | Cov@95(avg)=93.7%
2011-2014 | N= 480 | RMSE(flat)=1.73 | MAE(flat)=1.21 | CRPS(avg)=0.8855 | Cov@95(avg)=95.6%
2015-2017 | N= 360 | RMSE(flat)=1.82 | MAE(flat)=1.31 | CRPS(avg)=0.9719 | Cov@95(avg)=95.7%
2018-2020 | N= 190 | RMSE(flat)=1.68 | MAE(flat)=1.18 | CRPS(avg)=0.8877 | Cov@95(avg)=95.1%

----- Per-city (eval cities; years > VAL) -----
        City                            Region  N_test_windows RMSE (°C) MAE (°C) NLL (per-h) CRPS (°C)  CIA95 Cov@50 Cov@90 Cov@95  N_windows_in_test DM_vs_Persist      DM_p
      Banjul                            Africa             149      0.81     0.60      1.1367    0.4357 95.80%  38.5%  95.2%  99.0%                149        -6.305 3.147e-09
Kuala Lumpur                              Asia             223      0.61     0.48      0.7941    0.3596 94.97%  31.7%  96.7%  99.8%                223        -0.849     0.397
   Melbourne           Australia/South Pacific             223      1.01     0.80      1.4367    0.6120 96.94%  32.8%  92.4%  97.9%                223        -4.362 1.975e-05
      Moscow                            Europe             223      2.95     2.36      2.8453    1.7666 88.90%  23.1%  71.7%  84.5%                223       -10.783         0
        Oslo                            Europe             223      2.25     1.74      2.2734    1.2695 98.03%  29.8%  85.2%  93.1%                223       -10.167         0
    Damascus                       Middle East             223      1.55     1.16      1.8238    0.8667 99.01%  37.1%  89.7%  95.8%                223        -6.223 2.407e-09
Akron Canton                     North America             223      2.27     1.74      2.2861    1.2775 97.98%  30.9%  84.3%  93.3%                223        -8.387 5.773e-15
  Birmingham                     North America             223      1.87     1.46      2.0292    1.0505 98.95%  31.3%  88.8%  95.7%                223        -9.126         0
   Asheville                     North America             223      1.80     1.40      1.9912    1.0155 98.04%  32.7%  89.1%  96.9%                223        -8.018 6.128e-14
  Paramaribo South/Central America & Carribean             198      0.51     0.39      0.6807    0.2932 94.74%  39.6%  99.0% 100.0%                198        -1.539    0.1253

[DM] Per-city summary | significant(p<0.05): 8/10 | Fisher combined p=0

======================================================================
RUN | seed_split: 1002 | seed_model: 44 | device: cuda | H=6
======================================================================

/tmp/ipython-input-199474976.py:214: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

Using Colab cache for faster access to the 'daily-temperature-of-major-cities' dataset.
[DIAG] Available years: 1995..2020, cities: 321
[DIAG] Time splits -> TRAIN<= 1999, VAL: 2000..2000, TEST: 2001..2020
[DIAG] Horizon H=6

/tmp/ipython-input-199474976.py:301: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  for city, g in monthly.groupby("City", sort=False):

[DIAG] Eval set id: 2 | eval_seed: 125
[DIAG] Eval (TEST) cities: ['Banjul', 'Kuala Lumpur', 'Melbourne', 'Moscow', 'Oslo', 'Damascus', 'Akron Canton', 'Birmingham', 'Asheville', 'Paramaribo']
[DIAG] Geographic split -> TRAIN cities: 280, VAL cities: 31, TEST cities: 10

/tmp/ipython-input-199474976.py:674: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  for city, g in df.groupby("City", sort=False):

[DIAG] TRAIN samples: 11316
[DIAG] VAL samples: 196
[DIAG] TEST samples: 2131
[ART] saved TSLib NPZ: artifacts/npz/tslib_cityanom_set2_seedS1002_seedM44_H6_W12_H6.npz
Epoch   1/200 | Train Obj: 11.9097 | Val Obj: 12.6060 | LR: 0.000600
Epoch   2/200 | Train Obj: 10.1236 | Val Obj: 11.7452 | LR: 0.000900
Epoch   3/200 | Train Obj: 9.6477 | Val Obj: 11.6899 | LR: 0.001200
Epoch   4/200 | Train Obj: 9.5001 | Val Obj: 11.6458 | LR: 0.001500
Epoch   5/200 | Train Obj: 9.3652 | Val Obj: 11.5694 | LR: 0.001800
Epoch   6/200 | Train Obj: 9.2158 | Val Obj: 11.5666 | LR: 0.002100
Epoch   7/200 | Train Obj: 9.1029 | Val Obj: 11.2806 | LR: 0.002400
Epoch   8/200 | Train Obj: 9.0031 | Val Obj: 11.5234 | LR: 0.002700
Epoch   9/200 | Train Obj: 8.9112 | Val Obj: 11.7158 | LR: 0.003000
Epoch  10/200 | Train Obj: 8.7955 | Val Obj: 11.7390 | LR: 0.003000
Epoch  11/200 | Train Obj: 8.6736 | Val Obj: 11.7245 | LR: 0.003000
Epoch  12/200 | Train Obj: 8.5369 | Val Obj: 12.0623 | LR: 0.002999
Epoch  13/200 | Train Obj: 8.4304 | Val Obj: 11.9327 | LR: 0.002998
Epoch  14/200 | Train Obj: 8.3000 | Val Obj: 12.0669 | LR: 0.002997
Epoch  15/200 | Train Obj: 8.1854 | Val Obj: 12.2776 | LR: 0.002995
Epoch  16/200 | Train Obj: 8.0399 | Val Obj: 12.4473 | LR: 0.002993
Epoch  17/200 | Train Obj: 7.9330 | Val Obj: 12.3371 | LR: 0.002990
Epoch  18/200 | Train Obj: 7.8183 | Val Obj: 12.3749 | LR: 0.002987
Epoch  19/200 | Train Obj: 7.7216 | Val Obj: 12.2060 | LR: 0.002983
Epoch  20/200 | Train Obj: 7.6289 | Val Obj: 12.5293 | LR: 0.002980
Epoch  21/200 | Train Obj: 7.5268 | Val Obj: 12.5019 | LR: 0.002975
Epoch  22/200 | Train Obj: 7.4609 | Val Obj: 12.7336 | LR: 0.002971
Epoch  23/200 | Train Obj: 7.3820 | Val Obj: 12.4614 | LR: 0.002965
Epoch  24/200 | Train Obj: 7.2882 | Val Obj: 12.6709 | LR: 0.002960
Epoch  25/200 | Train Obj: 7.2231 | Val Obj: 12.9089 | LR: 0.002954
Epoch  26/200 | Train Obj: 7.1536 | Val Obj: 12.7459 | LR: 0.002948
Epoch  27/200 | Train Obj: 7.0958 | Val Obj: 12.8288 | LR: 0.002941
Early stopping.
[ART] saved table: artifacts/tables/sign_mag_dependence_set2_seedS1002_seedM44_H6.csv and artifacts/tables/sign_mag_dependence_set2_seedS1002_seedM44_H6.tex
[DM] Model vs Persist | DM=-13.675 | p=0 | mean(d)=-2.363567 (negative=better)
[MBB] block=6 | CI95(mean d_model-pers)=[-2.637234,-1.869847]
[MBB] block=12 | CI95(mean d_model-pers)=[-2.647566,-1.823667]
[MBB] block=24 | CI95(mean d_model-pers)=[-2.739683,-1.741619]
[MBB] block=6 | RMSE(flat) CI95=[1.675,1.863]
[MBB] block=12 | RMSE(flat) CI95=[1.642,1.897]
[MBB] block=24 | RMSE(flat) CI95=[1.605,1.920]

===== GLOBAL TEST (JOINT; TEST cities; years > VAL) =====
H=6 | RMSE(flat): 1.77 °C [1.72, 1.81] | MAE(flat): 1.23 °C [1.20, 1.27] | NLL(per-h): 1.7589 nats | EnergyScore(joint): 2.6553
AVG over horizons | RMSE: 1.77 | MAE: 1.23 | CRPS: 0.9154 | Cov@95(avg): 96.2%
Clim-0(flat)  | RMSE: 1.80 | MAE: 1.28
Persist(flat) | RMSE: 2.34 | MAE: 1.64
TinyTransformer(flat) | RMSE: 1.76 | MAE: 1.23 | train_sec: 4.9

----- Per-horizon summary (h=1..H) -----
h= 1 | RMSE=1.73 | MAE=1.20 | CRPS=0.8922 | Cov@95=96.2%
h= 2 | RMSE=1.79 | MAE=1.25 | CRPS=0.9171 | Cov@95=96.2%
h= 3 | RMSE=1.79 | MAE=1.25 | CRPS=0.9221 | Cov@95=96.3%
h= 4 | RMSE=1.78 | MAE=1.25 | CRPS=0.9194 | Cov@95=96.4%
h= 5 | RMSE=1.76 | MAE=1.23 | CRPS=0.9188 | Cov@95=95.6%
h= 6 | RMSE=1.76 | MAE=1.23 | CRPS=0.9226 | Cov@95=96.2%

----- Decade-wise (TEST; grouped by first horizon year) -----
2000s | N= 993 | RMSE(flat)=1.72 | MAE(flat)=1.20 | CRPS(avg)=0.8822 | Cov@95(avg)=96.6%
2010s | N=1138 | RMSE(flat)=1.81 | MAE(flat)=1.27 | CRPS(avg)=0.9443 | Cov@95(avg)=95.8%

----- Regime-wise (TEST; grouped by first horizon year ranges) -----
2001-2004 | N= 422 | RMSE(flat)=1.65 | MAE(flat)=1.18 | CRPS(avg)=0.8609 | Cov@95(avg)=97.3%
2005-2007 | N= 355 | RMSE(flat)=1.77 | MAE(flat)=1.22 | CRPS(avg)=0.9010 | Cov@95(avg)=96.4%
2008-2010 | N= 324 | RMSE(flat)=1.96 | MAE(flat)=1.33 | CRPS(avg)=1.0007 | Cov@95(avg)=93.6%
2011-2014 | N= 480 | RMSE(flat)=1.73 | MAE(flat)=1.21 | CRPS(avg)=0.8870 | Cov@95(avg)=96.2%
2015-2017 | N= 360 | RMSE(flat)=1.82 | MAE(flat)=1.29 | CRPS(avg)=0.9646 | Cov@95(avg)=96.9%
2018-2020 | N= 190 | RMSE(flat)=1.69 | MAE(flat)=1.17 | CRPS(avg)=0.8960 | Cov@95(avg)=96.2%

----- Per-city (eval cities; years > VAL) -----
        City                            Region  N_test_windows RMSE (°C) MAE (°C) NLL (per-h) CRPS (°C)  CIA95 Cov@50 Cov@90 Cov@95  N_windows_in_test DM_vs_Persist      DM_p
      Banjul                            Africa             149      0.83     0.61      1.1569    0.4392 95.21%  40.7%  97.0%  99.6%                149        -6.050 1.134e-08
Kuala Lumpur                              Asia             223      0.55     0.43      0.8082    0.3401 94.74%  40.2%  99.1% 100.0%                223        -2.864  0.004582
   Melbourne           Australia/South Pacific             223      0.98     0.77      1.4186    0.6000 95.68%  37.9%  96.0%  99.1%                223        -5.247 3.602e-07
      Moscow                            Europe             223      2.92     2.34      2.8288    1.7560 91.02%  20.8%  74.4%  86.5%                223       -10.720         0
        Oslo                            Europe             223      2.25     1.74      2.2657    1.2784 98.65%  28.7%  85.4%  93.7%                223       -10.155         0
    Damascus                       Middle East             223      1.55     1.17      1.8163    0.8694 97.18%  36.2%  91.0%  97.7%                223        -6.374 1.054e-09
Akron Canton                     North America             223      2.27     1.75      2.2896    1.2809 98.58%  27.6%  85.5%  93.6%                223        -8.459 3.775e-15
  Birmingham                     North America             223      1.87     1.46      2.0144    1.0541 98.30%  30.0%  90.4%  96.5%                223        -8.845  2.22e-16
   Asheville                     North America             223      1.82     1.41      1.9892    1.0244 98.14%  31.0%  90.1%  96.6%                223        -7.819 2.125e-13
  Paramaribo South/Central America & Carribean             198      0.47     0.37      0.6810    0.2821 94.74%  45.8% 100.0% 100.0%                198        -3.502 0.0005708

[DM] Per-city summary | significant(p<0.05): 10/10 | Fisher combined p=0
Not enough models for epistemic on eval_set=2 (found 0).

======================================================================
RUN | seed_split: 1003 | seed_model: 42 | device: cuda | H=6
======================================================================

/tmp/ipython-input-199474976.py:214: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

Using Colab cache for faster access to the 'daily-temperature-of-major-cities' dataset.
[DIAG] Available years: 1995..2020, cities: 321
[DIAG] Time splits -> TRAIN<= 1999, VAL: 2000..2000, TEST: 2001..2020
[DIAG] Horizon H=6

/tmp/ipython-input-199474976.py:301: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  for city, g in monthly.groupby("City", sort=False):

[DIAG] Eval set id: 3 | eval_seed: 126
[DIAG] Eval (TEST) cities: ['Dakar', 'Singapore', 'Brisbane', 'Budapest', 'Minsk', 'Abu Dhabi', 'Boise', 'Albuquerque', 'Cheyenne', 'Sao Paulo']
[DIAG] Geographic split -> TRAIN cities: 280, VAL cities: 31, TEST cities: 10

/tmp/ipython-input-199474976.py:674: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  for city, g in df.groupby("City", sort=False):

[DIAG] TRAIN samples: 11207
[DIAG] VAL samples: 207
[DIAG] TEST samples: 2230
[ART] saved TSLib NPZ: artifacts/npz/tslib_cityanom_set3_seedS1003_seedM42_H6_W12_H6.npz
Epoch   1/200 | Train Obj: 12.0603 | Val Obj: 9.8318 | LR: 0.000600
Epoch   2/200 | Train Obj: 10.2947 | Val Obj: 9.4030 | LR: 0.000900
Epoch   3/200 | Train Obj: 9.8409 | Val Obj: 9.1933 | LR: 0.001200
Epoch   4/200 | Train Obj: 9.6413 | Val Obj: 9.0929 | LR: 0.001500
Epoch   5/200 | Train Obj: 9.4896 | Val Obj: 8.9889 | LR: 0.001800
Epoch   6/200 | Train Obj: 9.3517 | Val Obj: 8.8842 | LR: 0.002100
Epoch   7/200 | Train Obj: 9.2310 | Val Obj: 8.9223 | LR: 0.002400
Epoch   8/200 | Train Obj: 9.1132 | Val Obj: 8.9351 | LR: 0.002700
Epoch   9/200 | Train Obj: 9.0155 | Val Obj: 8.8501 | LR: 0.003000
Epoch  10/200 | Train Obj: 8.8896 | Val Obj: 8.9441 | LR: 0.003000
Epoch  11/200 | Train Obj: 8.7460 | Val Obj: 8.9084 | LR: 0.003000
Epoch  12/200 | Train Obj: 8.6000 | Val Obj: 9.0716 | LR: 0.002999
Epoch  13/200 | Train Obj: 8.4534 | Val Obj: 9.1077 | LR: 0.002998
Epoch  14/200 | Train Obj: 8.3378 | Val Obj: 9.0551 | LR: 0.002997
Epoch  15/200 | Train Obj: 8.1802 | Val Obj: 9.2265 | LR: 0.002995
Epoch  16/200 | Train Obj: 8.0777 | Val Obj: 9.1316 | LR: 0.002993
Epoch  17/200 | Train Obj: 7.9490 | Val Obj: 9.3239 | LR: 0.002990
Epoch  18/200 | Train Obj: 7.8460 | Val Obj: 9.2650 | LR: 0.002987
Epoch  19/200 | Train Obj: 7.7375 | Val Obj: 9.3744 | LR: 0.002983
Epoch  20/200 | Train Obj: 7.6414 | Val Obj: 9.5329 | LR: 0.002980
Epoch  21/200 | Train Obj: 7.5565 | Val Obj: 9.3673 | LR: 0.002975
Epoch  22/200 | Train Obj: 7.4615 | Val Obj: 9.5001 | LR: 0.002971
Epoch  23/200 | Train Obj: 7.4083 | Val Obj: 9.5167 | LR: 0.002965
Epoch  24/200 | Train Obj: 7.3372 | Val Obj: 9.6117 | LR: 0.002960
Epoch  25/200 | Train Obj: 7.2453 | Val Obj: 9.6359 | LR: 0.002954
Epoch  26/200 | Train Obj: 7.1899 | Val Obj: 9.6145 | LR: 0.002948
Epoch  27/200 | Train Obj: 7.1319 | Val Obj: 9.6735 | LR: 0.002941
Epoch  28/200 | Train Obj: 7.0735 | Val Obj: 9.6876 | LR: 0.002934
Epoch  29/200 | Train Obj: 6.9910 | Val Obj: 9.7195 | LR: 0.002927
Early stopping.
[ART] saved table: artifacts/tables/sign_mag_dependence_set3_seedS1003_seedM42_H6.csv and artifacts/tables/sign_mag_dependence_set3_seedS1003_seedM42_H6.tex
[DM] Model vs Persist | DM=-12.867 | p=0 | mean(d)=-1.843317 (negative=better)
[MBB] block=6 | CI95(mean d_model-pers)=[-2.074380,-1.464557]
[MBB] block=12 | CI95(mean d_model-pers)=[-2.106917,-1.421494]
[MBB] block=24 | CI95(mean d_model-pers)=[-2.189795,-1.366867]
[MBB] block=6 | RMSE(flat) CI95=[1.587,1.762]
[MBB] block=12 | RMSE(flat) CI95=[1.564,1.777]
[MBB] block=24 | RMSE(flat) CI95=[1.540,1.813]

===== GLOBAL TEST (JOINT; TEST cities; years > VAL) =====
H=6 | RMSE(flat): 1.68 °C [1.63, 1.72] | MAE(flat): 1.22 °C [1.19, 1.25] | NLL(per-h): 1.7801 nats | EnergyScore(joint): 2.5686
AVG over horizons | RMSE: 1.68 | MAE: 1.22 | CRPS: 0.8839 | Cov@95(avg): 92.4%
Clim-0(flat)  | RMSE: 1.67 | MAE: 1.22
Persist(flat) | RMSE: 2.16 | MAE: 1.53
TinyTransformer(flat) | RMSE: 1.63 | MAE: 1.18 | train_sec: 4.7

----- Per-horizon summary (h=1..H) -----
h= 1 | RMSE=1.63 | MAE=1.19 | CRPS=0.8618 | Cov@95=92.5%
h= 2 | RMSE=1.67 | MAE=1.21 | CRPS=0.8746 | Cov@95=92.7%
h= 3 | RMSE=1.68 | MAE=1.23 | CRPS=0.8872 | Cov@95=92.5%
h= 4 | RMSE=1.70 | MAE=1.24 | CRPS=0.8995 | Cov@95=91.5%
h= 5 | RMSE=1.70 | MAE=1.24 | CRPS=0.8975 | Cov@95=91.6%
h= 6 | RMSE=1.67 | MAE=1.21 | CRPS=0.8827 | Cov@95=93.7%

----- Decade-wise (TEST; grouped by first horizon year) -----
2000s | N=1080 | RMSE(flat)=1.64 | MAE(flat)=1.19 | CRPS(avg)=0.8609 | Cov@95(avg)=92.4%
2010s | N=1150 | RMSE(flat)=1.71 | MAE(flat)=1.25 | CRPS(avg)=0.9055 | Cov@95(avg)=92.5%

----- Regime-wise (TEST; grouped by first horizon year ranges) -----
2001-2004 | N= 480 | RMSE(flat)=1.67 | MAE(flat)=1.21 | CRPS(avg)=0.8787 | Cov@95(avg)=92.4%
2005-2007 | N= 360 | RMSE(flat)=1.74 | MAE(flat)=1.25 | CRPS(avg)=0.9123 | Cov@95(avg)=90.7%
2008-2010 | N= 360 | RMSE(flat)=1.47 | MAE(flat)=1.08 | CRPS(avg)=0.7802 | Cov@95(avg)=93.9%
2011-2014 | N= 480 | RMSE(flat)=1.74 | MAE(flat)=1.21 | CRPS(avg)=0.8853 | Cov@95(avg)=92.3%
2015-2017 | N= 360 | RMSE(flat)=1.73 | MAE(flat)=1.29 | CRPS(avg)=0.9378 | Cov@95(avg)=92.4%
2018-2020 | N= 190 | RMSE(flat)=1.65 | MAE(flat)=1.31 | CRPS(avg)=0.9338 | Cov@95(avg)=93.4%

----- Per-city (eval cities; years > VAL) -----
       City                            Region  N_test_windows RMSE (°C) MAE (°C) NLL (per-h) CRPS (°C)  CIA95 Cov@50 Cov@90 Cov@95  N_windows_in_test DM_vs_Persist      DM_p
      Dakar                            Africa             223      0.88     0.68      1.1404    0.4835 98.20%  38.9%  91.9%  96.7%                223        -5.872 1.559e-08
  Singapore                              Asia             223      0.45     0.35      0.6428    0.2632 94.82%  59.2%  99.0%  99.9%                223        -5.051 9.162e-07
   Brisbane           Australia/South Pacific             223      0.86     0.70      1.2730    0.5018 97.96%  37.1%  91.6%  96.9%                223        -4.154 4.662e-05
   Budapest                            Europe             223      2.08     1.66      2.2800    1.2073 94.64%  28.9%  81.5%  89.9%                223        -5.463 1.254e-07
      Minsk                            Europe             223      2.59     2.05      2.6114    1.5193 87.88%  29.2%  72.8%  83.5%                223        -9.465         0
  Abu Dhabi                       Middle East             223      1.06     0.83      1.4373    0.6036 99.09%  39.2%  90.1%  95.6%                223        -2.819  0.005253
      Boise                     North America             223      2.33     1.84      2.3976    1.3511 89.61%  28.6%  73.9%  85.1%                223        -6.176 3.098e-09
Albuquerque                     North America             223      1.67     1.34      1.9769    0.9582 96.77%  34.0%  83.7%  91.9%                223        -8.390 5.551e-15
   Cheyenne                     North America             223      2.11     1.74      2.3311    1.2456 94.09%  26.5%  78.8%  89.4%                223        -8.935  2.22e-16
  Sao Paulo South/Central America & Carribean             223      1.24     0.99      1.7103    0.7054 99.45%  38.1%  87.8%  95.1%                223        -8.655 8.882e-16

[DM] Per-city summary | significant(p<0.05): 10/10 | Fisher combined p=0

======================================================================
RUN | seed_split: 1003 | seed_model: 43 | device: cuda | H=6
======================================================================

/tmp/ipython-input-199474976.py:214: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

Using Colab cache for faster access to the 'daily-temperature-of-major-cities' dataset.
[DIAG] Available years: 1995..2020, cities: 321
[DIAG] Time splits -> TRAIN<= 1999, VAL: 2000..2000, TEST: 2001..2020
[DIAG] Horizon H=6

/tmp/ipython-input-199474976.py:301: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  for city, g in monthly.groupby("City", sort=False):

[DIAG] Eval set id: 3 | eval_seed: 126
[DIAG] Eval (TEST) cities: ['Dakar', 'Singapore', 'Brisbane', 'Budapest', 'Minsk', 'Abu Dhabi', 'Boise', 'Albuquerque', 'Cheyenne', 'Sao Paulo']
[DIAG] Geographic split -> TRAIN cities: 280, VAL cities: 31, TEST cities: 10

/tmp/ipython-input-199474976.py:674: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  for city, g in df.groupby("City", sort=False):

[DIAG] TRAIN samples: 11207
[DIAG] VAL samples: 207
[DIAG] TEST samples: 2230
[ART] saved TSLib NPZ: artifacts/npz/tslib_cityanom_set3_seedS1003_seedM43_H6_W12_H6.npz
Epoch   1/200 | Train Obj: 12.0235 | Val Obj: 9.7641 | LR: 0.000600
Epoch   2/200 | Train Obj: 10.2871 | Val Obj: 9.4131 | LR: 0.000900
Epoch   3/200 | Train Obj: 9.7967 | Val Obj: 9.2118 | LR: 0.001200
Epoch   4/200 | Train Obj: 9.6235 | Val Obj: 9.0971 | LR: 0.001500
Epoch   5/200 | Train Obj: 9.4822 | Val Obj: 9.0056 | LR: 0.001800
Epoch   6/200 | Train Obj: 9.3611 | Val Obj: 8.8594 | LR: 0.002100
Epoch   7/200 | Train Obj: 9.2088 | Val Obj: 8.8327 | LR: 0.002400
Epoch   8/200 | Train Obj: 9.1130 | Val Obj: 8.7972 | LR: 0.002700
Epoch   9/200 | Train Obj: 9.0101 | Val Obj: 8.9879 | LR: 0.003000
Epoch  10/200 | Train Obj: 8.8738 | Val Obj: 9.0224 | LR: 0.003000
Epoch  11/200 | Train Obj: 8.7354 | Val Obj: 9.1109 | LR: 0.003000
Epoch  12/200 | Train Obj: 8.5581 | Val Obj: 9.2211 | LR: 0.002999
Epoch  13/200 | Train Obj: 8.4232 | Val Obj: 9.2494 | LR: 0.002998
Epoch  14/200 | Train Obj: 8.2651 | Val Obj: 9.3706 | LR: 0.002997
Epoch  15/200 | Train Obj: 8.1279 | Val Obj: 9.5215 | LR: 0.002995
Epoch  16/200 | Train Obj: 8.0088 | Val Obj: 9.4225 | LR: 0.002993
Epoch  17/200 | Train Obj: 7.8915 | Val Obj: 9.4834 | LR: 0.002990
Epoch  18/200 | Train Obj: 7.7859 | Val Obj: 9.5754 | LR: 0.002987
Epoch  19/200 | Train Obj: 7.6788 | Val Obj: 9.6822 | LR: 0.002983
Epoch  20/200 | Train Obj: 7.5821 | Val Obj: 9.6076 | LR: 0.002980
Epoch  21/200 | Train Obj: 7.5122 | Val Obj: 9.7744 | LR: 0.002975
Epoch  22/200 | Train Obj: 7.4313 | Val Obj: 9.8937 | LR: 0.002971
Epoch  23/200 | Train Obj: 7.3547 | Val Obj: 9.8584 | LR: 0.002965
Epoch  24/200 | Train Obj: 7.2853 | Val Obj: 9.8943 | LR: 0.002960
Epoch  25/200 | Train Obj: 7.1993 | Val Obj: 9.8771 | LR: 0.002954
Epoch  26/200 | Train Obj: 7.1413 | Val Obj: 9.9316 | LR: 0.002948
Epoch  27/200 | Train Obj: 7.0714 | Val Obj: 9.9748 | LR: 0.002941
Epoch  28/200 | Train Obj: 7.0046 | Val Obj: 10.0640 | LR: 0.002934
Early stopping.
[ART] saved table: artifacts/tables/sign_mag_dependence_set3_seedS1003_seedM43_H6.csv and artifacts/tables/sign_mag_dependence_set3_seedS1003_seedM43_H6.tex
[DM] Model vs Persist | DM=-13.287 | p=0 | mean(d)=-1.878990 (negative=better)
[MBB] block=6 | CI95(mean d_model-pers)=[-2.149205,-1.498086]
[MBB] block=12 | CI95(mean d_model-pers)=[-2.187558,-1.467812]
[MBB] block=24 | CI95(mean d_model-pers)=[-2.270567,-1.422790]
[MBB] block=6 | RMSE(flat) CI95=[1.580,1.756]
[MBB] block=12 | RMSE(flat) CI95=[1.562,1.773]
[MBB] block=24 | RMSE(flat) CI95=[1.520,1.812]

===== GLOBAL TEST (JOINT; TEST cities; years > VAL) =====
H=6 | RMSE(flat): 1.66 °C [1.63, 1.70] | MAE(flat): 1.21 °C [1.18, 1.24] | NLL(per-h): 1.7533 nats | EnergyScore(joint): 2.5457
AVG over horizons | RMSE: 1.66 | MAE: 1.21 | CRPS: 0.8740 | Cov@95(avg): 92.4%
Clim-0(flat)  | RMSE: 1.67 | MAE: 1.22
Persist(flat) | RMSE: 2.16 | MAE: 1.53
TinyTransformer(flat) | RMSE: 1.63 | MAE: 1.18 | train_sec: 5.4

----- Per-horizon summary (h=1..H) -----
h= 1 | RMSE=1.62 | MAE=1.17 | CRPS=0.8435 | Cov@95=93.0%
h= 2 | RMSE=1.66 | MAE=1.20 | CRPS=0.8677 | Cov@95=92.9%
h= 3 | RMSE=1.67 | MAE=1.22 | CRPS=0.8824 | Cov@95=92.2%
h= 4 | RMSE=1.68 | MAE=1.22 | CRPS=0.8891 | Cov@95=91.6%
h= 5 | RMSE=1.69 | MAE=1.23 | CRPS=0.8891 | Cov@95=92.0%
h= 6 | RMSE=1.66 | MAE=1.20 | CRPS=0.8720 | Cov@95=92.9%

----- Decade-wise (TEST; grouped by first horizon year) -----
2000s | N=1080 | RMSE(flat)=1.62 | MAE(flat)=1.17 | CRPS(avg)=0.8483 | Cov@95(avg)=92.4%
2010s | N=1150 | RMSE(flat)=1.70 | MAE(flat)=1.24 | CRPS(avg)=0.8981 | Cov@95(avg)=92.4%

----- Regime-wise (TEST; grouped by first horizon year ranges) -----
2001-2004 | N= 480 | RMSE(flat)=1.66 | MAE(flat)=1.20 | CRPS(avg)=0.8696 | Cov@95(avg)=92.1%
2005-2007 | N= 360 | RMSE(flat)=1.70 | MAE(flat)=1.23 | CRPS(avg)=0.8911 | Cov@95(avg)=91.3%
2008-2010 | N= 360 | RMSE(flat)=1.47 | MAE(flat)=1.07 | CRPS(avg)=0.7752 | Cov@95(avg)=94.2%
2011-2014 | N= 480 | RMSE(flat)=1.74 | MAE(flat)=1.22 | CRPS(avg)=0.8838 | Cov@95(avg)=92.4%
2015-2017 | N= 360 | RMSE(flat)=1.72 | MAE(flat)=1.28 | CRPS(avg)=0.9230 | Cov@95(avg)=92.1%
2018-2020 | N= 190 | RMSE(flat)=1.65 | MAE(flat)=1.30 | CRPS(avg)=0.9221 | Cov@95(avg)=92.6%

----- Per-city (eval cities; years > VAL) -----
       City                            Region  N_test_windows RMSE (°C) MAE (°C) NLL (per-h) CRPS (°C)  CIA95 Cov@50 Cov@90 Cov@95  N_windows_in_test DM_vs_Persist      DM_p
      Dakar                            Africa             223      0.85     0.65      1.1199    0.4657 98.59%  44.7%  91.3%  96.3%                223        -6.482  5.77e-10
  Singapore                              Asia             223      0.45     0.35      0.6396    0.2630 94.89%  59.6%  99.0%  99.9%                223        -6.033 6.675e-09
   Brisbane           Australia/South Pacific             223      0.82     0.67      1.2451    0.4766 97.18%  39.8%  91.6%  97.7%                223        -5.709 3.618e-08
   Budapest                            Europe             223      2.07     1.66      2.2104    1.2006 94.96%  29.1%  81.7%  90.2%                223        -5.844 1.807e-08
      Minsk                            Europe             223      2.59     2.06      2.5679    1.5129 88.58%  29.5%  72.6%  84.2%                223        -9.414         0
  Abu Dhabi                       Middle East             223      1.03     0.81      1.4061    0.5866 98.98%  42.1%  89.8%  95.3%                223        -3.352 0.0009445
      Boise                     North America             223      2.31     1.83      2.3748    1.3391 90.00%  29.2%  75.5%  85.5%                223        -6.232 2.287e-09
Albuquerque                     North America             223      1.65     1.33      1.9708    0.9474 96.22%  36.2%  83.8%  91.4%                223        -9.034         0
   Cheyenne                     North America             223      2.11     1.73      2.3155    1.2436 93.46%  28.5%  77.8%  88.8%                223        -9.362         0
  Sao Paulo South/Central America & Carribean             223      1.24     1.00      1.6832    0.7044 99.03%  40.6%  89.0%  95.1%                223        -8.702 6.661e-16

[DM] Per-city summary | significant(p<0.05): 10/10 | Fisher combined p=0

======================================================================
RUN | seed_split: 1003 | seed_model: 44 | device: cuda | H=6
======================================================================

/tmp/ipython-input-199474976.py:214: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

Using Colab cache for faster access to the 'daily-temperature-of-major-cities' dataset.
[DIAG] Available years: 1995..2020, cities: 321
[DIAG] Time splits -> TRAIN<= 1999, VAL: 2000..2000, TEST: 2001..2020
[DIAG] Horizon H=6

/tmp/ipython-input-199474976.py:301: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  for city, g in monthly.groupby("City", sort=False):

[DIAG] Eval set id: 3 | eval_seed: 126
[DIAG] Eval (TEST) cities: ['Dakar', 'Singapore', 'Brisbane', 'Budapest', 'Minsk', 'Abu Dhabi', 'Boise', 'Albuquerque', 'Cheyenne', 'Sao Paulo']
[DIAG] Geographic split -> TRAIN cities: 280, VAL cities: 31, TEST cities: 10

/tmp/ipython-input-199474976.py:674: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  for city, g in df.groupby("City", sort=False):

[DIAG] TRAIN samples: 11207
[DIAG] VAL samples: 207
[DIAG] TEST samples: 2230
[ART] saved TSLib NPZ: artifacts/npz/tslib_cityanom_set3_seedS1003_seedM44_H6_W12_H6.npz
Epoch   1/200 | Train Obj: 12.2001 | Val Obj: 9.9731 | LR: 0.000600
Epoch   2/200 | Train Obj: 10.2952 | Val Obj: 9.2956 | LR: 0.000900
Epoch   3/200 | Train Obj: 9.7904 | Val Obj: 9.1929 | LR: 0.001200
Epoch   4/200 | Train Obj: 9.6504 | Val Obj: 9.0623 | LR: 0.001500
Epoch   5/200 | Train Obj: 9.5006 | Val Obj: 8.8905 | LR: 0.001800
Epoch   6/200 | Train Obj: 9.3578 | Val Obj: 8.8454 | LR: 0.002100
Epoch   7/200 | Train Obj: 9.2397 | Val Obj: 8.7690 | LR: 0.002400
Epoch   8/200 | Train Obj: 9.1405 | Val Obj: 8.9433 | LR: 0.002700
Epoch   9/200 | Train Obj: 9.0132 | Val Obj: 8.9964 | LR: 0.003000
Epoch  10/200 | Train Obj: 8.9097 | Val Obj: 9.0749 | LR: 0.003000
Epoch  11/200 | Train Obj: 8.7676 | Val Obj: 9.1859 | LR: 0.003000
Epoch  12/200 | Train Obj: 8.6345 | Val Obj: 9.3135 | LR: 0.002999
Epoch  13/200 | Train Obj: 8.4920 | Val Obj: 9.2745 | LR: 0.002998
Epoch  14/200 | Train Obj: 8.3616 | Val Obj: 9.3830 | LR: 0.002997
Epoch  15/200 | Train Obj: 8.2194 | Val Obj: 9.4074 | LR: 0.002995
Epoch  16/200 | Train Obj: 8.0876 | Val Obj: 9.4201 | LR: 0.002993
Epoch  17/200 | Train Obj: 7.9471 | Val Obj: 9.5606 | LR: 0.002990
Epoch  18/200 | Train Obj: 7.8380 | Val Obj: 9.5033 | LR: 0.002987
Epoch  19/200 | Train Obj: 7.7410 | Val Obj: 9.7224 | LR: 0.002983
Epoch  20/200 | Train Obj: 7.6253 | Val Obj: 9.5454 | LR: 0.002980
Epoch  21/200 | Train Obj: 7.5207 | Val Obj: 9.7560 | LR: 0.002975
Epoch  22/200 | Train Obj: 7.4400 | Val Obj: 9.6820 | LR: 0.002971
Epoch  23/200 | Train Obj: 7.3565 | Val Obj: 9.8029 | LR: 0.002965
Epoch  24/200 | Train Obj: 7.2753 | Val Obj: 9.7544 | LR: 0.002960
Epoch  25/200 | Train Obj: 7.2272 | Val Obj: 9.9136 | LR: 0.002954
Epoch  26/200 | Train Obj: 7.1742 | Val Obj: 9.9290 | LR: 0.002948
Epoch  27/200 | Train Obj: 7.0807 | Val Obj: 10.0145 | LR: 0.002941
Early stopping.
[ART] saved table: artifacts/tables/sign_mag_dependence_set3_seedS1003_seedM44_H6.csv and artifacts/tables/sign_mag_dependence_set3_seedS1003_seedM44_H6.tex
[DM] Model vs Persist | DM=-13.305 | p=0 | mean(d)=-1.899617 (negative=better)
[MBB] block=6 | CI95(mean d_model-pers)=[-2.192261,-1.558007]
[MBB] block=12 | CI95(mean d_model-pers)=[-2.212434,-1.528177]
[MBB] block=24 | CI95(mean d_model-pers)=[-2.324388,-1.424164]
[MBB] block=6 | RMSE(flat) CI95=[1.573,1.757]
[MBB] block=12 | RMSE(flat) CI95=[1.542,1.768]
[MBB] block=24 | RMSE(flat) CI95=[1.523,1.805]

===== GLOBAL TEST (JOINT; TEST cities; years > VAL) =====
H=6 | RMSE(flat): 1.66 °C [1.62, 1.70] | MAE(flat): 1.20 °C [1.17, 1.23] | NLL(per-h): 1.7454 nats | EnergyScore(joint): 2.5329
AVG over horizons | RMSE: 1.66 | MAE: 1.20 | CRPS: 0.8705 | Cov@95(avg): 92.5%
Clim-0(flat)  | RMSE: 1.67 | MAE: 1.22
Persist(flat) | RMSE: 2.16 | MAE: 1.53
TinyTransformer(flat) | RMSE: 1.63 | MAE: 1.18 | train_sec: 4.7

----- Per-horizon summary (h=1..H) -----
h= 1 | RMSE=1.62 | MAE=1.17 | CRPS=0.8402 | Cov@95=94.6%
h= 2 | RMSE=1.65 | MAE=1.19 | CRPS=0.8595 | Cov@95=92.4%
h= 3 | RMSE=1.66 | MAE=1.20 | CRPS=0.8720 | Cov@95=91.9%
h= 4 | RMSE=1.67 | MAE=1.21 | CRPS=0.8854 | Cov@95=91.2%
h= 5 | RMSE=1.68 | MAE=1.22 | CRPS=0.8846 | Cov@95=92.4%
h= 6 | RMSE=1.67 | MAE=1.21 | CRPS=0.8811 | Cov@95=92.5%

----- Decade-wise (TEST; grouped by first horizon year) -----
2000s | N=1080 | RMSE(flat)=1.62 | MAE(flat)=1.17 | CRPS(avg)=0.8459 | Cov@95(avg)=92.5%
2010s | N=1150 | RMSE(flat)=1.70 | MAE(flat)=1.24 | CRPS(avg)=0.8936 | Cov@95(avg)=92.5%

----- Regime-wise (TEST; grouped by first horizon year ranges) -----
2001-2004 | N= 480 | RMSE(flat)=1.65 | MAE(flat)=1.19 | CRPS(avg)=0.8654 | Cov@95(avg)=92.7%
2005-2007 | N= 360 | RMSE(flat)=1.70 | MAE(flat)=1.23 | CRPS(avg)=0.8893 | Cov@95(avg)=91.3%
2008-2010 | N= 360 | RMSE(flat)=1.46 | MAE(flat)=1.06 | CRPS(avg)=0.7716 | Cov@95(avg)=93.8%
2011-2014 | N= 480 | RMSE(flat)=1.72 | MAE(flat)=1.20 | CRPS(avg)=0.8704 | Cov@95(avg)=92.6%
2015-2017 | N= 360 | RMSE(flat)=1.72 | MAE(flat)=1.28 | CRPS(avg)=0.9272 | Cov@95(avg)=91.9%
2018-2020 | N= 190 | RMSE(flat)=1.66 | MAE(flat)=1.31 | CRPS(avg)=0.9276 | Cov@95(avg)=92.7%

----- Per-city (eval cities; years > VAL) -----
       City                            Region  N_test_windows RMSE (°C) MAE (°C) NLL (per-h) CRPS (°C)  CIA95 Cov@50 Cov@90 Cov@95  N_windows_in_test DM_vs_Persist      DM_p
      Dakar                            Africa             223      0.85     0.65      1.1228    0.4657 97.96%  42.5%  92.5%  96.9%                223        -6.365 1.102e-09
  Singapore                              Asia             223      0.45     0.35      0.6386    0.2617 94.74%  58.5%  99.0% 100.0%                223        -5.286 2.986e-07
   Brisbane           Australia/South Pacific             223      0.83     0.67      1.2437    0.4866 96.70%  39.6%  92.0%  98.1%                223        -4.944 1.506e-06
   Budapest                            Europe             223      2.06     1.65      2.2111    1.1934 93.31%  30.3%  80.6%  88.6%                223        -5.690 3.994e-08
      Minsk                            Europe             223      2.58     2.05      2.5739    1.5074 87.40%  30.3%  72.7%  83.0%                223        -9.491         0
  Abu Dhabi                       Middle East             223      1.05     0.82      1.4054    0.5931 98.77%  42.3%  89.4%  96.0%                223        -2.967  0.003336
      Boise                     North America             223      2.30     1.81      2.3499    1.3275 90.39%  31.8%  75.5%  85.9%                223        -6.381 1.014e-09
Albuquerque                     North America             223      1.64     1.32      1.9464    0.9426 97.47%  37.7%  84.3%  92.6%                223        -8.965         0
   Cheyenne                     North America             223      2.09     1.71      2.2912    1.2298 92.99%  30.8%  78.0%  88.3%                223        -9.261         0
  Sao Paulo South/Central America & Carribean             223      1.22     0.98      1.6713    0.6970 99.03%  41.3%  88.5%  95.4%                223        -8.624  1.11e-15

[DM] Per-city summary | significant(p<0.05): 10/10 | Fisher combined p=0
Not enough models for epistemic on eval_set=3 (found 0).

======================================================================
RUN | seed_split: 1004 | seed_model: 42 | device: cuda | H=6
======================================================================

/tmp/ipython-input-199474976.py:214: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

Using Colab cache for faster access to the 'daily-temperature-of-major-cities' dataset.
[DIAG] Available years: 1995..2020, cities: 321
[DIAG] Time splits -> TRAIN<= 1999, VAL: 2000..2000, TEST: 2001..2020
[DIAG] Horizon H=6

/tmp/ipython-input-199474976.py:301: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  for city, g in monthly.groupby("City", sort=False):

[DIAG] Eval set id: 4 | eval_seed: 127
[DIAG] Eval (TEST) cities: ['Lome', 'Tashkent', 'Ulan-bator', 'Auckland', 'Kiev', 'Kuwait', 'Cleveland', 'Cincinnati', 'Caribou', 'Panama City']
[DIAG] Geographic split -> TRAIN cities: 280, VAL cities: 31, TEST cities: 10

/tmp/ipython-input-199474976.py:674: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  for city, g in df.groupby("City", sort=False):

[DIAG] TRAIN samples: 11184
[DIAG] VAL samples: 203
[DIAG] TEST samples: 2230
[ART] saved TSLib NPZ: artifacts/npz/tslib_cityanom_set4_seedS1004_seedM42_H6_W12_H6.npz
Epoch   1/200 | Train Obj: 11.8922 | Val Obj: 11.6428 | LR: 0.000600
Epoch   2/200 | Train Obj: 10.1614 | Val Obj: 10.8134 | LR: 0.000900
Epoch   3/200 | Train Obj: 9.7358 | Val Obj: 10.6166 | LR: 0.001200
Epoch   4/200 | Train Obj: 9.5434 | Val Obj: 10.5629 | LR: 0.001500
Epoch   5/200 | Train Obj: 9.3828 | Val Obj: 10.4730 | LR: 0.001800
Epoch   6/200 | Train Obj: 9.2236 | Val Obj: 10.5834 | LR: 0.002100
Epoch   7/200 | Train Obj: 9.0987 | Val Obj: 10.4353 | LR: 0.002400
Epoch   8/200 | Train Obj: 9.0070 | Val Obj: 10.5800 | LR: 0.002700
Epoch   9/200 | Train Obj: 8.9132 | Val Obj: 10.6215 | LR: 0.003000
Epoch  10/200 | Train Obj: 8.8033 | Val Obj: 10.8428 | LR: 0.003000
Epoch  11/200 | Train Obj: 8.6827 | Val Obj: 10.9623 | LR: 0.003000
Epoch  12/200 | Train Obj: 8.5560 | Val Obj: 10.9809 | LR: 0.002999
Epoch  13/200 | Train Obj: 8.4449 | Val Obj: 10.9395 | LR: 0.002998
Epoch  14/200 | Train Obj: 8.3060 | Val Obj: 11.2129 | LR: 0.002997
Epoch  15/200 | Train Obj: 8.1681 | Val Obj: 11.1772 | LR: 0.002995
Epoch  16/200 | Train Obj: 8.0716 | Val Obj: 11.3328 | LR: 0.002993
Epoch  17/200 | Train Obj: 7.9558 | Val Obj: 11.4011 | LR: 0.002990
Epoch  18/200 | Train Obj: 7.8573 | Val Obj: 11.3255 | LR: 0.002987
Epoch  19/200 | Train Obj: 7.7707 | Val Obj: 11.4408 | LR: 0.002983
Epoch  20/200 | Train Obj: 7.6798 | Val Obj: 11.5007 | LR: 0.002980
Epoch  21/200 | Train Obj: 7.5981 | Val Obj: 11.5537 | LR: 0.002975
Epoch  22/200 | Train Obj: 7.5043 | Val Obj: 11.6869 | LR: 0.002971
Epoch  23/200 | Train Obj: 7.4240 | Val Obj: 11.6674 | LR: 0.002965
Epoch  24/200 | Train Obj: 7.3378 | Val Obj: 11.7325 | LR: 0.002960
Epoch  25/200 | Train Obj: 7.3009 | Val Obj: 11.8380 | LR: 0.002954
Epoch  26/200 | Train Obj: 7.1970 | Val Obj: 11.9398 | LR: 0.002948
Epoch  27/200 | Train Obj: 7.1345 | Val Obj: 12.0495 | LR: 0.002941
Early stopping.
[ART] saved table: artifacts/tables/sign_mag_dependence_set4_seedS1004_seedM42_H6.csv and artifacts/tables/sign_mag_dependence_set4_seedS1004_seedM42_H6.tex
[DM] Model vs Persist | DM=-13.207 | p=0 | mean(d)=-2.874412 (negative=better)
[MBB] block=6 | CI95(mean d_model-pers)=[-3.217076,-2.269587]
[MBB] block=12 | CI95(mean d_model-pers)=[-3.234678,-2.275504]
[MBB] block=24 | CI95(mean d_model-pers)=[-3.332418,-2.127591]
[MBB] block=6 | RMSE(flat) CI95=[1.881,2.113]
[MBB] block=12 | RMSE(flat) CI95=[1.857,2.132]
[MBB] block=24 | RMSE(flat) CI95=[1.810,2.181]

===== GLOBAL TEST (JOINT; TEST cities; years > VAL) =====
H=6 | RMSE(flat): 2.00 °C [1.94, 2.05] | MAE(flat): 1.36 °C [1.32, 1.39] | NLL(per-h): 1.8449 nats | EnergyScore(joint): 2.9637
AVG over horizons | RMSE: 2.00 | MAE: 1.36 | CRPS: 0.9970 | Cov@95(avg): 91.9%
Clim-0(flat)  | RMSE: 1.97 | MAE: 1.36
Persist(flat) | RMSE: 2.62 | MAE: 1.82
TinyTransformer(flat) | RMSE: 1.97 | MAE: 1.34 | train_sec: 5.5

----- Per-horizon summary (h=1..H) -----
h= 1 | RMSE=1.91 | MAE=1.31 | CRPS=0.9613 | Cov@95=91.7%
h= 2 | RMSE=2.00 | MAE=1.37 | CRPS=0.9971 | Cov@95=92.1%
h= 3 | RMSE=2.05 | MAE=1.39 | CRPS=1.0241 | Cov@95=90.6%
h= 4 | RMSE=2.04 | MAE=1.38 | CRPS=1.0082 | Cov@95=92.3%
h= 5 | RMSE=2.00 | MAE=1.35 | CRPS=0.9948 | Cov@95=92.5%
h= 6 | RMSE=1.99 | MAE=1.36 | CRPS=0.9964 | Cov@95=92.4%

----- Decade-wise (TEST; grouped by first horizon year) -----
2000s | N=1080 | RMSE(flat)=2.03 | MAE(flat)=1.38 | CRPS(avg)=1.0124 | Cov@95(avg)=92.0%
2010s | N=1150 | RMSE(flat)=1.97 | MAE(flat)=1.33 | CRPS(avg)=0.9825 | Cov@95(avg)=91.9%

----- Regime-wise (TEST; grouped by first horizon year ranges) -----
2001-2004 | N= 480 | RMSE(flat)=1.98 | MAE(flat)=1.36 | CRPS(avg)=0.9862 | Cov@95(avg)=93.3%
2005-2007 | N= 360 | RMSE(flat)=2.08 | MAE(flat)=1.42 | CRPS(avg)=1.0470 | Cov@95(avg)=90.5%
2008-2010 | N= 360 | RMSE(flat)=2.08 | MAE(flat)=1.41 | CRPS(avg)=1.0454 | Cov@95(avg)=90.6%
2011-2014 | N= 480 | RMSE(flat)=2.03 | MAE(flat)=1.28 | CRPS(avg)=0.9588 | Cov@95(avg)=92.0%
2015-2017 | N= 360 | RMSE(flat)=1.94 | MAE(flat)=1.40 | CRPS(avg)=1.0151 | Cov@95(avg)=91.5%
2018-2020 | N= 190 | RMSE(flat)=1.73 | MAE(flat)=1.24 | CRPS(avg)=0.8995 | Cov@95(avg)=94.4%

----- Per-city (eval cities; years > VAL) -----
       City                            Region  N_test_windows RMSE (°C) MAE (°C) NLL (per-h) CRPS (°C)  CIA95 Cov@50 Cov@90 Cov@95  N_windows_in_test DM_vs_Persist      DM_p
       Lome                            Africa             223      0.45     0.36      0.6735    0.2624 94.82%  51.9%  99.3%  99.9%                223        -6.735  1.39e-10
   Tashkent                              Asia             223      2.45     1.85      2.3820    1.3639 91.97%  34.4%  79.0%  87.4%                223        -6.153 3.517e-09
 Ulan-bator                              Asia             223      3.36     2.56      2.8140    1.9302 81.98%  26.8%  67.3%  77.9%                223        -7.879 1.461e-13
   Auckland           Australia/South Pacific             223      0.85     0.66      1.2723    0.4745 96.70%  48.9%  94.0%  98.1%                223        -9.370         0
       Kiev                            Europe             223      2.39     1.83      2.3978    1.3517 92.05%  34.7%  78.5%  87.4%                223        -8.344 7.772e-15
     Kuwait                       Middle East             223      1.37     1.02      1.6626    0.7396 98.73%  43.0%  90.7%  93.8%                223        -7.029 2.529e-11
  Cleveland                     North America             223      2.25     1.70      2.2574    1.2320 95.90%  36.2%  83.5%  91.1%                223        -7.528 1.281e-12
 Cincinnati                     North America             223      2.21     1.70      2.2686    1.2308 96.45%  34.2%  83.5%  91.6%                223        -8.530  2.22e-15
    Caribou                     North America             223      1.98     1.51      2.0811    1.0930 97.00%  38.3%  84.5%  92.2%                223        -8.284  1.11e-14
Panama City South/Central America & Carribean             223      0.51     0.39      0.6401    0.2913 94.82%  54.0%  98.1%  99.9%                223        -2.351   0.01959

[DM] Per-city summary | significant(p<0.05): 10/10 | Fisher combined p=0

======================================================================
RUN | seed_split: 1004 | seed_model: 43 | device: cuda | H=6
======================================================================

/tmp/ipython-input-199474976.py:214: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

Using Colab cache for faster access to the 'daily-temperature-of-major-cities' dataset.
[DIAG] Available years: 1995..2020, cities: 321
[DIAG] Time splits -> TRAIN<= 1999, VAL: 2000..2000, TEST: 2001..2020
[DIAG] Horizon H=6

/tmp/ipython-input-199474976.py:301: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  for city, g in monthly.groupby("City", sort=False):

[DIAG] Eval set id: 4 | eval_seed: 127
[DIAG] Eval (TEST) cities: ['Lome', 'Tashkent', 'Ulan-bator', 'Auckland', 'Kiev', 'Kuwait', 'Cleveland', 'Cincinnati', 'Caribou', 'Panama City']
[DIAG] Geographic split -> TRAIN cities: 280, VAL cities: 31, TEST cities: 10

/tmp/ipython-input-199474976.py:674: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  for city, g in df.groupby("City", sort=False):

[DIAG] TRAIN samples: 11184
[DIAG] VAL samples: 203
[DIAG] TEST samples: 2230
[ART] saved TSLib NPZ: artifacts/npz/tslib_cityanom_set4_seedS1004_seedM43_H6_W12_H6.npz
Epoch   1/200 | Train Obj: 11.8431 | Val Obj: 11.5804 | LR: 0.000600
Epoch   2/200 | Train Obj: 10.1966 | Val Obj: 10.8167 | LR: 0.000900
Epoch   3/200 | Train Obj: 9.7089 | Val Obj: 10.6151 | LR: 0.001200
Epoch   4/200 | Train Obj: 9.5387 | Val Obj: 10.6575 | LR: 0.001500
Epoch   5/200 | Train Obj: 9.3949 | Val Obj: 10.4369 | LR: 0.001800
Epoch   6/200 | Train Obj: 9.2556 | Val Obj: 10.3337 | LR: 0.002100
Epoch   7/200 | Train Obj: 9.1324 | Val Obj: 10.4297 | LR: 0.002400
Epoch   8/200 | Train Obj: 9.0615 | Val Obj: 10.4502 | LR: 0.002700
Epoch   9/200 | Train Obj: 8.9553 | Val Obj: 10.5011 | LR: 0.003000
Epoch  10/200 | Train Obj: 8.8396 | Val Obj: 10.9319 | LR: 0.003000
Epoch  11/200 | Train Obj: 8.6992 | Val Obj: 10.7188 | LR: 0.003000
Epoch  12/200 | Train Obj: 8.5512 | Val Obj: 10.8109 | LR: 0.002999
Epoch  13/200 | Train Obj: 8.4232 | Val Obj: 11.1374 | LR: 0.002998
Epoch  14/200 | Train Obj: 8.2765 | Val Obj: 11.1025 | LR: 0.002997
Epoch  15/200 | Train Obj: 8.1517 | Val Obj: 11.1065 | LR: 0.002995
Epoch  16/200 | Train Obj: 8.0288 | Val Obj: 11.2025 | LR: 0.002993
Epoch  17/200 | Train Obj: 7.9200 | Val Obj: 11.3713 | LR: 0.002990
Epoch  18/200 | Train Obj: 7.8154 | Val Obj: 11.5411 | LR: 0.002987
Epoch  19/200 | Train Obj: 7.7111 | Val Obj: 11.5760 | LR: 0.002983
Epoch  20/200 | Train Obj: 7.6085 | Val Obj: 11.5732 | LR: 0.002980
Epoch  21/200 | Train Obj: 7.5484 | Val Obj: 11.7568 | LR: 0.002975
Epoch  22/200 | Train Obj: 7.4684 | Val Obj: 11.8712 | LR: 0.002971
Epoch  23/200 | Train Obj: 7.3680 | Val Obj: 11.8525 | LR: 0.002965
Epoch  24/200 | Train Obj: 7.2934 | Val Obj: 12.0054 | LR: 0.002960
Epoch  25/200 | Train Obj: 7.2093 | Val Obj: 11.9221 | LR: 0.002954
Epoch  26/200 | Train Obj: 7.1709 | Val Obj: 12.1745 | LR: 0.002948
Early stopping.
[ART] saved table: artifacts/tables/sign_mag_dependence_set4_seedS1004_seedM43_H6.csv and artifacts/tables/sign_mag_dependence_set4_seedS1004_seedM43_H6.tex
[DM] Model vs Persist | DM=-13.538 | p=0 | mean(d)=-2.969909 (negative=better)
[MBB] block=6 | CI95(mean d_model-pers)=[-3.251856,-2.322009]
[MBB] block=12 | CI95(mean d_model-pers)=[-3.246641,-2.295041]
[MBB] block=24 | CI95(mean d_model-pers)=[-3.322097,-2.180562]
[MBB] block=6 | RMSE(flat) CI95=[1.866,2.089]
[MBB] block=12 | RMSE(flat) CI95=[1.833,2.115]
[MBB] block=24 | RMSE(flat) CI95=[1.791,2.159]

===== GLOBAL TEST (JOINT; TEST cities; years > VAL) =====
H=6 | RMSE(flat): 1.97 °C [1.92, 2.03] | MAE(flat): 1.35 °C [1.31, 1.38] | NLL(per-h): 1.8315 nats | EnergyScore(joint): 2.9357
AVG over horizons | RMSE: 1.97 | MAE: 1.35 | CRPS: 0.9857 | Cov@95(avg): 91.9%
Clim-0(flat)  | RMSE: 1.97 | MAE: 1.36
Persist(flat) | RMSE: 2.62 | MAE: 1.82
TinyTransformer(flat) | RMSE: 1.97 | MAE: 1.34 | train_sec: 4.7

----- Per-horizon summary (h=1..H) -----
h= 1 | RMSE=1.88 | MAE=1.30 | CRPS=0.9518 | Cov@95=91.5%
h= 2 | RMSE=1.96 | MAE=1.34 | CRPS=0.9799 | Cov@95=92.6%
h= 3 | RMSE=2.00 | MAE=1.36 | CRPS=0.9972 | Cov@95=92.3%
h= 4 | RMSE=2.00 | MAE=1.36 | CRPS=0.9996 | Cov@95=90.6%
h= 5 | RMSE=2.00 | MAE=1.36 | CRPS=0.9936 | Cov@95=91.5%
h= 6 | RMSE=1.99 | MAE=1.35 | CRPS=0.9919 | Cov@95=93.0%

----- Decade-wise (TEST; grouped by first horizon year) -----
2000s | N=1080 | RMSE(flat)=2.00 | MAE(flat)=1.37 | CRPS(avg)=0.9983 | Cov@95(avg)=91.8%
2010s | N=1150 | RMSE(flat)=1.95 | MAE(flat)=1.33 | CRPS(avg)=0.9737 | Cov@95(avg)=92.1%

----- Regime-wise (TEST; grouped by first horizon year ranges) -----
2001-2004 | N= 480 | RMSE(flat)=1.95 | MAE(flat)=1.34 | CRPS(avg)=0.9712 | Cov@95(avg)=92.9%
2005-2007 | N= 360 | RMSE(flat)=2.05 | MAE(flat)=1.40 | CRPS(avg)=1.0311 | Cov@95(avg)=90.4%
2008-2010 | N= 360 | RMSE(flat)=2.06 | MAE(flat)=1.40 | CRPS(avg)=1.0348 | Cov@95(avg)=90.3%
2011-2014 | N= 480 | RMSE(flat)=2.00 | MAE(flat)=1.27 | CRPS(avg)=0.9497 | Cov@95(avg)=92.5%
2015-2017 | N= 360 | RMSE(flat)=1.93 | MAE(flat)=1.39 | CRPS(avg)=1.0086 | Cov@95(avg)=91.8%
2018-2020 | N= 190 | RMSE(flat)=1.71 | MAE(flat)=1.24 | CRPS(avg)=0.8905 | Cov@95(avg)=94.6%

----- Per-city (eval cities; years > VAL) -----
       City                            Region  N_test_windows RMSE (°C) MAE (°C) NLL (per-h) CRPS (°C)  CIA95 Cov@50 Cov@90 Cov@95  N_windows_in_test DM_vs_Persist      DM_p
       Lome                            Africa             223      0.44     0.36      0.7164    0.2631 94.74%  57.3%  99.3% 100.0%                223        -6.678 1.921e-10
   Tashkent                              Asia             223      2.44     1.84      2.3661    1.3524 92.60%  38.0%  80.0%  88.0%                223        -6.199 2.731e-09
 Ulan-bator                              Asia             223      3.28     2.50      2.7937    1.8839 81.03%  26.8%  67.6%  77.0%                223        -8.400 5.329e-15
   Auckland           Australia/South Pacific             223      0.84     0.65      1.2649    0.4703 96.86%  51.4%  94.3%  98.0%                223        -9.369         0
       Kiev                            Europe             223      2.38     1.83      2.3769    1.3446 92.36%  36.3%  79.7%  87.7%                223        -8.286  1.11e-14
     Kuwait                       Middle East             223      1.35     1.00      1.6333    0.7300 99.50%  47.8%  91.5%  94.6%                223        -7.208 8.789e-12
  Cleveland                     North America             223      2.23     1.68      2.2158    1.2168 96.14%  38.2%  84.2%  91.3%                223        -7.732 3.653e-13
 Cincinnati                     North America             223      2.20     1.70      2.2396    1.2226 96.22%  35.9%  83.9%  91.4%                223        -8.679 8.882e-16
    Caribou                     North America             223      1.95     1.49      2.0523    1.0793 96.22%  39.7%  84.5%  91.4%                223        -8.791 4.441e-16
Panama City South/Central America & Carribean             223      0.51     0.40      0.6561    0.2936 94.82%  58.5%  98.6%  99.9%                223        -2.110   0.03596

[DM] Per-city summary | significant(p<0.05): 10/10 | Fisher combined p=0

======================================================================
RUN | seed_split: 1004 | seed_model: 44 | device: cuda | H=6
======================================================================

/tmp/ipython-input-199474976.py:214: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

Using Colab cache for faster access to the 'daily-temperature-of-major-cities' dataset.
[DIAG] Available years: 1995..2020, cities: 321
[DIAG] Time splits -> TRAIN<= 1999, VAL: 2000..2000, TEST: 2001..2020
[DIAG] Horizon H=6

/tmp/ipython-input-199474976.py:301: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  for city, g in monthly.groupby("City", sort=False):

[DIAG] Eval set id: 4 | eval_seed: 127
[DIAG] Eval (TEST) cities: ['Lome', 'Tashkent', 'Ulan-bator', 'Auckland', 'Kiev', 'Kuwait', 'Cleveland', 'Cincinnati', 'Caribou', 'Panama City']
[DIAG] Geographic split -> TRAIN cities: 280, VAL cities: 31, TEST cities: 10

/tmp/ipython-input-199474976.py:674: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  for city, g in df.groupby("City", sort=False):

[DIAG] TRAIN samples: 11184
[DIAG] VAL samples: 203
[DIAG] TEST samples: 2230
[ART] saved TSLib NPZ: artifacts/npz/tslib_cityanom_set4_seedS1004_seedM44_H6_W12_H6.npz
Epoch   1/200 | Train Obj: 12.0181 | Val Obj: 12.3747 | LR: 0.000600
Epoch   2/200 | Train Obj: 10.2109 | Val Obj: 10.7966 | LR: 0.000900
Epoch   3/200 | Train Obj: 9.6959 | Val Obj: 10.7416 | LR: 0.001200
Epoch   4/200 | Train Obj: 9.5469 | Val Obj: 10.5230 | LR: 0.001500
Epoch   5/200 | Train Obj: 9.4017 | Val Obj: 10.4643 | LR: 0.001800
Epoch   6/200 | Train Obj: 9.2501 | Val Obj: 10.5185 | LR: 0.002100
Epoch   7/200 | Train Obj: 9.1388 | Val Obj: 10.5433 | LR: 0.002400
Epoch   8/200 | Train Obj: 9.0359 | Val Obj: 10.4480 | LR: 0.002700
Epoch   9/200 | Train Obj: 8.9597 | Val Obj: 10.6685 | LR: 0.003000
Epoch  10/200 | Train Obj: 8.8467 | Val Obj: 10.8790 | LR: 0.003000
Epoch  11/200 | Train Obj: 8.7176 | Val Obj: 11.0212 | LR: 0.003000
Epoch  12/200 | Train Obj: 8.6077 | Val Obj: 11.1988 | LR: 0.002999
Epoch  13/200 | Train Obj: 8.5079 | Val Obj: 11.1305 | LR: 0.002998
Epoch  14/200 | Train Obj: 8.3678 | Val Obj: 11.1586 | LR: 0.002997
Epoch  15/200 | Train Obj: 8.2615 | Val Obj: 11.3653 | LR: 0.002995
Epoch  16/200 | Train Obj: 8.1354 | Val Obj: 11.3658 | LR: 0.002993
Epoch  17/200 | Train Obj: 8.0257 | Val Obj: 11.4991 | LR: 0.002990
Epoch  18/200 | Train Obj: 7.8783 | Val Obj: 11.4799 | LR: 0.002987
Epoch  19/200 | Train Obj: 7.8138 | Val Obj: 11.5682 | LR: 0.002983
Epoch  20/200 | Train Obj: 7.6731 | Val Obj: 11.7263 | LR: 0.002980
Epoch  21/200 | Train Obj: 7.5944 | Val Obj: 11.8856 | LR: 0.002975
Epoch  22/200 | Train Obj: 7.4989 | Val Obj: 11.6076 | LR: 0.002971
Epoch  23/200 | Train Obj: 7.4160 | Val Obj: 11.7204 | LR: 0.002965
Epoch  24/200 | Train Obj: 7.3668 | Val Obj: 11.6779 | LR: 0.002960
Epoch  25/200 | Train Obj: 7.2674 | Val Obj: 11.7597 | LR: 0.002954
Epoch  26/200 | Train Obj: 7.2007 | Val Obj: 11.7804 | LR: 0.002948
Epoch  27/200 | Train Obj: 7.1294 | Val Obj: 11.9137 | LR: 0.002941
Epoch  28/200 | Train Obj: 7.0606 | Val Obj: 11.9868 | LR: 0.002934
Early stopping.
[ART] saved table: artifacts/tables/sign_mag_dependence_set4_seedS1004_seedM44_H6.csv and artifacts/tables/sign_mag_dependence_set4_seedS1004_seedM44_H6.tex
[DM] Model vs Persist | DM=-13.091 | p=0 | mean(d)=-2.831448 (negative=better)
[MBB] block=6 | CI95(mean d_model-pers)=[-3.246690,-2.311282]
[MBB] block=12 | CI95(mean d_model-pers)=[-3.277589,-2.232681]
[MBB] block=24 | CI95(mean d_model-pers)=[-3.373633,-2.099788]
[MBB] block=6 | RMSE(flat) CI95=[1.895,2.127]
[MBB] block=12 | RMSE(flat) CI95=[1.860,2.144]
[MBB] block=24 | RMSE(flat) CI95=[1.812,2.193]

===== GLOBAL TEST (JOINT; TEST cities; years > VAL) =====
H=6 | RMSE(flat): 2.01 °C [1.95, 2.07] | MAE(flat): 1.37 °C [1.34, 1.41] | NLL(per-h): 1.8580 nats | EnergyScore(joint): 2.9769
AVG over horizons | RMSE: 2.01 | MAE: 1.37 | CRPS: 1.0062 | Cov@95(avg): 91.9%
Clim-0(flat)  | RMSE: 1.97 | MAE: 1.36
Persist(flat) | RMSE: 2.62 | MAE: 1.82
TinyTransformer(flat) | RMSE: 1.97 | MAE: 1.34 | train_sec: 5.5

----- Per-horizon summary (h=1..H) -----
h= 1 | RMSE=1.95 | MAE=1.34 | CRPS=0.9738 | Cov@95=92.5%
h= 2 | RMSE=2.03 | MAE=1.39 | CRPS=1.0100 | Cov@95=92.7%
h= 3 | RMSE=2.05 | MAE=1.40 | CRPS=1.0310 | Cov@95=90.7%
h= 4 | RMSE=2.03 | MAE=1.38 | CRPS=1.0170 | Cov@95=91.6%
h= 5 | RMSE=2.00 | MAE=1.35 | CRPS=0.9994 | Cov@95=92.0%
h= 6 | RMSE=1.99 | MAE=1.37 | CRPS=1.0061 | Cov@95=91.7%

----- Decade-wise (TEST; grouped by first horizon year) -----
2000s | N=1080 | RMSE(flat)=2.03 | MAE(flat)=1.39 | CRPS(avg)=1.0181 | Cov@95(avg)=91.7%
2010s | N=1150 | RMSE(flat)=1.98 | MAE(flat)=1.35 | CRPS(avg)=0.9951 | Cov@95(avg)=92.1%

----- Regime-wise (TEST; grouped by first horizon year ranges) -----
2001-2004 | N= 480 | RMSE(flat)=1.97 | MAE(flat)=1.36 | CRPS(avg)=0.9842 | Cov@95(avg)=92.9%
2005-2007 | N= 360 | RMSE(flat)=2.10 | MAE(flat)=1.44 | CRPS(avg)=1.0597 | Cov@95(avg)=90.1%
2008-2010 | N= 360 | RMSE(flat)=2.10 | MAE(flat)=1.43 | CRPS(avg)=1.0581 | Cov@95(avg)=90.5%
2011-2014 | N= 480 | RMSE(flat)=2.04 | MAE(flat)=1.30 | CRPS(avg)=0.9694 | Cov@95(avg)=92.5%
2015-2017 | N= 360 | RMSE(flat)=1.95 | MAE(flat)=1.41 | CRPS(avg)=1.0229 | Cov@95(avg)=92.0%
2018-2020 | N= 190 | RMSE(flat)=1.76 | MAE(flat)=1.28 | CRPS(avg)=0.9235 | Cov@95(avg)=93.4%

----- Per-city (eval cities; years > VAL) -----
       City                            Region  N_test_windows RMSE (°C) MAE (°C) NLL (per-h) CRPS (°C)  CIA95 Cov@50 Cov@90 Cov@95  N_windows_in_test DM_vs_Persist      DM_p
       Lome                            Africa             223      0.45     0.36      0.6892    0.2644 94.74%  55.4%  99.5% 100.0%                223        -7.452 2.025e-12
   Tashkent                              Asia             223      2.50     1.91      2.4302    1.4051 91.18%  33.5%  78.3%  86.6%                223        -5.929 1.157e-08
 Ulan-bator                              Asia             223      3.35     2.56      2.8021    1.9272 81.19%  25.1%  65.2%  77.1%                223        -7.821 2.105e-13
   Auckland           Australia/South Pacific             223      0.85     0.66      1.2726    0.4758 95.84%  51.9%  94.9%  99.0%                223        -8.771 4.441e-16
       Kiev                            Europe             223      2.43     1.87      2.4285    1.3787 91.73%  34.2%  78.3%  87.1%                223        -7.918 1.146e-13
     Kuwait                       Middle East             223      1.38     1.04      1.6758    0.7446 99.37%  42.0%  90.8%  94.9%                223        -6.756 1.228e-10
  Cleveland                     North America             223      2.25     1.71      2.2622    1.2389 95.51%  33.4%  83.3%  90.7%                223        -7.583 9.142e-13
 Cincinnati                     North America             223      2.23     1.73      2.2752    1.2459 96.06%  33.0%  84.3%  91.3%                223        -8.483 3.109e-15
    Caribou                     North America             223      1.98     1.51      2.1000    1.0966 96.92%  38.9%  83.8%  92.1%                223        -8.384 5.995e-15
Panama City South/Central America & Carribean             223      0.49     0.38      0.6444    0.2848 94.74%  57.5%  99.3% 100.0%                223        -3.526 0.0005122

[DM] Per-city summary | significant(p<0.05): 10/10 | Fisher combined p=0
Not enough models for epistemic on eval_set=4 (found 0).

######################################################################
EVAL-SET DISTRIBUTION (over 5 different 10-city TEST sets)
######################################################################
rmse_flat: 1.7076 ± 0.2054
mae_flat: 1.2145 ± 0.1116
nll_per_h: 1.7603 ± 0.0735
energy_joint: 2.6011 ± 0.2568
energy_ind: 2.6058 ± 0.2563
pit_ks: 0.1386 ± 0.0441
iw95: 6.1450 ± 0.6212
cal_ae: 0.0522 ± 0.0125
corr_offdiag: 0.1813 ± 0.0412
crps_avg: 0.8866 ± 0.0849
cov95_avg: 94.2296 ± 1.8891
[ART] zipped -> artifacts/artifacts.zip

##Notes for Colab: what to add in `data_loader.py` and `data_factory.py` for CityAnom NPZ

To train/evaluate Time-Series-Library models on the CityAnom `.npz` files, we need two things:
1) a custom Dataset class that knows how to read the NPZ format, and  
2) a registration step so `run.py` can find and instantiate that Dataset when passing `--data cityanom_npz`.

---

### 1) `data_provider/data_loader.py`: add a new Dataset class (e.g., `Dataset_CityAnomNPZ`)

In `data_loader.py` we define a class that inherits from `torch.utils.data.Dataset`. This class is responsible for loading the NPZ file via `np.load(os.path.join(root_path, data_path))` and building sliding windows according to `seq_len`, `label_len`, and `pred_len`.

```python
class Dataset_CityAnomNPZ(Dataset):
    """
    NPZ-based dataset that loads pre-windowed samples (train/val/test) exported from an external pipeline.
    Returns (seq_x, seq_y, seq_x_mark, seq_y_mark) compatible with Exp_Long_Term_Forecast.
    """
    def __init__(self, args, root_path, flag='train', size=None, features='S',
                 data_path='tslib_cityanom.npz', target='OT', scale=False, timeenc=1, freq='m', seasonal_patterns=None):
        assert flag in ['train', 'val', 'test']
        self.args = args
        self.flag = flag
        self.root_path = root_path
        self.data_path = data_path
        self.features = features
        self.target = target
        self.scale = False   # we already applied scaling upstream where needed

        fp = os.path.join(root_path, data_path)
        npz = np.load(fp)

        if flag == 'train':
            self.X = npz['X_train']
            self.y = npz['y_train']
            self.Xm = npz['X_train_mark']
            self.ym = npz['y_train_mark']
        elif flag == 'val':
            self.X = npz['X_val']
            self.y = npz['y_val']
            self.Xm = npz['X_val_mark']
            self.ym = npz['y_val_mark']
        else:
            self.X = npz['X_test']
            self.y = npz['y_test']
            self.Xm = npz['X_test_mark']
            self.ym = npz['y_test_mark']

        # seq_len / label_len / pred_len
        self.seq_len = int(self.X.shape[1])
        self.pred_len = int(self.y.shape[1])
        self.label_len = int(npz['label_len'][0]) if 'label_len' in npz else getattr(args, 'label_len', self.pred_len)

        # build seq_y as [label_len + pred_len, 1] (label part from last label_len of X, future from y)
        # done per-item in __getitem__ for simplicity

    def __len__(self):
        return int(self.X.shape[0])

    def __getitem__(self, index):
        seq_x = self.X[index]           # [seq_len, 1]
        fut_y = self.y[index]           # [pred_len, 1]
        seq_x_mark = self.Xm[index]     # [seq_len, 1]
        seq_y_mark = self.ym[index]     # [label_len+pred_len, 1]

        label_y = seq_x[-self.label_len:, :]  # last label_len from encoder input
        seq_y = np.concatenate([label_y, fut_y], axis=0).astype(np.float32)  # [label_len+pred_len, 1]

        return seq_x.astype(np.float32), seq_y, seq_x_mark.astype(np.float32), seq_y_mark.astype(np.float32)
```

---

### 2) `data_provider/data_factory.py`: register the Dataset in `data_dict`

In `data_factory.py`, add two updates:

**(a) Import the Dataset class**

`from data_provider.data_loader import Dataset_CityAnomNPZ`


**(b) Add it to data_dict**

`data_dict = {
    ...
    "cityanom_npz": Dataset_CityAnomNPZ,
}`

#Autoformer/Informer/PatchTST/DLinear

In [9]:
!pip -q install sktime
!pip -q install patool pyunpack

In [7]:
import os
os.makedirs("Time-Series-Library/data/cityanom", exist_ok=True)

In [8]:
import shutil, glob, os

paths = sorted(glob.glob("artifacts/npz/tslib_cityanom_*.npz"), key=os.path.getmtime)
npz_path = paths[-1]
dst = "Time-Series-Library/data/cityanom/tslib_cityanom_W12_H6.npz"
shutil.copy(npz_path, dst)
print("Copied to:", dst)

Copied to: Time-Series-Library/data/cityanom/tslib_cityanom_W12_H6.npz

In [18]:
import numpy as np
d = np.load("Time-Series-Library/data/cityanom/tslib_cityanom_W12_H6.npz")
print(d["X_train"].shape, d["y_train"].shape, d["X_train_mark"].shape, d["y_train_mark"].shape)
print("label_len:", d["label_len"][0], "pred_len:", d["pred_len"][0])

(11193, 12, 1) (11193, 6, 1) (11193, 12, 1) (11193, 12, 1)
label_len: 6 pred_len: 6

In [22]:
import os, re, glob, shutil, subprocess, math, pandas as pd

NPZ_SRC_DIR = "/content/artifacts/npz"
NPZ_DST = "/content/Time-Series-Library/data/cityanom/tslib_cityanom_W12_H6.npz"
RUNPY = "/content/Time-Series-Library/run.py"

def run_one(model_name, model_id, epochs=15, patience=5):
    cmd = [
        "python", RUNPY,
        "--task_name", "long_term_forecast",
        "--is_training", "1",
        "--model_id", model_id,
        "--model", model_name,
        "--data", "cityanom_npz",
        "--root_path", "/content/Time-Series-Library/data/cityanom/",
        "--data_path", "tslib_cityanom_W12_H6.npz",
        "--features", "S",
        "--freq", "m",
        "--seq_len", "12",
        "--label_len", "6",
        "--pred_len", "6",
        "--enc_in", "1", "--dec_in", "1", "--c_out", "1",
        "--embed", "timeF",
        "--d_model", "64",
        "--n_heads", "4",
        "--d_ff", "256",
        "--train_epochs", str(epochs),
        "--batch_size", "256",
        "--learning_rate", "1e-4",
        "--patience", str(patience),
        "--itr", "1",
        "--use_gpu"
    ]
    out = subprocess.run(cmd, capture_output=True, text=True, cwd="/content/Time-Series-Library")
    m = re.findall(r"mse:([0-9.]+), mae:([0-9.]+)", out.stdout)
    if not m:
        return None, out.stdout[-2000:]
    mse = float(m[-1][0]); mae = float(m[-1][1])
    rmse = math.sqrt(mse)
    return {"mse": mse, "mae": mae, "rmse": rmse}, out.stdout

# list all NPZs
npz_files = sorted(glob.glob(os.path.join(NPZ_SRC_DIR, "tslib_cityanom_set*_seedS*_seedM*_H6_W12_H6.npz")))
print("Found NPZ:", len(npz_files))

rows = []
for f in npz_files:
    base = os.path.basename(f)
    # extract set and seedM
    m = re.search(r"set(\d+)_seedS(\d+)_seedM(\d+)_H6_W12_H6\.npz", base)
    set_id = int(m.group(1)); seedS = int(m.group(2)); seedM = int(m.group(3))

    # copy npz to expected location
    shutil.copy(f, NPZ_DST)

    # run Autoformer
    res, log = run_one("Autoformer", f"CityAnom_set{set_id}_M{seedM}_Autoformer", epochs=15, patience=5)
    if res is None:
        print("Autoformer failed for", base)
        print(log[-800:])
        break
    rows.append({"model":"Autoformer","set":set_id,"seedM":seedM, **res})

    # run Informer
    res, log = run_one("Informer", f"CityAnom_set{set_id}_M{seedM}_Informer", epochs=15, patience=5)
    if res is None:
        print("Informer failed for", base)
        print(log[-800:])
        break
    rows.append({"model":"Informer","set":set_id,"seedM":seedM, **res})

df = pd.DataFrame(rows)
df

Found NPZ: 15

         model  set  seedM       mse       mae      rmse
0   Autoformer    0     42  2.067715  1.067140  1.437955
1     Informer    0     42  2.029456  1.051053  1.424590
2   Autoformer    0     43  2.067715  1.067140  1.437955
3     Informer    0     43  2.029469  1.051082  1.424594
4   Autoformer    0     44  2.067715  1.067140  1.437955
5     Informer    0     44  2.029251  1.050990  1.424518
6   Autoformer    1     42  2.771665  1.208672  1.664832
7     Informer    1     42  2.782815  1.217471  1.668177
8   Autoformer    1     43  2.771665  1.208672  1.664832
9     Informer    1     43  2.782886  1.217476  1.668198
10  Autoformer    1     44  2.771665  1.208672  1.664832
11    Informer    1     44  2.782647  1.217419  1.668127
12  Autoformer    2     42  3.083267  1.226713  1.755924
13    Informer    2     42  3.077859  1.229939  1.754383
14  Autoformer    2     43  3.083267  1.226713  1.755924
15    Informer    2     43  3.077801  1.229915  1.754366
16  Autoformer    2     44  3.083268  1.226713  1.755924
17    Informer    2     44  3.077816  1.229926  1.754371
18  Autoformer    3     42  2.665215  1.184452  1.632549
19    Informer    3     42  2.657771  1.181720  1.630267
20  Autoformer    3     43  2.665215  1.184452  1.632549
21    Informer    3     43  2.657770  1.181720  1.630267
22  Autoformer    3     44  2.665215  1.184452  1.632549
23    Informer    3     44  2.657767  1.181719  1.630266
24  Autoformer    4     42  3.821086  1.353262  1.954760
25    Informer    4     42  3.878795  1.347073  1.969466
26  Autoformer    4     43  3.821086  1.353262  1.954760
27    Informer    4     43  3.878774  1.347071  1.969460
28  Autoformer    4     44  3.821086  1.353262  1.954760
29    Informer    4     44  3.878798  1.347077  1.969466

In [24]:
metrics = ["mse","mae","rmse"]

per_set_model = df.groupby(["set","model"])[metrics].mean().reset_index()
per_set_all   = df.groupby("set")[metrics].mean().reset_index()

final_model = df.groupby("model")[metrics].mean().reset_index()
final_all   = df[metrics].mean()

display(per_set_model.round(2))
display(per_set_all.round(2))
display(final_model.round(2))
print("FINAL GLOBAL:", final_all.round(2).to_dict())

   set       model   mse   mae  rmse
0    0  Autoformer  2.07  1.07  1.44
1    0    Informer  2.03  1.05  1.42
2    1  Autoformer  2.77  1.21  1.66
3    1    Informer  2.78  1.22  1.67
4    2  Autoformer  3.08  1.23  1.76
5    2    Informer  3.08  1.23  1.75
6    3  Autoformer  2.67  1.18  1.63
7    3    Informer  2.66  1.18  1.63
8    4  Autoformer  3.82  1.35  1.95
9    4    Informer  3.88  1.35  1.97

   set   mse   mae  rmse
0    0  2.05  1.06  1.43
1    1  2.78  1.21  1.67
2    2  3.08  1.23  1.76
3    3  2.66  1.18  1.63
4    4  3.85  1.35  1.96

        model   mse   mae  rmse
0  Autoformer  2.88  1.21  1.69
1    Informer  2.89  1.21  1.69

FINAL GLOBAL: {'mse': 2.88, 'mae': 1.21, 'rmse': 1.69}

In [25]:
import os
print(sorted([os.path.splitext(f)[0] for f in os.listdir("/content/Time-Series-Library/models") if f.endswith(".py")]))

['Autoformer', 'Chronos', 'Chronos2', 'Crossformer', 'DLinear', 'ETSformer', 'FEDformer', 'FiLM', 'FreTS', 'Informer', 'KANAD', 'Koopa', 'LightTS', 'MICN', 'MSGNet', 'Mamba', 'MambaSimple', 'Moirai', 'MultiPatchFormer', 'Nonstationary_Transformer', 'PAttn', 'PatchTST', 'Pyraformer', 'Reformer', 'SCINet', 'SegRNN', 'Sundial', 'TSMixer', 'TemporalFusionTransformer', 'TiDE', 'TiRex', 'TimeFilter', 'TimeMixer', 'TimeMoE', 'TimeXer', 'TimesFM', 'TimesNet', 'Transformer', 'WPMixer', '__init__', 'iTransformer']

In [30]:
# Setup + run_one (PatchTST / DLinear)

import os, re, glob, shutil, subprocess, math, pandas as pd

NPZ_SRC_DIR = "/content/artifacts/npz"
NPZ_DST     = "/content/Time-Series-Library/data/cityanom/tslib_cityanom_W12_H6.npz"
RUNPY       = "/content/Time-Series-Library/run.py"
CWD         = "/content/Time-Series-Library"

def run_one(model_name, model_id, epochs=15, patience=5, extra_args=None):
    # extra_args: list gen ["--patch_len","3"] etc.
    extra_args = extra_args or []

    # safety
    cleaned = []
    i = 0
    while i < len(extra_args):
        if extra_args[i] == "--stride":
            i += 2
            continue
        cleaned.append(extra_args[i]); i += 1
    extra_args = cleaned

    cmd = [
        "python", RUNPY,
        "--task_name", "long_term_forecast",
        "--is_training", "1",
        "--model_id", model_id,
        "--model", model_name,
        "--data", "cityanom_npz",
        "--root_path", "/content/Time-Series-Library/data/cityanom/",
        "--data_path", "tslib_cityanom_W12_H6.npz",
        "--features", "S",
        "--freq", "m",
        "--seq_len", "12",
        "--label_len", "6",
        "--pred_len", "6",
        "--enc_in", "1", "--dec_in", "1", "--c_out", "1",
        "--embed", "timeF",
        "--d_model", "64",
        "--n_heads", "4",
        "--d_ff", "256",
        "--train_epochs", str(epochs),
        "--batch_size", "256",
        "--learning_rate", "1e-4",
        "--patience", str(patience),
        "--itr", "1",
        "--use_gpu",
        *extra_args
    ]

    out = subprocess.run(cmd, capture_output=True, text=True, cwd=CWD)

    if out.returncode != 0:
        print(f"FAILED: {model_name} {model_id} returncode={out.returncode}")
        print("---- STDERR (tail) ----")
        print(out.stderr[-6000:])
        print("---- STDOUT (tail) ----")
        print(out.stdout[-2000:])
        return None, out.stderr + "\n" + out.stdout

    m = re.findall(r"mse:([0-9.]+), mae:([0-9.]+)", out.stdout)
    if not m:
        print(f"WARNING: nu am găsit 'mse/mae' în stdout pentru {model_name} {model_id}")
        print(out.stdout[-2000:])
        return None, out.stdout

    mse = float(m[-1][0]); mae = float(m[-1][1])
    rmse = math.sqrt(mse)
    return {"mse": mse, "mae": mae, "rmse": rmse}, out.stdout

In [31]:
npz_files = sorted(glob.glob(os.path.join(NPZ_SRC_DIR, "tslib_cityanom_set*_seedS*_seedM*_H6_W12_H6.npz")))
print("Found NPZ:", len(npz_files))

rows = []
for f in npz_files:
    base = os.path.basename(f)
    m = re.search(r"set(\d+)_seedS(\d+)_seedM(\d+)_H6_W12_H6\.npz", base)
    if not m:
        print("Skip (pattern mismatch):", base)
        continue

    set_id = int(m.group(1)); seedS = int(m.group(2)); seedM = int(m.group(3))

    # place current NPZ in the location expected by the loader
    shutil.copy(f, NPZ_DST)

    # PatchTST
    patch_args = ["--patch_len", "3", "--pos", "1"]
    res, _ = run_one("PatchTST", f"CityAnom_set{set_id}_M{seedM}_PatchTST",
                     epochs=15, patience=5, extra_args=patch_args)
    if res is None:
        print("Stop la PatchTST pentru", base)
        break
    rows.append({"model": "PatchTST", "set": set_id, "seedM": seedM, **res})

    # DLinear (for seq_len=12, small moving_avg)
    dlinear_args = ["--moving_avg", "3"]  # optional: add "--individual"
    # dlinear_args += ["--individual"]
    res, _ = run_one("DLinear", f"CityAnom_set{set_id}_M{seedM}_DLinear",
                     epochs=15, patience=5, extra_args=dlinear_args)
    if res is None:
        print("Stop la DLinear pentru", base)
        break
    rows.append({"model": "DLinear", "set": set_id, "seedM": seedM, **res})

df2 = pd.DataFrame(rows)
df2

Found NPZ: 15

       model  set  seedM       mse       mae      rmse
0   PatchTST    0     42  2.020355  1.051469  1.421392
1    DLinear    0     42  2.008951  1.049296  1.417375
2   PatchTST    0     43  2.020355  1.051469  1.421392
3    DLinear    0     43  2.008951  1.049296  1.417375
4   PatchTST    0     44  2.020355  1.051469  1.421392
5    DLinear    0     44  2.008951  1.049296  1.417375
6   PatchTST    1     42  2.832615  1.215249  1.683037
7    DLinear    1     42  2.674918  1.179762  1.635518
8   PatchTST    1     43  2.832615  1.215249  1.683037
9    DLinear    1     43  2.674918  1.179762  1.635518
10  PatchTST    1     44  2.832615  1.215249  1.683037
11   DLinear    1     44  2.674918  1.179762  1.635518
12  PatchTST    2     42  3.203830  1.241916  1.789925
13   DLinear    2     42  3.040743  1.220733  1.743773
14  PatchTST    2     43  3.203830  1.241916  1.789925
15   DLinear    2     43  3.040743  1.220733  1.743773
16  PatchTST    2     44  3.203830  1.241916  1.789925
17   DLinear    2     44  3.040743  1.220733  1.743773
18  PatchTST    3     42  2.717122  1.184095  1.648369
19   DLinear    3     42  2.539620  1.156901  1.593619
20  PatchTST    3     43  2.717122  1.184095  1.648369
21   DLinear    3     43  2.539620  1.156901  1.593619
22  PatchTST    3     44  2.717122  1.184095  1.648369
23   DLinear    3     44  2.539620  1.156901  1.593619
24  PatchTST    4     42  4.010197  1.373326  2.002548
25   DLinear    4     42  3.657762  1.320575  1.912528
26  PatchTST    4     43  4.010197  1.373326  2.002548
27   DLinear    4     43  3.657762  1.320575  1.912528
28  PatchTST    4     44  4.010197  1.373326  2.002548
29   DLinear    4     44  3.657762  1.320575  1.912528

In [33]:
metrics = ["mse", "mae", "rmse"]

per_set_model = df2.groupby(["set", "model"])[metrics].mean().reset_index()
final_model   = df2.groupby("model")[metrics].mean().reset_index()
final_all     = df2[metrics].mean()

display(per_set_model.round(2))
display(final_model.round(2))
print("FINAL GLOBAL:", final_all.round(6).to_dict())

   set     model   mse   mae  rmse
0    0   DLinear  2.01  1.05  1.42
1    0  PatchTST  2.02  1.05  1.42
2    1   DLinear  2.67  1.18  1.64
3    1  PatchTST  2.83  1.22  1.68
4    2   DLinear  3.04  1.22  1.74
5    2  PatchTST  3.20  1.24  1.79
6    3   DLinear  2.54  1.16  1.59
7    3  PatchTST  2.72  1.18  1.65
8    4   DLinear  3.66  1.32  1.91
9    4  PatchTST  4.01  1.37  2.00

      model   mse   mae  rmse
0   DLinear  2.78  1.19  1.66
1  PatchTST  2.96  1.21  1.71

FINAL GLOBAL: {'mse': 2.870611, 'mae': 1.199332, 'rmse': 1.684808}